### ISSUE TITLE
要被搞疯了，求textarea如何优雅的使用

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#100]
如果直接使用textarea，那么就无法使用小程序的特殊属性
为什么要使用特殊属性，是因为现在官方还有很多坑没填，不用特殊属性做不到兼容

如果用 wx-textarea 呢，居然不能覆盖样式

怎么办啊

**Comment by xmsz** [comment]
textarea穿不进参数，发现是因为不支持驼峰？？？
adjust-position 不能写成  adjustPosition

更搞笑的来了 adjust-position={false} 是不行的，必须是adjust-position="false" 。。。。。 这个是官方的问题。

就这个属性已经搞死我，按照常量 adjustPosition={false} ， 没毛病吧
结果不能是adjust-position={false}  ， 不能是adjustPosition="false"。得是adjust-position="false"

试到怀疑人生

**Comment by xmsz** [comment]
然后问题在于， 如果设置adjust-position={false}， 则下面这段函数获取的是 undefined，因为是前面生成 node 树的时候，判断为 false 所以丢掉了 @JuneAndGreen 


```
{
        name: 'adjustPosition',
        get(domNode) {
            const value = domNode.getAttribute('adjust-position')
            console.log(value, value !== undefined ? !!value : true)
            return value !== undefined ? !!value : true
        },
    }
```

**Comment by wzs28150** [comment]
我也遇到了。。wx-textarea居然改不了样式- -  直接这样都写不进去
textarea {
  background-color: #fff;
}

**Comment by xmsz** [comment]
> 我也遇到了。。wx-textarea居然改不了样式- - 直接这样都写不进去
> textarea {
> background-color: #fff;
> }

没错，所以现在至少两个 bug
1. wx-textarea， 无法覆盖 style 和 class，显示的是 style: undefined
2. textarea包括其他组件，无法传入{false}，会被过滤掉 @JuneAndGreen

**Comment by wzs28150** [comment]
使用wx- 在web端你是怎么处理的? web端会警告 wx-textarea 不识别 没有注册组件

**Comment by xmsz** [comment]
> 使用wx- 在web端你是怎么处理的? web端会警告 wx-textarea 不识别 没有注册组件

推荐还是用textarea，先自己该源码兼容一下
miniprogram-element包里搜索 textarea ，然后根据需求改一下。等修复了再换回来

**Comment by wzs28150** [comment]
我用别的组件也是,不只是textarea,wx-swiper小程序和web就没办法用同一个来实现,小程序端我可以用check-reduce 屏蔽掉web端写的swiper,但是web端要屏蔽掉wx-swiper就没有这样的标签 就得自己写loader。。。

**Comment by JuneAndGreen** [comment]
有几个问题，我逐个回答一下哈：
1、使用 wx-textarea 的 class、style 没有问题，因为 textarea 不需要使用 wx-textarea 的方式渲染，直接使用 textarea 标签即可，它会自动转成小程序的 textarea 组件的（[文档](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6)）：
![image](https://user-images.githubusercontent.com/7931744/75619100-6bda5b00-5bb2-11ea-8e03-2fdd25feaea7.png)
2、转成使用 textarea，样式要怎么写呢？因为目前不支持 template 递归，所以只能使用自定义组件的方式来动态渲染内置组件，这就导致了会多一层容器（[文档](https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91)）：
![image](https://user-images.githubusercontent.com/7931744/75619125-b3f97d80-5bb2-11ea-8186-3fabbb3b3297.png)
![image](https://user-images.githubusercontent.com/7931744/75619127-bb208b80-5bb2-11ea-8836-245cb258acba.png)
3、遇到属性默认值为 true，设置成 false 后会被 vue 干掉，这个要怎么办？这里使用其他 falsy 的值即可。
![image](https://user-images.githubusercontent.com/7931744/75619132-da1f1d80-5bb2-11ea-832d-bd2f165cf54b.png)

**Comment by JuneAndGreen** [comment]
然后对于那种希望可以同时兼容小程序和web端的组件，可以使用 kbone-ui（[文档](https://wechat-miniprogram.github.io/kbone/docs/ui/intro/)），这个库目前只有 vue 版本，主要就是做这个工作的。

**Comment by xmsz** [comment]
> 有几个问题，我逐个回答一下哈：
> 1、使用 wx-textarea 的 class、style 没有问题，因为 textarea 不需要使用 wx-textarea 的方式渲染，直接使用 textarea 标签即可，它会自动转成小程序的 textarea 组件的（[文档](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6)）：
> ![image](https://user-images.githubusercontent.com/7931744/75619100-6bda5b00-5bb2-11ea-8e03-2fdd25feaea7.png)
> 2、转成使用 textarea，样式要怎么写呢？因为目前不支持 template 递归，所以只能使用自定义组件的方式来动态渲染内置组件，这就导致了会多一层容器（[文档](https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91)）：
> ![image](https://user-images.githubusercontent.com/7931744/75619125-b3f97d80-5bb2-11ea-8186-3fabbb3b3297.png)
> ![image](https://user-images.githubusercontent.com/7931744/75619127-bb208b80-5bb2-11ea-8836-245cb258acba.png)
> 3、遇到属性默认值为 true，设置成 false 后会被 vue 干掉，这个要怎么办？这里使用其他 falsy 的值即可。
> ![image](https://user-images.githubusercontent.com/7931744/75619132-da1f1d80-5bb2-11ea-832d-bd2f165cf54b.png)

第三点完全解决了我的需求，非常感谢。这个在哪里查阅
以往 vue 写的时候就是通过 true 和 false 来切换，或者一些属性是用 off。但没遇到过设置false 不行的必须设空或0的情况

是不是说在 kbone 会这样？

**Comment by xmsz** [comment]
> 有几个问题，我逐个回答一下哈：
> 1、使用 wx-textarea 的 class、style 没有问题，因为 textarea 不需要使用 wx-textarea 的方式渲染，直接使用 textarea 标签即可，它会自动转成小程序的 textarea 组件的（[文档](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6)）：
> ![image](https://user-images.githubusercontent.com/7931744/75619100-6bda5b00-5bb2-11ea-8e03-2fdd25feaea7.png)
> 2、转成使用 textarea，样式要怎么写呢？因为目前不支持 template 递归，所以只能使用自定义组件的方式来动态渲染内置组件，这就导致了会多一层容器（[文档](https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91)）：
> ![image](https://user-images.githubusercontent.com/7931744/75619125-b3f97d80-5bb2-11ea-8186-3fabbb3b3297.png)
> ![image](https://user-images.githubusercontent.com/7931744/75619127-bb208b80-5bb2-11ea-8836-245cb258acba.png)
> 3、遇到属性默认值为 true，设置成 false 后会被 vue 干掉，这个要怎么办？这里使用其他 falsy 的值即可。
> ![image](https://user-images.githubusercontent.com/7931744/75619132-da1f1d80-5bb2-11ea-832d-bd2f165cf54b.png)

第一情况是，原生小程序下
```
<textarea class='test'>abc</textarea>
textarea {
  font-size: 72px;
}
.test {
  font-size: 72px;
}
```
两种方式写都没问题

现在使用 wx-textarea ，
```
 <wx-textarea class="test">abc</wx-textarea>
textarea {
  font-size: 72px;
}
.test {
  font-size: 72px;
}
```
是不能使用，没有用源码调试，所以不知道原因
class 和 style 都没传进去
![image](https://user-images.githubusercontent.com/5879146/75619979-042a0d00-5bbe-11ea-8f6a-b11ea7f2bcc1.png)

**Comment by JuneAndGreen** [comment]
@xmsz 改成 <textarea class="test">abc</textarea>，如同上面文档所说的，不要使用 wx- 前缀试试。

**Comment by JuneAndGreen** [comment]
@xmsz 或者有兴趣的话，可以尝试一下 beta 版， miniprogram-element@beta 和 miniprogram-render@beta，这两个包去掉了对 textarea 的包裹层，也就不需要使用我上面提到的第2点那样用比较迂回的方式来编写样式了。

**Comment by xmsz** [comment]
> @xmsz 或者有兴趣的话，可以尝试一下 beta 版， miniprogram-element@beta 和 miniprogram-render@beta，这两个包去掉了对 textarea 的包裹层，也就不需要使用我上面提到的第2点那样用比较迂回的方式来编写样式了。

我现在用 input 替代了，可能暂时没时间测试了

**Comment by Hxmic** [comment]
我在vue中无法新建路由，什么鬼？
