### ISSUE TITLE
求支持 rich-text

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#103]
目前原生组件还不支持 rich-text，希望支持一下

**Comment by JuneAndGreen** [comment]
miniprogram-element@0.8.3 已支持。

但是这里有一个问题，就是 rich-text 组件官方还没有支持全局样式，因此富文本里的 class 应用不上外部写的样式。这个已和相关组件负责同学提了需求，需要等基础库支持。如果这里着急使用富文本渲染的话，直接使用 innerHTML 就可以的，比如 vue 的 v-html 指令。

**Comment by xmsz** [comment]
> miniprogram-element@0.8.3 已支持。
> 
> 但是这里有一个问题，就是 rich-text 组件官方还没有支持全局样式，因此富文本里的 class 应用不上外部写的样式。这个已和相关组件负责同学提了需求，需要等基础库支持。如果这里着急使用富文本渲染的话，直接使用 innerHTML 就可以的，比如 vue 的 v-html 指令。

非常非常的感谢！

对，我也发现富文本里无法使用外部 class，这个我先临时处理，等后续支持再改

本来是用 domPropsInnerHTML去写，但是发现 微信小程序里除了 text 可以支持长按复制以外，其他都不行。但是又发现微信小程序里的 rich-text 虽然明面不支持，但是支持 css 属性  user-select。所以就必须得用 rich-text。web的话就不担心
