### ISSUE TITLE
关于vue-router的hash模式

### ISSUE THREAD

**Issue by yaozitong666** [Tencent/kbone#105]
如果要使用vue-router的hash模式，小程序要怎么配置路由才能跳转过去？

**Comment by xxxBW** [comment]
用 reoter-link ，单页应用的话在小程序也是只有一个页面的

**Comment by xxxBW** [comment]
> 如果要使用vue-router的hash模式，小程序要怎么配置路由才能跳转过去？
用 reoter-link ，单页应用的话在小程序也是只有一个页面的

**Comment by xxxBW** [comment]
> 如果要使用vue-router的hash模式，小程序要怎么配置路由才能跳转过去？

用 reoter-link ，单页应用的话在小程序也是只有一个页面的

**Comment by JuneAndGreen** [comment]
mp-webpack-plugin 里配置该页面的 url 即可，hashchange 事件是支持的，如 xxxBW 所说，使用 router-link 或者 $router 对象的方法跳转即可。
