### ISSUE TITLE
是否支持antd,antv,d3,f2等第三方库在两端的通用，还是是配型如何？

### ISSUE THREAD

**Issue by hopperhuang** [Tencent/kbone#106]
如题。是否支持第三方库在两端的通用，如果不支持的话，需要注意什么？

**Comment by xxxBW** [comment]
> 如题。是否支持第三方库在两端的通用，如果不支持的话，需要注意什么？

第三方库有些接口无法兼容，比如 getComputedStyle、getBoundingClientRect 等接口，建议使用kbone-ui
