### ISSUE TITLE
用kbone-cli 来快速开发 提示‘模板 vue 不存在’？

### ISSUE THREAD

**Issue by wzya** [Tencent/kbone#107]
kbone init my-app 创建项目后 选vue  提示‘模板 vue 不存在’，请问如何解决？

**Comment by xxxBW** [comment]
https://github.com/wechat-miniprogram/kbone-template-vue

建议直接下载使用呢，可能是git配置有问题导致clone失败。

**Comment by wzya** [comment]
有办法修复git配置吗

**Comment by xxxBW** [comment]
查下git是不是有代理
git config --global --get http.proxy
git config --global --get https.proxy

有的话取消代理试试
git config --global --unset http.proxy
git config --global --unset https.proxy
