### ISSUE TITLE
如果让onShareAppMessage分享path是自己控制？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#108]
目前通过onShareAppMessage设置的 path 会被自动变成
```
pages/mine/index?targeturl=%2Fpages%2Fhome%2Findex&type=share

```

这个规则是知道的，但是我能不能自己控制这个 path。因为很多场景。

例如，我所有页面分享都要跳到首页。分享 path 是'/page/home/index'。但是现在得话，我得在每个路由跳转前判断，这个肯定不智能。因为页面会闪/左滑两下。

我目前得要求仅是支持小程序，没有兼容 h5 的需求。但是被这个限制了能力。

**Comment by xxxBW** [comment]
分享其他页面的时候会先跳首页再跳到要分享的页面么

**Comment by xmsz** [comment]
> 分享其他页面的时候会先跳首页再跳到要分享的页面么

看清楚需求，是想要分享出去的path 是其他页面的 path。

如果按照目前的方式，分享出去就是当前页面路径。

**Comment by JuneAndGreen** [comment]
mp-webpack-plugin@0.8.4 中已支持。
参考文档：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-onshareappmessage
参考 demo：https://github.com/Tencent/kbone/blob/develop/examples/demo5/src/page1/App.vue

PS：如果需要封装成 kbone 能识别的 url，可参考 qa：
![image](https://user-images.githubusercontent.com/7931744/76137498-b8bda600-6078-11ea-8b85-57817c7f071d.png)
