### ISSUE TITLE
这个里面的http模块web端与小程序端怎么推荐

### ISSUE THREAD

**Issue by honeyTi** [Tencent/kbone#110]
又没有统一的web http请求工具类，还是说直接用miniprogram那一套就可以了

**Comment by JuneAndGreen** [comment]
XMLHttpRequest 对象的兼容目前暂未实现，不过后续我们会提供 kbone-api 来支持这种情况，这个还在开发中，在不久后可用。目前有两个方案可以考虑：
1、使用第三方库
![image](https://user-images.githubusercontent.com/7931744/76136437-6e362c80-606c-11ea-9a98-613a341a898b.png)
2、开发者自己封装请求接口，使用条件判断，不同环境走不同的方式进行请求
