### ISSUE TITLE
静态资源和requiredBackgroundModes

### ISSUE THREAD

**Issue by codetest** [Tencent/kbone#111]
对应通过url-loader转换的本地静态资源图片，应该是mp plugin再处理，需要拷贝到miniprogram-element底下才能够访问。requiredBackgroundModes好像没有再mp plugin的options里面？

**Comment by xxxBW** [comment]
静态资源可以考虑转成 base64 或者使用网络地址
requiredBackgroundModes  可以在 appExtraConfig 这里配置

**Comment by codetest** [comment]
> 静态资源可以考虑转成 base64 或者使用网络地址
> requiredBackgroundModes 可以在 appExtraConfig 这里配置

转base64就多1/3的体积了。
