### ISSUE TITLE
KSwiper 更改current/v-model 没有反应

### ISSUE THREAD

**Issue by wu0211** [Tencent/kbone#112]
bindchange 属性也没有执行

![image](https://user-images.githubusercontent.com/34398833/76162611-39180000-617a-11ea-9ecc-79d879e0c29c.png)
![image](https://user-images.githubusercontent.com/34398833/76162616-40d7a480-617a-11ea-8111-9700d91d34e6.png)

**Comment by JimmyVV** [comment]
把 :current 改成 v-model，change 事件可以修改为 @change 来调试下

**Comment by JimmyVV** [comment]
可以用 0.6.3 版本试用一下
