### ISSUE TITLE
如何支持capture-bind事件

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#113]
目前有使用小程序的capture-bind事件，请问如何支持？

**Comment by xxxBW** [comment]
addEventListener 这个接口是支持绑定捕获事件的。跟 web 端使用方法一样，第三个参数表示在哪个阶段。

**Comment by xmsz** [comment]
> addEventListener 这个接口是支持绑定捕获事件的。跟 web 端使用方法一样，第三个参数表示在哪个阶段。

为什么你老是天天强答？？ 有拿什么好处吗？问题是你回答我两次，两次都不对，你是想校招微信小程序？

如果可以的话，我来求支持干什么？？

每次都看不懂我的需求，我要的支持capture-bind，不是捕获 capture 事件。

**Comment by JuneAndGreen** [comment]
xxxBW 是我们这边的值班同学来着。。。她可能没有理解你的问题。

目前kbone的事件都是采用 bind 事件来处理，然后转成 kbone 自己搭建的一套事件冒泡机制。所以如果只是要捕获阶段，如 addEventListener 的方式使用即可。如果想用原始的 capture-bind，因为小程序自定义组件不支持动态修改模板，也没有动态处理事件绑定的接口，所以只能用一个比较妥协的方法，将其实现成一个原始的自定义组件，然后通过文档这个方式来使用：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6

**Comment by xmsz** [comment]
> xxxBW 是我们这边的值班同学来着。。。她可能没有理解你的问题。
> 
> 目前kbone的事件都是采用 bind 事件来处理，然后转成 kbone 自己搭建的一套事件冒泡机制。所以如果只是要捕获阶段，如 addEventListener 的方式使用即可。如果想用原始的 capture-bind，因为小程序自定义组件不支持动态修改模板，也没有动态处理事件绑定的接口，所以只能用一个比较妥协的方法，将其实现成一个原始的自定义组件，然后通过文档这个方式来使用：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6

可以，抱歉之前言语过激

然后后面的问题我使用的就是原生自定义组件方式 <wx-xxx/> ， 但因为包裹了一层，所以这个capture-bind并不会作用到原生组件上，而是原生组件的上一层。

然后我现在临时的做法是改 element 包，index.js 里添加一个
```
onCaptureTap(evt) { if (this.document && this.document.\$\$checkEvent(evt)) { this.callEvent('captureTap', evt, {button: 0}) // 默认左键 } }
```
然后在templete，所有组件都加载 capture-bind:tap的支持
```
<test capture-bind:tap='onCaptureTap' />
```

这样的就可以和 onClick 一样处理。

这个需求有点蛋疼，因为只有小程序场景才有，其他情况下是直接用 useCapture。

看能否支持，或者只有让原生组件组件其他不支持没关系。把这个属性当做原生组件的固定属性

或者看是否有其他方式，现在改源码太麻烦，一更新就要改一次

**Comment by JuneAndGreen** [comment]
@xmsz 可以说明一下具体是什么样的场景只能使用 capture-bind 而无法使用 addEventListener 的 capture 阶段么？我们来评估一下。

**Comment by xmsz** [comment]
> @xmsz 可以说明一下具体是什么样的场景只能使用 capture-bind 而无法使用 addEventListener 的 capture 阶段么？我们来评估一下。

有点尴尬，因为这个场景肯定有点蛋疼，我们可不可以只站在技术角度，然后忽略其他事情。。。

就是<ad/> 这个组件需要支持capture-bind，只能在ad的组件上绑定，父级绑定是没有用的，因为已经冒泡停止了

**Comment by xmsz** [comment]
有结果吗，如果不支持的话，我要自己fork了，但是好麻烦，还得同步更新
