### ISSUE TITLE
@vue/composition-api如何在 setup 里绑定window.addEventListener小程序生命周期

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#114]
vue2正常是在 created 生命周期，但是 @vue/composition-api 实际上把 created 算在 setup 里。
但是我在 setup 使用

```
window.addEventListener('wxload', (query) => {
  console.log(query);
});
```
是不行的，因为还没绑上就执行了

如果把监听代码放在setup 函数外，那就没问题。但是这个就很蛋疼，因为如果放在外面就会被在下一次打开的时候被替换掉

**Comment by codetest** [comment]
从生成的小程序代码来看，只要是保证在new Vue的过程中会执行的事件里面监听就可以？ 
onLoad(query){
...
        this.app = this.window.createApp()
        this.window.$$trigger('load')
        this.window.$$trigger('wxload', {event: query})
...
}

**Comment by LastHeaven** [comment]
用vue3开发，可以参考下
https://gitee.com/MRLH/kbone-vue3

**Comment by xmsz** [comment]
> 从生成的小程序代码来看，只要是保证在new Vue的过程中会执行的事件里面监听就可以？
> onLoad(query){
> ...
> this.app = this.window.createApp()
> this.window.$$trigger('load')
> this.window.$$trigger('wxload', {event: query})
> ...
> }

什么意思

**Comment by xmsz** [comment]
> 用vue3开发，可以参考下
> https://gitee.com/MRLH/kbone-vue3

参考啥... 你这个只是官方 DEMO 然后套上 vue3，而且还在用.vue（这不是重点）
重点是你这个帮不上忙

**Comment by xmsz** [comment]
> 从生成的小程序代码来看，只要是保证在new Vue的过程中会执行的事件里面监听就可以？
> onLoad(query){
> ...
> this.app = this.window.createApp()
> this.window.$$trigger('load')
> this.window.$$trigger('wxload', {event: query})
> ...
> }

你的回答启发了我，我知道我的问题是什么了 。[https://github.com/Tencent/kbone/issues/117](https://github.com/Tencent/kbone/issues/117)

这个情况是因为我并不是在页面创建vue 的时候开启监听，而是在页面调整的时候进行监听，而这个时候页面根本没有启动，肯定是监听不到的。所以是我自己的问题
