### ISSUE TITLE
如何将页面放在pages下面 直接放在src下面 问题很多 乱七八糟的

### ISSUE THREAD

**Issue by fangkyi03** [Tencent/kbone#116]

**Comment by xxxBW** [comment]
具体是有什么问题呢？

**Comment by fangkyi03** [comment]
其他项目结构都是
src -> pages -> Index -> index.js
 现在用这个以后 强制我一定要
src -> index.js 
所有的样式都密密麻麻堆一块 恶心的要死

**Comment by xxxBW** [comment]
![image](https://user-images.githubusercontent.com/12763321/76483504-217a9900-6452-11ea-85bd-68f01aff1655.png)
我这边是这样的

**Comment by JuneAndGreen** [comment]
源码目录这边不关心，你可以用任意目录结构，只要 webpack 的 entry 配置正确即可。
