### ISSUE TITLE
【讨论贴】如何在vue路由页面生命周期中监听或者获取到页面 onload

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#117]
需求：
在一个 vue 的实例中，跳转到另外一个路由页面，如何获取 onload 信息或者监听 onload？

我的解决方案有点繁琐，大家是怎么解决的？

**Comment by JuneAndGreen** [comment]
你这种情况属于页面内的单页跳转，这种实际上并没有触发小程序的页面 onload，所以我这边也不会给到。

如果你是想要监听单页路由的变化，vue-router 本身应该有相关的 hook 提供给开发者使用。如果是想要 onload 的入参，可以在第一次监听到 onload 后将其存到全局（比如 window），后面直接取出来用即可，不过 onload 的入参基本上都会解析到 location 上，理论上应该会用到的场景很少。

**Comment by xmsz** [comment]
> 你这种情况属于页面内的单页跳转，这种实际上并没有触发小程序的页面 onload，所以我这边也不会给到。
> 
> 如果你是想要监听单页路由的变化，vue-router 本身应该有相关的 hook 提供给开发者使用。如果是想要 onload 的入参，可以在第一次监听到 onload 后将其存到全局（比如 window），后面直接取出来用即可，不过 onload 的入参基本上都会解析到 location 上，理论上应该会直接用到入参的场景很少。

明白
这也是我现在用的，在vue 创建实例时，记录下来，然后后面页面要用就取。不知道其他有没有更好的方法
我现在先关闭 issue
