### ISSUE TITLE
usingComponents无法支持原生组件

### ISSUE THREAD

**Issue by fangkyi03** [Tencent/kbone#118]
比如vant的组件 用usingComponents引入以后 出来的结果是一个普通的view 导致显示异常

**Comment by JuneAndGreen** [comment]
是否按照[文档](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)所述的方式来引入外部自定义组件的？可以对比下 demo10 的用法，看看是否哪里配置有问题。

**Comment by JuneAndGreen** [comment]
@fangkyi03 这里是否仍有问题？如果按照上述描述不能解决的话，可以提供一下demo么？
