### ISSUE TITLE
小程序里面写px 无法转换成rpx

### ISSUE THREAD

**Issue by fangkyi03** [Tencent/kbone#119]

**Comment by toowell2015** [comment]
试一下postcss-pxtorpx

**Comment by xxxBW** [comment]
可以用rem
https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8-rem

**Comment by fangkyi03** [comment]
我不想用rem 我希望跟web统一标准 用vw vh rem计算太麻烦了

**Comment by JuneAndGreen** [comment]
是只考虑小程序端么？只考虑小程序端应该其实可以直接用 rpx 这个单位的。如果两端都要支持，那么目前基本两个方案：使用 rem、px 等两端都支持的单位，或者使用类似楼上提到的其他单位转 rpx 的插件等。

**Comment by Richar-Dada** [comment]
> 是只考虑小程序端么？只考虑小程序端应该其实可以直接用 rpx 这个单位的。如果两端都要支持，那么目前基本两个方案：使用 rem、px 等两端都支持的单位，或者使用类似楼上提到的其他单位转 rpx 的插件等。

小程序里面 dpr 怎么解决

**Comment by JuneAndGreen** [comment]
> 小程序里面 dpr 怎么解决

https://developers.weixin.qq.com/miniprogram/dev/api/base/system/system-info/wx.getSystemInfo.html
