### ISSUE TITLE
刷新页面以后 微信小程序那边 直接回到首页 而不是当前修改页 

### ISSUE THREAD

**Issue by fangkyi03** [Tencent/kbone#120]
现在有两个页面
1.首页
2.其他页面
我切换到其他页面以后 然后在其他页面修改代码 保存以后 自动回到了首页
我又得自己手动切换过去才可以 很麻烦

**Comment by xxxBW** [comment]
重新编译之后到首页是正常的哦

**Comment by JuneAndGreen** [comment]
你应该是想要开发者工具的编译模式切换这样的能力吧？
编译模式是记录在 project.config.json 里的，这里提供了修改 project.config.json 的方式：https://wechat-miniprogram.github.io/kbone/docs/config/#projectconfig。
然后配置大概如下：
```js
{
    projectConfig: {
        condition: {
            miniprogram: {
				current: 0,
				list: [{
					id: -1,
					name: 'xxxx',
					pathName: 'pages/detail/index', // 页面路由
					query: `type=open&targeturl=${encodeURIComponent('https://abc.com')}&search=&hash=`, // 查询参数
					scene: null,
				}]
			}
        }
    }
}
```

查询参数具体结构可参考：
![image](https://user-images.githubusercontent.com/7931744/76484271-4cfe8300-6454-11ea-8c40-ee6c48c930b1.png)
