### ISSUE TITLE
common目录过大

### ISSUE THREAD

**Issue by toowell2015** [Tencent/kbone#121]
自定义app.js入口后，common目录3M多，vendors文件2M多，我才尝试移植两个页面而已，不指定app.js入口common目录也将近1M

**Comment by JuneAndGreen** [comment]
首先确保 webpack 配置中的代码分割是正常的。

然后有两个方案：
1、对代码依赖进行分析，剪除掉在小程序端根本不会跑的代码，对于 vue 这里有个简单的说明：https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E4%BB%A3%E7%A0%81%E4%BD%93%E7%A7%AF%E7%B2%BE%E7%AE%80，react 也可以用同样的方式来做。在 web 端缩减代码体积的方式基本上应该都可以。
2、如果代码都无法剪除，可以考虑使用分包。

**Comment by toowell2015** [comment]
> 首先确保 webpack 配置中的代码分割是正常的。
> 
> 然后有两个方案：
> 1、对代码依赖进行分析，剪除掉在小程序端根本不会跑的代码，对于 vue 这里有个简单的说明：[https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E4%BB%A3%E7%A0%81%E4%BD%93%E7%A7%AF%E7%B2%BE%E7%AE%80，react](https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E4%BB%A3%E7%A0%81%E4%BD%93%E7%A7%AF%E7%B2%BE%E7%AE%80%EF%BC%8Creact) 也可以用同样的方式来做。在 web 端缩减代码体积的方式基本上应该都可以。
> 2、如果代码都无法剪除，可以考虑使用分包。

1.现有框架是mpvue，没有要缩减的代码，现有上传代码1.2M
