### ISSUE TITLE
kbone-cli 没有更新到npm上   使用npm install -g kbone-cli 无法安装

### ISSUE THREAD

**Issue by blackdevila** [Tencent/kbone#123]
kbone-cli 没有更新到npm上   使用   npm install -g kbone-cli 无法安装 
18732 error 404 'kbone-cli@latest' is not in the npm registry.

**Comment by xxxBW** [comment]
https://www.npmjs.com/package/kbone-cli
有的哦，看看网络正常的吗

**Comment by blackdevila** [comment]
网络正常  安装其它都是可以的   就安装 kbone-cli   npm 报错    报错日志里面是
18732 error 404 'kbone-cli@latest' is not in the npm registry.
使用cnpm  正常安装

**Comment by blackdevila** [comment]
> https://www.npmjs.com/package/kbone-cli
> 有的哦，看看网络正常的吗

网络正常 安装其它都是可以的 就安装 kbone-cli npm 报错 报错日志里面是
18732 error 404 'kbone-cli@latest' is not in the npm registry.
使用cnpm 正常安装

**Comment by JuneAndGreen** [comment]
并没有做 deprecated 等操作，可以看看指向的 registry 是否是正确的。

**Comment by JuneAndGreen** [comment]
@blackdevila 请问这里是否还有问题？

**Comment by JuneAndGreen** [comment]
目前无其他反馈，kbone-cli 也正常存在于 npm 的 registry 上，如还有问题可 reopen，先暂关闭。
