### ISSUE TITLE
kbone为什么不用typescript写？

### ISSUE THREAD

**Issue by codetest** [Tencent/kbone#125]

**Comment by JuneAndGreen** [comment]
原因其实很简单：核心刚开始写的时候，小程序还没有支持 ts。后面再次改造伤筋动骨比较大（你要么给所有接口进行定义，要么就各种 any，但是这样又失去意义了），所以保留了纯 js 编写，走 babel + lint 的方式，理论上来说可以解决大部分低级问题。
