### ISSUE TITLE
求支持capture-bind和catch绑定事件

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#128]
相同问题：
#113 

之前说使用capture-bind是为了实现捕获阶段的拦截，场景是可以实现捕获一些原生组件的点击事件，有些原生组件官方禁止掉了点击

而catch则是阻止事件冒泡，场景就是非常非常常见的防止弹窗穿透。因为小程序里没办法实现
preventDefault和stopPropagation。所以在h5上没问题，但是在小程序里是无效的。

而目前kbone，可以实现阻止传递事件，但是无法阻止例如页面的滚动事件

所以希望可以支持一下capture-bind和catch

**Comment by JuneAndGreen** [comment]
在你提到的场景中，应该只有个别节点能支持 capture-bind 或者 catch 就可以了？

我这边近期计划提供：`<wx-capture @touchstart="xxx"></wx-capture>` 和 `<wx-catch @touchstart="xxx"></wx-catch>`，对于这种标签会将方法绑定处理成 xxx-bind 的绑定方法，应该可以满足你的需求？

**Comment by xmsz** [comment]
> 在你提到的场景中，应该只有个别节点能支持 capture-bind 或者 catch 就可以了？
> 
> 我这边近期计划提供：`<wx-capture @touchstart="xxx"></wx-capture>` 和 `<wx-catch @touchstart="xxx"></wx-catch>`，对于这种标签会将方法绑定处理成 xxx-bind 的绑定方法，应该可以满足你的需求？

非常可以！ 什么时候上，最近项目一直在催

**Comment by JuneAndGreen** [comment]
- miniprogram-element@1.1.0
 - miniprogram-render@1.1.0

文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BA%8B%E4%BB%B6%E7%B3%BB%E7%BB%9F

demo3 中也已补充相关例子。
