### ISSUE TITLE
Uncaught SyntaxError: Identifier 'XMLHttpRequest' has already been declared

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#130]
npm构建就报错
![image](https://user-images.githubusercontent.com/5879146/77029737-82b4e600-69d7-11ea-9c44-a750dce38857.png)

**Comment by JuneAndGreen** [comment]
xml-http-request.js 只声明过一次 XMLHttpRequest 才对，我这边本地跑起来正常。你那边 miniprogram-render / miniprogram-element 分别是什么版本呢？重启一下开发者工具是否正常呢？

**Comment by xmsz** [comment]
> xml-http-request.js 只声明过一次 XMLHttpRequest 才对，我这边本地跑起来正常。你那边 miniprogram-render / miniprogram-element 分别是什么版本呢？重启一下开发者工具是否正常呢？


miniprogram-render@1.0.9
 5af57b5  zip  tar.gz
16 hours ago 
miniprogram-element@1.0.11

**Comment by xmsz** [comment]
xml-http-request.js 里 先console.log(XMLHttpRequest) 是undefined，所以正常来说没啥问题

临时解决就是xml-http-request.js  里的XMLHttpRequest 先随便改个名字

**Comment by JuneAndGreen** [comment]
怀疑和工具有关，你是什么工具版本呢？如果不是最新的升级到最新稳定版是否可以？

**Comment by xmsz** [comment]
> 怀疑和工具有关，你是什么工具版本呢？如果不是最新的升级到最新稳定版是否可以？

Nightly v1.0.2.2003112 升级到 1.02.2003172 确实可以了 
没想到是开发者工具原因

**Comment by xmsz** [comment]
尼玛3192版本有出现了？感觉不是和版本有关 好烦

**Comment by xmsz** [comment]
感觉这个需要处理一下，每次重新构建npm就会报错。各种尝试无效。只能改名字

**Comment by xmsz** [comment]
qq开发者工具也同样报错

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/77908155-8725ac80-72bd-11ea-9fcb-e18bffc9dfbd.png)

我试了最新的这个版本是正常的，无论是 npm install 还是点击 npm 构建都没问题。你可以拿一个 demo 来重新跑下试试呢？看看是不是所有项目都这样？
