### ISSUE TITLE
从从分享进入后如何跳转到其他页面？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#132]
{
 imageUrl: ""
 path: "https://test.miniprogram.com/result"
 title: "个性头像生成器"
}
![image](https://user-images.githubusercontent.com/5879146/77130879-835f8200-6a94-11ea-83d8-36be31543bb6.png)

表现是：
1. 页面进入正确
2. 但是无法跳转到其他页面

打了输出
![image](https://user-images.githubusercontent.com/5879146/77130901-9d00c980-6a94-11ea-80e6-851027b5e6c3.png)

发现是hostname不匹配，这个要才能避免发生或者解决？

**Comment by JuneAndGreen** [comment]
https://wechat-miniprogram.github.io/kbone/docs/config/#origin

这里要求所有页面必须同源，支持传域名只是为了兼容直接将 location.href 传入的情况。不同源的页面跳转可以用这个来统一处理。
