### ISSUE TITLE
Kbone 原生组件 picker内的数据不是响应式？

### ISSUE THREAD

**Issue by yangzhimin** [Tencent/kbone#133]
<wx-component behavior="picker" :value="date" mode="date" @change="onChange">{{date}}</wx-component>{{date}}

onChange(e){

this.date = e.detail.value

}

change事件触发后 wx-component 组件内的date不会变化，组件外的date会变化

**Comment by xxxBW** [comment]
测试正常哦，你是不是标签没有闭合？

**Comment by JuneAndGreen** [comment]
@yangzhimin 请问这里是否还有问题？有的话看看能否提供一个完整的能复现问题的 demo 出来？

**Comment by JuneAndGreen** [comment]
fixed：https://github.com/Tencent/kbone/commit/6aeaf8761b8cdb14cef1012657704b19262864d9
