### ISSUE TITLE
文档小错误写成bintap了

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#134]
https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6

![image](https://user-images.githubusercontent.com/5879146/77132176-73966c80-6a99-11ea-8aa9-be1783cb4cb0.png)

**Comment by JuneAndGreen** [comment]
这里没错噢，这里就是小程序的自定义组件，并不是 vue 或者 react 之类的。

**Comment by JuneAndGreen** [comment]
原来是少写了个 d，马上修改。
