### ISSUE TITLE
使用rem在iPhone上无效

### ISSUE THREAD

**Issue by garfieldull** [Tencent/kbone#135]
使用rem定义样式，在开发者工具和Android真机中都没问题，在iPhone上好像没有作用

**Comment by JuneAndGreen** [comment]
rem 使用了小程序[这个组件的 root-font-size 属性](https://developers.weixin.qq.com/miniprogram/dev/component/page-meta.html)，依赖 2.9.0 基础库，确认下你的 iPhone 上的基础库是否是这个版本以上的呢？

**Comment by garfieldull** [comment]
谢谢，确实是基础库问题
