### ISSUE TITLE
使用小程序自定义组件如何支持multipleSlots？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#136]
还有options的其他属性是否都支持？
现在只可以单个slot，没办法多个

**Comment by JuneAndGreen** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html 文档里有提到。

自定义组件的内部实现已经不在 kbone 范畴了，后续问题可以翻阅小程序相关文档，或者到微信开放社区提问：https://developers.weixin.qq.com/community/develop/mixflow

**Comment by xmsz** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html 文档里有提到。
> 
> 自定义组件的内部实现已经不在 kbone 范畴了，后续问题可以翻阅小程序相关文档，或者到微信开放社区提问：https://developers.weixin.qq.com/community/develop/mixflow

就是配置了multipleSlots，但是实际上并没有传递进去。然后没有测试其他options参数，感觉应该也没有传递进去

**Comment by JuneAndGreen** [comment]
你的 slot 是否是由外部传到你的自定义组件的呢？如果是话目前不支持，因为已经跨了框架了，kbone 本身不是走模板编译的类型，所以无法直接桥接过去使用，只有最基础的 slot。而自定义组件内部的 slot 传递是小程序自身的了，如果这块有问题的话，可以在社区提问，会有相关值班同学来跟进。

**Comment by xmsz** [comment]
> 你的 slot 是否是由外部传到你的自定义组件的呢？如果是话目前不支持，因为已经跨了框架了，kbone 本身不是走模板编译的类型，所以无法直接桥接过去使用，只有最基础的 slot。而自定义组件内部的 slot 传递是小程序自身的了，如果这块有问题的话，可以在社区提问，会有相关值班同学来跟进。

有没有其他方式支持？
需求肯定有，影响也很大。组件肯定都会有支持多个slot的场景，小程序本身又控制不slot，也搞不了scopeSlot，局限性很大。所以只能最原始的 <slot name=''/> 方式。
