### ISSUE TITLE
createIntersectionObserver选择不了？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#137]
选择不到元素，猜测是因为调用的是wx.createIntersectionObserver 而不是 this.createIntersectionObserver

**Comment by JuneAndGreen** [comment]
createIntersectionObserver 需要传入自定义组件实例，最新版本可通过 domNode._wxComponent 来拿到，然后调 wx.createInterSection 的时候传入，但是这里需要注意节点可能会因为自定义组件而隔离（即两个节点分输入两个自定义组件），所以还可以这么做：

利用 window.$$createIntersSection 接口，文档：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-createintersectionobserver

![image](https://user-images.githubusercontent.com/7931744/77246497-d2f3a880-6c62-11ea-95cb-f2c18045d3c7.png)

其中 .h5-body 就是根节点，通过 >>> 可以跨越自定义组件选择小程序组件实例。

**Comment by xmsz** [comment]
> createIntersectionObserver 需要传入自定义组件实例，最新版本可通过 domNode._wxComponent 来拿到，然后调 wx.createInterSection 的时候传入，但是这里需要注意节点可能会因为自定义组件而隔离（即两个节点分输入两个自定义组件），所以还可以这么做：
> 
> 利用 window.$$createIntersSection 接口，文档：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-createintersectionobserver
> 
> ![image](https://user-images.githubusercontent.com/7931744/77246497-d2f3a880-6c62-11ea-95cb-f2c18045d3c7.png)
> 
> 例子在 demo3 中，其中 .h5-body 就是根节点，通过 >>> 可以跨越自定义组件选择小程序组件实例。

_wxComponent这个我记得只有canvas拿的到，其他里面没有

**Comment by xmsz** [comment]
我看了一下$$createIntersectionObserver

这个有有几个想法，既然专属小程序的，希望可以和wx.createIntersectionObserver一样

第一个是支持传入components，现在的话this是箭头函数写死的，所以也绑不了this。

第二个通过.h5-body >>> 有点太「兼容补丁」

第三个 就是_wxComponent获取方式是否有其他办法，现在得改成wx-button之类，wx-view也不行

**Comment by JuneAndGreen** [comment]
miniprogram-element@1.1.1 已补充所有节点都可以拿到 _wxComponent
