### ISSUE TITLE
vue-improve-loader在解析vue的具名插槽的缩写格式时报错

### ISSUE THREAD

**Issue by wangzhengbo** [Tencent/kbone#138]
vue的具名插槽的缩写格式如下，可见Vue文档https://cn.vuejs.org/v2/guide/components-slots.html#%E4%BD%9C%E7%94%A8%E5%9F%9F%E6%8F%92%E6%A7%BD

<base-layout>
  <template #header>
    <h1>Here might be a page title</h1>
  </template>

  <p>A paragraph for the main content.</p>
  <p>And another one.</p>

  <template #footer>
    <p>Here's some contact info</p>
  </template>
</base-layout>

Error: parse error: <template #header>

**Comment by JuneAndGreen** [comment]
先前的 parser 是基于 html 的实现，现已支持属性名带 # 的情况：

* vue-improve-loader@0.3.2
