### ISSUE TITLE
怎么在小程序中显示代码块

### ISSUE THREAD

**Issue by HurricaneTBS** [Tencent/kbone#141]
我想开发一个文章页面，页面中有一部分需要将makdown中的代码块显示出来（类似于简书中的代码块），有没有专门的显示方案呢？

**Comment by xxxBW** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/rich-text.html

**Comment by JuneAndGreen** [comment]
kbone 是支持富文本设置的（innerHTML 或者 dom api），应该大部分开源 markdown 工具都可用。微信开放社区这里用的是 markdown-it，可供参考。
