### ISSUE TITLE
minniprograp-element 1.0之后,除了view这样的组件,其他内置组件还会带来性能问题吗?

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#143]

**Comment by JuneAndGreen** [comment]
如果大规模使用，仍然可能会。因为这些组件的子节点仍然会被包裹成一个自定义组件，但是如果这些组件都没有子节点的话，就不会在其子节点处创建自定义组件了，那么它可以认为和普通的 html 节点没什么区别（当然，wx-view 这些除外，因为这种节点在外层就会直接被创建一个自定义组件包裹）

使用内置组件引入的性能问题，都必须是大规模使用才会有，一般来说这种情况很少见，最可能被大规模使用的节点是 wx-view 和 wx-text，但是这两个直接用 div 和 span 替代即可。有些时候通过 wx-view 引入自定义组件还可能优化性能，因为自定义组件本身是可以优化 diff 过程的（一般来说，频繁更新的部分可以用 wx-view 包裹）。
