### ISSUE TITLE
kbone-template-kboneui 中无法显示 KCell

### ISSUE THREAD

**Issue by loafer** [Tencent/kbone#144]
在 kbone-template-kboneui 中无法显示 KCell。
[Vue warn]: Unknown custom element: <KCell> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

```
<template>
  <KView class="page form js_show">
    <KButtonArea direction="horizontal">
      <KButton type="warn">Button1</KButton>
      <KButton type="primary">Button2</KButton>
    </KButtonArea>

    <KCells>
        <KCell value="标题文字" footer="说明文字" />
    </KCells>

    <KCells>
      <KSwitch label="Switch文本" />
    </KCells>
  </KView>
</template>

<script>

export default {
  data() {
    return {}
  }
}
</script>
```

**Comment by JimmyVV** [comment]
麻烦提供一些 kbone-ui 的版本，和具体代码

**Comment by loafer** [comment]
@JimmyVV 问题解决了，kbone 版本的问题，kbone-template-kboneui 中使用的版本低的问题，我将 kbone-ui 改为 0.6.3 就可以了。请及时更新模板中的 kbone-ui 版本，这样模板工程才有意义。
