### ISSUE TITLE
demo20 真机预览提示 "无法加载插件"

### ISSUE THREAD

**Issue by ucshell** [Tencent/kbone#145]
系统：安卓
小程序基础库: 2.9.0+
现象：图标展示后会显示 “无法加载插件”提示
![image](https://user-images.githubusercontent.com/6849965/77887049-7b75be00-729c-11ea-853c-bf6e20399a58.png)

**Comment by xxxBW** [comment]
2.10.4测试是正常的，你那边版本多少呢

**Comment by JuneAndGreen** [comment]
同：https://github.com/ecomfe/echarts-for-weixin/issues/648  与 kbone 无关，需要官方处理解决。
