### ISSUE TITLE
文档有错误

### ISSUE THREAD

**Issue by HurricaneTBS** [Tencent/kbone#146]
![image](https://user-images.githubusercontent.com/46099292/77918820-fce64400-72ce-11ea-9693-6f8cbd72ecd1.png)

两个一模一样，不应该啊

**Comment by JuneAndGreen** [comment]
已fixed：https://wechat-miniprogram.github.io/kbone/docs/ui/components/kscrollview.html#%E4%BD%BF%E7%94%A8%E5%8F%82%E6%95%B0
