### ISSUE TITLE
无法获取formID？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#147]
```
            <wx-form
              onSubmit={(e) => {
                console.log(e);
              }}
              reportSubmit
            >
              <wx-button form-type="submit">获取formId</wx-button>
            </wx-form>

```

![image](https://user-images.githubusercontent.com/5879146/77979533-7c0f6280-7337-11ea-8aa8-550e3cd59cd5.png)

**Comment by xxxBW** [comment]
formId是用来发模板消息的，后面都改成订阅消息了，不建议使用

**Comment by xmsz** [comment]
> formId是用来发模板消息的，后面都改成订阅消息了，不建议使用

... 这次我耐心回答

1. 从formId角度，微信小程序是没了，但是qq和其他平台还有
2. 从设计角度，不管我在什么平台，我至少得有办法拿到detail的其他字段？

？

**Comment by xxxBW** [comment]
这里用的 <wx-form> 是小程序的内置组件，其他detail也是有的

**Comment by xmsz** [comment]
> 这里用的 是小程序的内置组件，其他detail也是有的

就是没有，所以才来。没有看源码

1. 要么是事件监听的时候丢了
2. 要么就是因为两层<wx-comp>导致里面的属性外面一层识别不到，所以实现不了

总之你自己试一下，然后赶紧修，我现在临时是用原生组件包一层

**Comment by JuneAndGreen** [comment]
是因为这里的 form 和 button 跨了自定义组件，所以获取不到 formid。你监听到的 submit 事件其实不是原生的，是 kbone 发现你点击的是带有 form-type=submit 的 button，收集了表单组件的值后再触发的，因为原生这里没有给到 submit 事件，也就没有 formid 了。如果要拿 formid，这里得看后续基础库能否到支持原生的跨自定义组件的 button submit 才行。

话说这里也是因为模板消息会下掉，也就没有跟基础库同学提需求了。为何还需要 formid 呢？

**Comment by xmsz** [comment]
> 微信小程序这里是因为 form 和 button 跨了自定义组件，所以无法关联，导致获取不到 formid。你监听到的 submit 事件其实不是原生的，是 kbone 发现你点击的是带有 form-type=submit 的 button，收集了表单组件的值后再触发的，因为原生这里没有给到 submit 事件，也就没有 formid 了。近期基础库 form 和 button 跨自定义组件关联支持后倒是可以实现。
> 
> 不过模板消息会下掉，formid 应该也用不着了，为何还需要 formid 呢？

跨组件关联这个上了吗

 因为现在团队业务都往qq走了，qq还是用formId收集（这个非常好），所以需要这个功能。
其次如果有其他情况也是关联的也会遇到这个问题。

**Comment by JuneAndGreen** [comment]
跨组件关联这个是微信这边的一个新特性，后面是可以加下。但是 qq 那边的话，如果他们没有支持跨组件关联，我们也没辙了。。。

**Comment by xmsz** [comment]
> 跨组件关联这个是微信这边的一个新特性，后面是可以加下。但是 qq 那边的话，如果他们没有支持跨组件关联，我们也没辙了。。。只能问下他们那边有没有支持的计划了。

组件关联这个一般都有，毕竟一方面是微信小程序先抢占了市场，其他都得跟进（有些做得比微信的好，但是用不了）。另一方面这个特性不是很早就有了？
所以不用担心，可以搞

**Comment by JuneAndGreen** [comment]
如果他们原本就支持了的话（不需要内置 behavior），现在无需做任何更新应该就能监听到的。另外看了下 qq 小程序的文档，还没有相关内置 behavior 的实现（而且内置 behavior 的命名方式也不太一样），所以微信这边提供的关联方式其他平台应该也没法用。

**Comment by xmsz** [comment]
> 如果他们原本就支持了的话（不需要内置 behavior），现在无需做任何更新应该就能监听到的。另外看了下 qq 小程序的文档，还没有相关内置 behavior 的实现（而且内置 behavior 的命名方式也不太一样），所以微信这边提供的关联方式其他平台应该也没法用。

关于组件的关联（https://q.qq.com/wiki/develop/miniprogram/frame/diy_components/diy_components_relation.html），behaviors（https://q.qq.com/wiki/develop/miniprogram/frame/diy_components/diy_components_behaviors.html），这两个我在微信和qq都没用到过（也不希望用的，这样就拜托不了原生）。所以没有发言权

可以尝试一下吗？其他平台的不知道，qq现在的发展阶段相当于微信2.6.5的程度。所以在2.6.5之前的都可以实现。
然后qq也做了wx字段的映射。就是直接使用wx. 调用api是没问题的。所以还是值得兼容的

**Comment by JuneAndGreen** [comment]
不是用 relations 实现的，是使用 https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/behaviors.html 里的 wx://form-field-button 来实现的，2.10.3 才支持。

我这边是可以加上，这个没问题，不过 qq 里估计还是用不了。。。

**Comment by JuneAndGreen** [comment]
wx://form-field-button 已支持，在 demo3 里补充了相关例子。不过这里要求 wx-form + wx-button 的配合才能生效。普通 form 或者普通的 button 只会收集表单数据，无法触发小程序原生 form 的 submit 事件。

**Comment by xmsz** [comment]
> 不是用 relations 实现的，是使用 https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/behaviors.html 里的 wx://form-field-button 来实现的，2.10.3 才支持。
> 
> 我这边是可以加上，这个没问题，不过 qq 里估计还是用不了。。。

2.10.3 那就不用想了，qq那边就是在2.6.5的版本。qq那边bug更多，基础库基本就固定了
