### ISSUE TITLE
input因为某些原因真机导致诡异bug会自动focus

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#148]
搞了一个下午，差点疯掉了

```
                <input/>
```

最这么简单的一段代码，在开发者工具上没问题，我点击到其他区域的时候会blur。

但是在真机上，无论什么系统，当我点击其他区域的时候，会先blur然后自己focus。期间我没有做任何控制focus的操作

尝试了各种办法，想了各种情况，结果都不是

然后，我突然想到，我点击某些区域的时候是不会触发这个问题，而这个区域的不同点，在于这个个区域是原生组件而不是。

然后各种试验以后，我发现我要这么操作才能避免出现上面的问题
```
    <wx-view><input/></wx-view>
```

没看源码，但看起来和之前不一样的地方就是，和其他组件隔离了起来。

这个还是很蛋疼的

**Comment by JuneAndGreen** [comment]
有可能是命中了同层 input 的灰度，然后这个同层 input 存在一些问题。可以尝试将 miniprogram-element/miniprogram-render 升到最新版本试试，如果还有问题，提供一下基础库版本、手机型号和 miniprogram-element/miniprogram-render 的版本？

**Comment by xmsz** [comment]
> 有可能是命中了同层 input 的灰度，然后这个同层 input 存在一些问题。可以尝试将 miniprogram-element/miniprogram-render 升到最新版本试试，如果还有问题，提供一下基础库版本、手机型号和 miniprogram-element/miniprogram-render 的版本？

应该都是最新的

		"miniprogram-render": "^1.1.3",
		"miniprogram-element": "^1.1.8",

**Comment by JuneAndGreen** [comment]
两端都有的话，那和同层无关，不过我试了下两端，还是没能复现。

包裹 <wx-view> 的最大区别就是 setData 的范围变了，因为 wx-view 会生成一个自定义组件，setData 是自定义组件维度的， 所以也可能是 blur 后有什么操作导致了 input 的 focus 属性为 true，进而 setData 过去了。

可以排查下点击其他区域时可能会执行的操作，如果一切正常，可以给下能完整复现问题的 demo 么？我这边来调试一下。

**Comment by xmsz** [comment]
> 两端都有的话，那和同层无关，不过我试了下两端，还是没能复现。
> 
> 包裹 的最大区别就是 setData 的范围变了，因为 wx-view 会生成一个自定义组件，setData 是自定义组件维度的， 所以也可能是 blur 后有什么操作导致了 input 的 focus 属性为 true，进而 setData 过去了。
> 
> 可以排查下点击其他区域时可能会执行的操作，如果一切正常，可以给下能完整复现问题的 demo 么？我这边来调试一下。

可以 有一点思路 我试一下

**Comment by xmsz** [comment]
找到大概原因且临时解决了，非常感谢

复现是
1. 用户主动在input输入文字
2. input获取focus
3. 点击其他区域
4. input状态为blur
5. **代码主动清除input的value值**
6. input自己重新获得focus
7. iOS端，小程序判断非用户主动触发（猜测），又将input状态改为blur
   Android端，保存focus状态

所以造成了我上面的情况，这个现在不知道是不是小程序的问题还是web端也会这样

临时处理
1. 定时器修改value的值，但是时间不好控制
2. 手动去管理focus属性，但是不好管理，条件变多了
3. 放弃这个需求...

**Comment by mumuxiaozhu** [comment]
请问  ios   13.4.1  使用自带输入法输入中文时有没有出现拼音还在input输入框的时候，内容会自动消失，期间也没调h5的任何事件。

**Comment by xmsz** [comment]
> 请问 ios 13.4.1 使用自带输入法输入中文时有没有出现拼音还在input输入框的时候，内容会自动消失，期间也没调h5的任何事件。

我没遇到过
