### ISSUE TITLE
与原生小程序混合使用

### ISSUE THREAD

**Issue by YikaJ** [Tencent/kbone#149]
kbone-cli 是否能有一种模式，可以将项目生成子包，可以挂载原本的原生小程序上。

**Comment by JuneAndGreen** [comment]
cli 提供的是完整项目模板，所以没有支持。不过 mp-webpack-plugin 支持只输出页面内容，相当于小程序中的部分页面可以采用 kbone 开发。然后app.json中的配置就需要自己手动补充了，而从原生小程序页面跳到 kbone 页面的话，可以参考 qa 中的说明来拼接跳转路由。

配置文档：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-app 
qa ：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91
