### ISSUE TITLE
wx-catch导致vue双向绑定失效？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#150]
![image](https://user-images.githubusercontent.com/5879146/78328999-1c24f000-75b3-11ea-9bb8-3e439cba2dd9.png)
![image](https://user-images.githubusercontent.com/5879146/78329014-28a94880-75b3-11ea-9ff1-4cc2a22e4d07.png)

从图上可以看出，没有用wx-catch的情况下，正常h5标签，或者原生组件（包括自己封装的wx-catch页没问题）下都没有问题

但是在wx-catch下，里面的状态完全失效

**Comment by JuneAndGreen** [comment]
demo3 补充了相关用例，我这边看是正常的，你试试 demo3 看看是否正常？

![image](https://user-images.githubusercontent.com/7931744/78452058-a9536c00-76bb-11ea-9e96-93b2a39bc1fe.png)
![image](https://user-images.githubusercontent.com/7931744/78452094-e0298200-76bb-11ea-8b42-5f09b5779d6b.png)

**Comment by xmsz** [comment]
这个问题我再找时间复现一下，这个不是kbone的问题，只是问一下其他人有没有遇到。
挺奇怪的，现在唯一关联的是用了wx-catch里面的状态就失效。
但是如果单独写又是没问题。换掉wx-catch也没问题，也没任何报错

**Comment by JuneAndGreen** [comment]
那我这边先 close 掉了，如果后续有复现 demo 提供，可以再 reopen。

**Comment by xmsz** [comment]
遇到一个类似表现
```
<wx-swiper>
  {props.cardList.map((card, index) => (
      <wx-swiper-item 
        class={`swiper-item ${props.current === index ? 'swiper-item-on' : ''}`}>
            {card.url}
      </wx-swiper-item>
    ))}
</wx-swiper>
```
props.current 这个是 number 类型，且是动态的。

上面的代码，会导致card没有更新

然后如果把class里关于props.current的去除，就恢复正常
