### ISSUE TITLE
wx-button求支持bindaddfriend等一系列属性

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#151]
背景：
qq的button有一些很好的属性支持，希望支持一下

https://q.qq.com/wiki/develop/miniprogram/component/form/button.html

**Comment by JuneAndGreen** [comment]
目前我们暂不会主动考虑兼容其他平台，每个平台的实现都不尽相同，带来的后续维护和更新相当困难，对于新特性的推出兼容也举步维艰。对于其他平台我们目前推荐通过 fork 的方式来进行改造使用。

**Comment by xmsz** [comment]
> 目前我们暂不会主动考虑兼容其他平台，每个平台的实现都不尽相同，带来的后续维护和更新相当困难，对于新特性的推出兼容也举步维艰（除非后续其他平台愿意参与共同建设）。目前对于其他平台我们推荐通过 fork 的方式来进行改造使用。


至少qq可以吧，大方一点。kbone可以当做是所有小程序的一种解决方案，而不是局限于微信。kbone真的非常的有意义。

另外三个理由
1. 大部分开发者确实没有时间和精力单独维护一份。之前我也想这么做，但是发现根本顾及不来。基本上每天还得检查一下源是否有更新。而且自己维护的话新的bug没人测，几乎等同于挖了更多坑。
2. 现在主流趋势都往抖音和qq小程序走，这一方面是由于流量的倾斜，他们的用户比微信的年轻，比微信的活跃，比微信的精准。广告费用也自然高，无论是对于流量主还是广告主都很好。另一方面微信小程序团队太多作死的行为，无意义一直在自残。
3. 特殊的特性不要求兼容，因为没必要，本来就要自己写兼容判断，希望兼容的是一些所有平台都有的特性或者属性。

扯远了，就是希望kbone在有精力下可以多兼容兼容其他平台。

然后关于这个问题，可否
1. template模板直接支持
2. 或者有另外一种方式，可以把额外未知的dataset传递到真实组件

**Comment by JuneAndGreen** [comment]
如果是微信上有的，后续都有可能考虑支持，因为我们这边可以从基础库层面上进行研究并考虑支持方案，但是其他平台在这方面就比较困难了，最大的问题是得很长一段时间都投入比较多的精力和时间来做完整兼容，所以就目前来说，更优先的是做好微信这边，以后有余裕再考虑其他的。

然后另外两个问题：
1、template 是指 template 递归还是指小程序的 template 模板？如果是 template 模板，像 vue/小程序的组件应该提供了类似的功能了，非要用原生的 template，目前没有很好的桥接方案（性质和 wxs 类似，各种想到的桥接方案都存在一些缺陷，所以目前还不支持），只能用引入第三方自定义组件的方式来实现了。如果是 template 递归特性，需要等后续 wxml 模板编译器的改造完成可用后，就可以考虑改造成这个方式来实现 kbone。
2、想要把dataset挂到真实组件应该是 wxss 属性选择器的需求吧？这个对于 kbone 这种采用固定模板，运行时构建组件树的方案来说，目前是无法做到的，因为小程序本身并没有支持动态增加模板不存在的属性的方法。

**Comment by xmsz** [comment]
> 如果是微信上有的，后续都有可能考虑支持，因为我们这边可以从基础库层面上进行研究并考虑支持方案，但是其他平台在这方面就比较困难了，最大的问题是得很长一段时间都投入比较多的精力和时间来做完整兼容，所以就目前来说，更优先的是做好微信这边，以后有余裕再考虑其他的。
> 
> 然后另外两个问题：
> 1、template 是指 template 递归还是指小程序的 template 模板？如果是 template 模板，像 vue/小程序的组件应该提供了类似的功能了，非要用原生的 template，目前没有很好的桥接方案（性质和 wxs 类似，各种想到的桥接方案都存在一些缺陷，所以目前还不支持），只能用引入第三方自定义组件的方式来实现了。如果是 template 递归特性，需要等后续 wxml 模板编译器的改造完成可用后，就可以考虑改造成这个方式来实现 kbone。
> 2、想要把dataset挂到真实组件应该是 wxss 属性选择器的需求吧？这个对于 kbone 这种采用固定模板，运行时构建组件树的方案来说，目前是无法做到的，因为小程序本身并没有支持动态增加原有模板里不存在的属性的方法。


1. 嗯，指的是模板递归
