### ISSUE TITLE
diff和setData过大的问题

### ISSUE THREAD

**Issue by codetest** [Tencent/kbone#152]
在对setData做调试的时候，发现kbone传递的数据实质上是虚拟节点，而且传递的数据量大。已下面的代码为例
```vue
<template>
    <div>
        <div v-for="(text, index) in msgs" v-bind:key="index" @click="click(index)">{{text}}</div>
    </div>
</template>
<script lang="ts">
    import {Vue, Component} from "vue-property-decorator"
    @Component({name: "Home"})
    export default class Home extends Vue{
        msgs: string[] = []
        click(index: number){
            this.msgs[index] = "Hello " + index.toString() + " " + new Date().toString()
            this.$forceUpdate()
        }

        created() {
            var arr: string[] = []
            for (var inx = 0; inx < 100; ++inx){
                arr.push("Hello " + inx.toString())
            }

            this.msgs = arr
        }
    }
</script>
<style lang="sass">
</style>
```
在点击某一个条目的时候，由vue的diff，到触发了dom的视图更新，触发onChildNodesUpdate调用，最终是this.setData(newData)。newData包含了整整100个子节点，而vue中通过比较，只是更新了一个节点。当然这个setData本身耗时并不长，但不知道是否有优化的空间。
![callstack](https://raw.githubusercontent.com/codetest/codetest.github.io/master/images/issue/kbone/Callstack1.png)

**Comment by JuneAndGreen** [comment]
对于需要频繁更新的部分，可以包括在 wx-view 中。wx-view 会创建一个自定义组件，然后 setData 维度从这个自定义组件开始，可以减少该部分 setData 的数据大小和基础库底层的 diff 损耗。

此方法在 qa 中有提到：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91

**Comment by codetest** [comment]
调试了一下，如果定义组件的话，就根据一系列的模板引用最终生成对应的element组件，然后就拥有自己的data和在Attached的时候注册自己的children update回调。
```javascript
this.onChildNodesUpdate = tool.throttle(this.onChildNodesUpdate.bind(this))
```
不过，最终setData都是该组件内虚拟节点的数据更新。

**Comment by JuneAndGreen** [comment]
是的，每个组件只考虑这个组件内管理的节点树。

**Comment by codetest** [comment]
通过生成式的模板定义文件index.wxml, subtree.wxml, subtree-cover.wxml, inner-compoenent.wxml循环递归定义树的节点结构，决定了data的只能是当前子树的完整虚拟节点描述。但疑惑的发ing是在于通过import的方式引入的模板，就可以运行时查找对应的组件，然后渲染？比如先定义好element组件，然后通过childnodes更新，进入到substree的时候，再去渲染需要用到的element组件，再递归直到渲染结束？这样的话如果使用错误，就会导致爆栈了。

**Comment by codetest** [comment]
element组件的自我递归调用和其他组件组合构成了页面树形结构，也决定了data的结构是对这个页面树形结构的一一对应了。我一开是读到下面的这段kbone文档的时候还意味框架本身可以做调整，原来是调用者自己调整。

细节其二：自定义组件实例的创建其实是会有比较大开销的，有没有办法减少一些自定义组件实例的创建？按照先前的构想，一个自定义组件绑定一个 Dom 节点，所以自定义组件实例数量等于 Dom 节点数量。其中一个思路是对 Dom 节点进行删减，这个实现比较简单，只要是不展示在页面上的节点，直接从 Dom 树上干掉就可以了，这样自定义组件数量也会相应减少。另一个思路是调整映射关系，让一个自定义组件绑定多个 Dom 节点。我们可以对 Dom 树按照一定规则进行裁剪，拆分成多棵子树，然后每个自定义组件管理一棵子树，这样的话也可以减少大部分自定义组件的创建。

**Comment by JuneAndGreen** [comment]
是的，如果没有其他问题的话我这边先关闭 issue 了，有其他问题可以 reopen 或者新建 issue。如果想要讨论，可以单独建立一个讨论用 issue。
