### ISSUE TITLE
npm run start没有把根目录下的sitemap.json复制到dist/mp

### ISSUE THREAD

**Issue by yunchuanyang** [Tencent/kbone#153]
![image](https://user-images.githubusercontent.com/15663474/78472130-1d981900-7769-11ea-9e92-8a736f57e4e9.png)

**Comment by JuneAndGreen** [comment]
目前没有支持 sitemap，可以使用 webpack 插件拷贝过去：https://webpack.js.org/plugins/copy-webpack-plugin/

**Comment by JuneAndGreen** [comment]
https://wechat-miniprogram.github.io/kbone/docs/config/#sitemapconfig 可配置 sitemap，也可以使用 webpack 插件拷贝过去：https://webpack.js.org/plugins/copy-webpack-plugin/
