### ISSUE TITLE
如果单个页面设置pullDownRefresh

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#155]
配置文档看到了global中设置，要如何实现单个页面设置

**Comment by JuneAndGreen** [comment]
pages 字段可以对某个页面单独配置：https://wechat-miniprogram.github.io/kbone/docs/config/#pages

**Comment by xmsz** [comment]
> pages 字段可以对某个页面单独配置：https://wechat-miniprogram.github.io/kbone/docs/config/#pages

... 好吧，是我没看到

（努力挽回颜面的回复）

1. 文档有点不好阅读，全部在一个页面里，还得全部先看一遍，然后下次又忘了
2. 搜索功能不能搜索code内，所以搜索框搜索「pullDownRefresh」只会有global结果
3. 和想象中不同，一直以为这个就是和其他page.json里的字段配置一样，单独拿出来，知道的人知道就是原因。但是不知道的没法理解为什么其他字段在extraConfig配置而这个要单独出来。
4. 不知道是否直接配置在pageConfig的做法怎么样
![image](https://user-images.githubusercontent.com/5879146/78560596-e8fb8e80-7848-11ea-93c4-b838b6b0e928.png)

**Comment by JuneAndGreen** [comment]
文档我在 global 那里再补充一下引导提示好了。这里单独拿出来其实是这里会存在和原生小程序配置不同的字段，为避免冲突，所以补了个 extraConfig（其实原先一开始设计是想完全接管小程序配置的，后来发现没必要，就变成现在这种方式）。

文档搜索原本想接 algolia 但是一直没有时间去搞。。。

**Comment by xmsz** [comment]
> 文档我在 global 那里再补充一下引导提示好了。这里单独拿出来其实是这里会存在和原生小程序配置不同的字段，为避免冲突，所以补了个 extraConfig（其实原先一开始设计是想完全接管小程序配置的，后来发现没必要，就变成现在这种方式）。
> 
> 文档搜索原本想接 algolia 但是一直没有时间去搞。。。

原来如此

辛苦了，维护和满足所有需求确实挺不容易的

**Comment by lirui9825** [comment]
> > 文档我在 global 那里再补充一下引导提示好了。这里单独拿出来其实是这里会存在和原生小程序配置不同的字段，为避免冲突，所以补了个 extraConfig（其实原先一开始设计是想完全接管小程序配置的，后来发现没必要，就变成现在这种方式）。
> > 文档搜索原本想接 algolia 但是一直没有时间去搞。。。
> 
> 原来如此
> 
> 辛苦了，维护和满足所有需求确实挺不容易的

请问我这边这个backgroundColor生效了为啥navigationBarTitleText没有生效？
```js
pages: {
        home: {
            navigationBarTitleText: '学校介绍',
            backgroundColor: 'yellow',
        },
        list: {
            navigationBarTitleText: '国际学校排名',
            backgroundColor: 'pink',
        }
    },
```
dist\mp下的config.js也构建了对应的
```js
"pages": {
		"home": {
			"rem": true,
			"share": true,
			"windowScroll": false,
			"backgroundColor": "yellow",
			"navigationBarTitleText": "学校介绍"
		},
		"list": {
			"rem": true,
			"share": true,
			"windowScroll": false,
			"backgroundColor": "pink",
			"navigationBarTitleText": "国际学校排名"
		}
}
```

**Comment by lirui9825** [comment]
> pages 字段可以对某个页面单独配置：https://wechat-miniprogram.github.io/kbone/docs/config/#pages

请问我这边这个backgroundColor生效了为啥navigationBarTitleText没有生效？
```js
pages: {
        home: {
            navigationBarTitleText: '学校介绍',
            backgroundColor: 'yellow',
        },
        list: {
            navigationBarTitleText: '国际学校排名',
            backgroundColor: 'pink',
        }
    },
```
dist\mp下的config.js也构建了对应的
```js
"pages": {
		"home": {
			"rem": true,
			"share": true,
			"windowScroll": false,
			"backgroundColor": "yellow",
			"navigationBarTitleText": "学校介绍"
		},
		"list": {
			"rem": true,
			"share": true,
			"windowScroll": false,
			"backgroundColor": "pink",
			"navigationBarTitleText": "国际学校排名"
		}
}
```

**Comment by lirui9825** [comment]
请问大佬，我这个backgroundColor生效了，为啥navigationBarTitleText没有生效？
```js
pages: {
        home: {
            navigationBarTitleText: '学校介绍',
            backgroundColor: 'yellow',
        },
        list: {
            navigationBarTitleText: '国际学校排名',
            backgroundColor: 'pink',
        }
    },
```
dist\mp下的config.js也构建了对应的
```js
"pages": {
		"home": {
			"rem": true,
			"share": true,
			"windowScroll": false,
			"backgroundColor": "yellow",
			"navigationBarTitleText": "学校介绍"
		},
		"list": {
			"rem": true,
			"share": true,
			"windowScroll": false,
			"backgroundColor": "pink",
			"navigationBarTitleText": "国际学校排名"
		}
}
```
