### ISSUE TITLE
kbone组件模板subtree嵌套

### ISSUE THREAD

**Issue by codetest** [Tencent/kbone#157]
对subtree.xml进行格式化的时候可以看到又很多层嵌套。从递归渲染的角度来说，是不是bfs排布也可以，比如简单示例。渲染wxml可能也是调用各子自组件的渲染函数，然后生成节点树。使用10层嵌套是为了解析wxml快？避免多次加载组件wxml进行解析？
```xml
 <block wx:for="{{childNodes}}" wx:key="nodeId" wx:for-item="item1">
   <image wx:if="{{item1.isImage}}"></image>
   <button wx:if="{{item1.isButton}}"  >
     <element wx:if="{{item1.hasChildren}}"></element>
 </button>
   <form wx:if="{{item1.isForm}}"  >
     <element wx:if="{{item1.hasChildren}}"></element>
 </form>
 ...
 <element wx:else></element>
</block>
```

![嵌套](https://raw.githubusercontent.com/codetest/codetest.github.io/master/images/issue/kbone/%E5%B5%8C%E5%A5%97.png)

**Comment by codetest** [comment]
因为最终是要生成html的，而不是要渲染出虚拟节点，10层相当于批处理？

**Comment by JuneAndGreen** [comment]
不是，这个层级是可配的，用来控制整个页面的自定义组件实例的数量。自定义组件本身可以优化 diff 消耗，但是其创建反而会增加耗时。目前默认是给自定义组件内配置的层级是 10 层，用于减少自定义组件数量，但是遇到需要频繁更新的部分（也就是需要频繁 diff），开发者也可以通过 wx-view 标签来强行创建一个自定义组件，来减少 diff 的范围，优化 diff 消耗。
