### ISSUE TITLE
开发者工具支持的外挂kbone不是最新

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#158]
开启miniprogram.config.js 中的 appExtraConfig.useExtendedLib.kbone选项, 可以减少大量打包耗时,但是开发者工具不提供最新的element ,render组件.  
最新的开发者工具仍不支持xhr  
![image](https://user-images.githubusercontent.com/42435611/78850633-40b51800-7a4a-11ea-944d-1efa9fca113c.png)

这个支持真的非常重要,能帮忙联系下开发者工具那边的同学吗?

**Comment by xxxBW** [comment]
手机预览是正常的么

**Comment by TomVista** [comment]
> 手机预览是正常的么

我的意思是开发者工具带的miniprogram-element miniprogram-render 版本非常低,

用到新特性,肯定不行,手机预览也不行,直接报错

**Comment by TomVista** [comment]
> 手机预览是正常的么

另外,这个和线上无关,主要是为了方便开发,,只要开发者工具支持最新的miniprogram-element miniprogram-render就行,  
你们那边,可以分别试一下,autobuildnpm:true 和appExtraConfig.useExtendedLib.kbone:true时,开发者工具的编译速度,差距非常大,  
appExtraConfig.useExtendedLib.kbone:true,能够有效提升kbone的开发效率

**Comment by xmsz** [comment]
xhr 问题和我遇到的一样 只能手动改源码

**Comment by JuneAndGreen** [comment]
工具和客户端均已更新，useExtendedLib 因为目前的更新机制问题，版本会稍稍落后于 npm 上版本，这个我们看看如何尽量让其差距不会太远。
