### ISSUE TITLE
在kbone中使用自定义组件没找到方法调用子组件里面的方法，使用的是vue的模板

### ISSUE THREAD

**Issue by YangZhiQingYZQ** [Tencent/kbone#160]
html里面使用标签：        <Cashier id="cashier" :style="{width:width}" ref="Cashier" />

无论是：
this.$refs.Cashier;  // 能访问到组件，但是查找不到组件内的方法
window.selectComponent // 找不到这个方法
this.selectComponent // 找不到这个方法
document.getElementById("Cashier"); // 返回Null

**Comment by JuneAndGreen** [comment]
现在其实是可以访问到，但是方法比较复杂，近期我提供一个更为简便的方法来获取相关实例好了。

**Comment by JuneAndGreen** [comment]
更新 mp-webpack-plugin@0.9.8，可以通过 this.$refs.Cashier._wxCustomComponent 来获取对应的组件实例，参考 demo：https://github.com/Tencent/kbone/blob/90f1e7a2085ef20ebbbd82dbbb383ea35488486e/examples/demo10/src/index/App.vue#L31
