### ISSUE TITLE
mp-webpack-plugin@v0.9.5 bug 

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#162]
重复自动安装小程序依赖.
下面这个函数缺个 hasbuildnpm = true
![image](https://user-images.githubusercontent.com/42435611/79084026-40778e00-7d64-11ea-8cf0-39f00ddab165.png)

**Comment by JuneAndGreen** [comment]
这个其实是占位的标记，暂时还未实现。我看近期能否支持一下。

**Comment by TomVista** [comment]
补充:这也是kbone小程序编译慢的原因,大家在第一次构建项目后,可以把miniprogram.config.js 中的general.buildnpm 关掉,能加快编译.

**Comment by JuneAndGreen** [comment]
mp-webpack-plugin@0.9.9 已支持 ：https://github.com/Tencent/kbone/blob/a288f8ccb69ccdd141ef3dde5d3570582ed6c255/packages/mp-webpack-plugin/src/index.js#L461
