### ISSUE TITLE
webpack cache:true 引起的bug

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#165]
引起的报错
```
VM145:1 TypeError: Cannot read property 'a' of undefined
VM1966:1 TypeError: Cannot set property 'render' of undefined
```
其他现象:
* async 函数无效. 不运行,不报错

以上错误或现象同时存在一个, async 函数无效更容易触发

复现方式: webapck cache:true时,删减 async 重新编译
```
export default{
...
async mounted () {
    console.log('index123')
  },
...
}
```

* 可以通过重新npm run mp 解决,重启开发者工具无效
* 只测试了async mounted 其他未测试

**Comment by xmsz** [comment]
很正常 这个是webpack的相关 手动重启就能解决

**Comment by TomVista** [comment]
问题不大,建议关闭cache.
