### ISSUE TITLE
demo20在微信小程序开发者工具上报错

### ISSUE THREAD

**Issue by yangangzhang** [Tencent/kbone#167]
![1587030482(1)](https://user-images.githubusercontent.com/20433039/79442040-966d5f80-800a-11ea-91ec-856d169bd89f.png)

**Comment by JuneAndGreen** [comment]
重启一下工具试试？工具的 watch 这里有个 bug，已经反馈过去，静等修复。

**Comment by yangangzhang** [comment]
> 重启一下工具试试？工具的 watch 这里有个 bug，已经反馈过去，静等修复。

工具重启了两三次，都不可以；您那可以运行？

**Comment by JuneAndGreen** [comment]
是呀，话说构建 npm 那一套工序都完成了的吧？这里依赖了小程序的[构建 npm 功能](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)，你可以选择自己构建，也可以用 autoBuildNpm 配置自动构建：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-autobuildnpm

**Comment by yangangzhang** [comment]
> 是呀，话说构建 npm 那一套工序都完成了的吧？这里依赖了小程序的[构建 npm 功能](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)，你可以选择自己构建，也可以用 autoBuildNpm 配置自动构建：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-autobuildnpm

npm那一套工序完成了

**Comment by JuneAndGreen** [comment]
如果你看到项目根目录下有 miniprogram_npm，且里面有 kbone 的核心 miniprogram-element 和 miniprogram-render，表示npm构建成功，那么应该可以跑的，如果还不行重启一次项目也应该可以的。

**Comment by yangangzhang** [comment]
> 如果你看到项目根目录下有 miniprogram_npm，且里面有 kbone 的核心 miniprogram-element 和 miniprogram-render，表示npm构建成功，那么应该可以跑的，如果还不行重启一次项目也应该可以的。

![image](https://user-images.githubusercontent.com/20433039/79546434-05a78a00-80c5-11ea-80fc-6a91e1a3c8a1.png)
服了，核心都有，重启也是不行。。。

**Comment by yangangzhang** [comment]
> 你这个目录不对，你是不是用的 cnpm？如果想用 cnpm 暗转的话，可以直接使用 npm，然后源切成 cnpm 即可。标准 npm 生成的目录应该是不会有 @版本号这样的后缀的，这样才有办法找到对应的代码。

好的，谢谢，我再试试

**Comment by yangangzhang** [comment]
> 你这个目录不对，你是不是用的 cnpm？如果想用 cnpm 安装的话，可以直接使用 npm，然后源切成 cnpm 即可。标准 npm 生成的目录应该是不会有 @版本号这样的后缀的，这样才有办法找到对应的代码。

已经没问题了，就是cnpm的问题，谢谢
