### ISSUE TITLE
KBone框架中，如何做到在web应用中有使用webpack.ensure,import()异步方式引用资源，kbone构建的时候零改动？

### ISSUE THREAD

**Issue by Toney-ZhouTao** [Tencent/kbone#168]

**Comment by JuneAndGreen** [comment]
之前有尝试过，发现基本上都是走 script 标签/eval/new Function 的形式，而这几种动态执行 js 代码的方式在小程序里都不被允许，所以目前我这边暂时没能发现可以零改动处理异步引用资源的方法。。。

**Comment by xmsz** [comment]
这一点确实之前很纠结，因为一部引用真的是web最基础也很有效的优化方式。

**Comment by Thyiad** [comment]
就是要全部改成同步吗？

**Comment by JuneAndGreen** [comment]
@Thyiad 是的，小程序自身框架限制，而且未来也没有看到有开放的可能，所以目前只能改成同步来处理了。
