### ISSUE TITLE
canvas touch事件真机报错

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#169]
开发工具正常

## 测试代码
demo3
```
<canvas v-else-if="item === 'canvas'" class="canvas" ref="canvas" type="2d" width="300" height="200" @canvastouchstart="onCanvasTouchStart">
     <Inner style="margin-top: 100px;"></Inner>
</canvas>
...
onCanvasTouchStart(){
      console.log('onCanvasTouchStart')
    }
```
## 测试信息
* 魅族16s
* 基础库2.10.4
## 报错图片
![JloaBq.png](https://s1.ax1x.com/2020/04/20/JloaBq.png)

**Comment by JuneAndGreen** [comment]
fixed: https://github.com/Tencent/kbone/commit/af18034737d567d2dfb9c8cceee98e3a73edacc6 
小程序基础库在客户端派发事件时缺少了 currentTarget 导致，后续基础库会对齐。我这边优先选用 target 字段来兼容了，可更新至 miniprogram-element@1.2.6 试试。
