### ISSUE TITLE
window.addEventListener('storage')跨页面无法监听且必须是app组件才能监听？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#170]
第一个情况：有A、B两个页面，从A到B，B的储存在storage的数据变动了，但是A页面的监听事件并没有被触发。

而在web环境中，是可以触发的。

第二个情况： window.addEventListener('storage'); 这段如果写在普通组件（非app组件）中，也无法被触发。

没看源码，第一个情况猜测就是localStorage这个适配器也是单例的
第二个情况没想到为什么

**Comment by JuneAndGreen** [comment]
已对齐 Web 端表现：https://github.com/Tencent/kbone/commit/fb21dd432aa32acee40dfe6a4cb56009d60f4295

 - miniprogram-element@1.2.7
 - miniprogram-render@1.2.6

demo: https://github.com/Tencent/kbone/blob/develop/examples/demo22/src/common/Storage.vue
