### ISSUE TITLE
不支持监听visibilitychange

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#171]
发现不支持监听visibilitychange

```
        window.addEventListener('visibilitychange', () => {
          console.log(123);
        });
```

web中成功触发，但是kbone里似乎没有做处理

使用场景
- 代替onPageShow

**Comment by JuneAndGreen** [comment]
https://github.com/Tencent/kbone/commit/e5309ad4737c75b8b793db081c46eeb65f96e0c2

已支持：
- miniprogram-element@1.2.8
- miniprogram-render@1.2.7
- mp-webpack-plugin@0.9.12

在页面的 onshow/onhide 时期会触发，unload 时期会触发 window 的 beforeunload
