### ISSUE TITLE
kbone

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#172]
引入一个路由都引入不成功，新建一个新的都成功不了，大写服了。
求大佬指点。vue 。 各种看不懂的错。

**Comment by JuneAndGreen** [comment]
可以的话，提 issue 麻烦请提供详细一点的信息：比如怎么引入，报错是什么之类的？

多页面配置可以参考：https://github.com/Tencent/kbone/tree/develop/examples/demo18
单页面的路由可以参考：https://github.com/Tencent/kbone/tree/develop/examples/demo1

**Comment by Hxmic** [comment]
好的。谢谢哈

**Comment by Hxmic** [comment]
vue 相关方面的文档有么。
![image](https://user-images.githubusercontent.com/23522154/79982667-43e3e580-84d9-11ea-870d-b9d5c6468461.png)

请问下，我是在 vue中这样引入的，但是编译后，app.json 中没有 info

**Comment by JuneAndGreen** [comment]
你新增的 info 是单页路由，是会集成在一个页面里的。多页才会打到 app.json 中。

**Comment by Hxmic** [comment]
单页路由，我按路径访问还会访问不到。

多路由得已经可以了。
