### ISSUE TITLE
wx-button的样式很烦人

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#173]
wx-button的有个灰色的背景

```
<wx-button class='a'>123</wx-button>
```

```
.button, .wx-button, button {
  background: transparent
}

.a {
  background: transparent
}
```

都没办法覆盖掉背景属性，但是在开发者工具上是覆盖的

只能写成
```
.a {
  background: transparent  !important;
}
```

太蛋疼

**Comment by JuneAndGreen** [comment]
https://github.com/Tencent/kbone/commit/e5309ad4737c75b8b793db081c46eeb65f96e0c2

已兼容：
- miniprogram-element@1.2.8

kbone 对于没有设置的属性会用默认值设置进去，而 button 组件恰巧使用 button[type=default] 这样的属性选择器来设置样式，导致标签选择器+属性选择器优先级大于 class 选择器。一般来说，你的 class 选择器也加上 [type=default] 就可以了。

不过这样写终归不太好，所以就在 kbone 兼容了一下，在上述版本你可以直接用 class 选择器来设置样式覆盖了，不需要 improtant。

**Comment by xmsz** [comment]
> [e5309ad](https://github.com/Tencent/kbone/commit/e5309ad4737c75b8b793db081c46eeb65f96e0c2)
> 
> 已兼容：
> 
> * miniprogram-element@1.2.8
> 
> kbone 对于没有设置的属性会用默认值设置进去，而 button 组件恰巧使用 button[type=default] 这样的属性选择器来设置样式，导致标签选择器+属性选择器优先级大于 class 选择器。一般来说，你的 class 选择器也加上 [type=default] 就可以了。
> 
> 不过这样写终归不太好，所以就在 kbone 兼容了一下，在上述版本你可以直接用 class 选择器来设置样式覆盖了，不需要 improtant。

原来如此 感谢
