### ISSUE TITLE
提示文件找不着

### ISSUE THREAD

**Issue by xiaohuoni** [Tencent/kbone#175]
一直提示文件找不着，但是我看相对路径是正确的，请问一下，可能会是什么问题。
![image](https://user-images.githubusercontent.com/11746742/79966780-851bcb80-84c0-11ea-9723-7fa6804956ef.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79967014-daf07380-84c0-11ea-808f-87aa5e4393c7.png)

**Comment by JuneAndGreen** [comment]
第一个截图报 "miniprogram-render/miniprogram-element" 找不到，这是 npm 模块，必须走一遍小程序自身的 npm 构建功能，执行完之后如果还报就需要重启一下工具。

css 找不到这个是不是你对 webpack 构建脚本做了一些改动？可以参考下仓库中的 demo 或者相关模板，输出文件不应该有 css 文件，应该只有 wxss 文件的。

**Comment by xiaohuoni** [comment]
好的，我们项目本身有一个很大的webpack配置，正在尝试接入kbone。有产生css，也有import，配图里面没有是调试的时候被我删了。我再尝试下。

**Comment by xiaohuoni** [comment]
有一个疑问，有没有负责一点的react尝试，比如使用了react-route的情况，能支持嘛？

**Comment by xiaohuoni** [comment]
https://github.com/Tencent/kbone/issues/130 遇到这个问题，更新到最新版本，解决。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/80064254-3460ad00-856a-11ea-96aa-022462b04236.png)
问题太多，估计是我webpack插件用了太多。我自己再实验。这个先关闭了

**Comment by JuneAndGreen** [comment]
react-router 可以用的，参考 demo16
