### ISSUE TITLE
vue-cli-plugin-kbone 不能与H5复用静态资源

### ISSUE THREAD

**Issue by Hedgehogking** [Tencent/kbone#176]
vue-cli-plugin-kbone  插件
在url-loader里面应该配置 name: '[name].[hash:hex:8].[ext]',  才能与vue-cli默认的url-loader  name统一，这样才方便小程序同步引用线上H5资源

>   name: '[name].[hash:hex:8].[ext]',

**Comment by JuneAndGreen** [comment]
感谢 pr #177 ，已发布 vue-cli-plugin-kbone@0.9.13
