### ISSUE TITLE
【讨论】有什么好的监听onAppShow的方法

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#178]
不想直接使用wx.onAppShow来监听

真实需求
- 获取当次启动时的参数

其他背景
- wxShow(onShow)无法拿到启动参数，只能是onAppShow拿
- getEnterOptionsSync 基础库要求太高，且其他平台小程序暂未支持
- getLaunchOptionsSync 是冷启动的参数，不符合要求

**Comment by JuneAndGreen** [comment]
https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss

那可以自定义 app，这样就可以监听到 app onshow 后做各种定制操作了。

**Comment by xmsz** [comment]
> https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss
> 
> 那么可以尝试自定义 app，这样就可以监听到 app onshow 后做各种定制操作了。

希望是在组件中获取监听appShow

**Comment by JuneAndGreen** [comment]
你可以在这里给所有 window 抛 appshow 事件，比如这样：

```js
getCurrentPages().forEach(page => {
    if (page.window) page.window.$$trigger('appshow')
})
```

当然，其他的一些方法都可以尝试的。不过第一次应该监听不到，因为第一次 appshow 应该在页面组件创建之前。
