### ISSUE TITLE
画布实例方法draw is not a function

### ISSUE THREAD

**Issue by zairl23** [Tencent/kbone#181]
html:
```html
<canvas type="2d" id="myCanvas"></canvas>
```

```js
...
mounted() {
 document.querySelector('#myCanvas').$$getNodesRef().then((nodesRef) => {
      // NodesRef 对象文档：https://developers.weixin.qq.com/miniprogram/dev/api/wxml/NodesRef.html
      nodesRef.node((res) => {
        const canvas = res.node
        const ctx = canvas.getContext('2d')
        console.log('ctx:', ctx)

        const dpr = wx.getSystemInfoSync().pixelRatio
        canvas.width = res.width * dpr
        canvas.height = res.height * dpr
        ctx.scale(dpr, dpr)
        
        ctx.strokeRect(10, 10, 25, 15)
        ctx.scale(2, 2)
        ctx.strokeRect(10, 10, 25, 15)
        ctx.scale(2, 2)
        ctx.strokeRect(10, 10, 25, 15)

        ctx.draw()
      }).exec()
}
````

Throw error :

VM675:1 thirdScriptError
n.draw is not a function;at SelectorQuery callback function
TypeError: n.draw is not a function
    at n.<anonymous> (http://127.0.0.1:10030/appservice/common/bookdetail.js:1:10483)
    at Function.<anonymous> (http://127.0.0.1:10030/appservice/__dev__/WAService.js:2:1246177)
    at http://127.0.0.1:10030/appservice/__dev__/WAService.js:2:127441
    at http://127.0.0.1:10030/appservice/__dev__/WAService.js:2:1246423
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:10030/appservice/__dev__/WAService.js:2:1246396

打印ctx实例，确实没有找到这个方法：

<img width="891" alt="屏幕快照 2020-04-24 下午12 02 41" src="https://user-images.githubusercontent.com/542486/80173820-8a455b80-8623-11ea-94d4-6f29c9338c28.png">

**Comment by zairl23** [comment]
调试基础库： 2.10.4
去掉如下部分代码:
```js
const dpr = wx.getSystemInfoSync().pixelRatio
        canvas.width = res.width * dpr
        canvas.height = res.height * dpr
        ctx.scale(dpr, dpr)
```

画布可以绘制出来，但依然报上述报错：

```js
document.querySelector('#myCanvas').$$getNodesRef().then((nodesRef) => {
      // NodesRef 对象文档：https://developers.weixin.qq.com/miniprogram/dev/api/wxml/NodesRef.html
      nodesRef.node((res) => {
        const canvas = res.node
        const ctx = canvas.getContext('2d')
        console.log('ctx:', ctx)

        ctx.strokeRect(10, 10, 25, 15)
        ctx.scale(2, 2)
        ctx.strokeRect(10, 10, 25, 15)
        ctx.scale(2, 2)
        ctx.strokeRect(10, 10, 25, 15)

        ctx.draw()
      }).exec()
    })
```

**Comment by JuneAndGreen** [comment]
通过 node 方法 + getContext 拿到的 context 和通过 context 方法（或者 createContext）拿到的 context 不是一个东西。前者拿到 context 几乎和 Web 端相同，不需要调 draw 方法，后者才需要。

小程序本身就提供了两种 context，目前官方是推荐前者，也就是通过 node 方法拿到的这种。

而在 kbone 上使用，有个更为方便的用法，使用 canvas 的 $$prepare 方法：https://wechat-miniprogram.github.io/kbone/docs/domextend/#canvas-prepare

 参考 demo ：https://github.com/Tencent/kbone/blob/730d3809487da98395b3092eca624d64308cad3a/examples/demo3/src/index/Component.vue#L698

**Comment by zairl23** [comment]
@JuneAndGreen 感谢您的提醒， 两种接口我都尝试了以下：对比两种方法，发现：

```js
canvas.$$prepare().then(domNode => {
      // 这里无法找到createImage方法
      domNode.createImage()
```

```js
document.querySelector('#myCanvas').$$getNodesRef().then((nodesRef) => {
      nodesRef.node((res) => {
          // 获取到canvas节点
          const node = res.node
         // 可以调用createImage
         node.createImage()
```

下面的方法能方便的在canvas上画图了。。

另外[kbone文档](https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-childnodesupdate-%E4%BA%8B%E4%BB%B6)里：

```js
document.getElementById('#canvas').$$prepare().then(domNode => {
    const ctx = domNode.getContext('2d') // 注意，这种用法需要设置 canvas 节点的 type 属性，相关文档：https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html
    // do something
})
```
其实这种方式：**document.getElementById('#canvas')**是找不到节点实例的，会抛错，而[demo](https://github.com/Tencent/kbone/blob/730d3809487da98395b3092eca624d64308cad3a/examples/demo3/src/index/Component.vue#L697)这里展示的通过ref获取节点的方式是可以获取到的。但这种方式获取到的节点实例存在上面所说的问题，即两种获取到的节点接口不是很统一。

或许我还没有找到更好的接口方法，望能再看看这个问题。

**Comment by JuneAndGreen** [comment]
document.getElementById('#canvas')  这里只是指代这里获取到的是个 dom 节点而已，你用任意方式都可以，比如你说的 ref。
