### ISSUE TITLE
map组件的markers、circles等属性不能正常作用，显示不出来

### ISSUE THREAD

**Issue by YouWillBe** [Tencent/kbone#182]
代码如下：
```javascript
import React, { useState } from 'react'

function Main() {
    console.log(window.$$global.latitude)
    console.log(window.$$global.longitude)
    const [markers, setMarkers] = useState([
        {
            id: 0,
            latitude: window.$$global.latitude,
            longitude: window.$$global.longitude,
            width: '50px',
            height: '50px',
            // zIndex: 10,
            // iconPath: './Marker1_Activated@3x.png'
            iconPath: 'https://i.loli.net/2020/04/24/kLTiDMEtgl9ySnX.png'
        }
    ])
    return (
        <wx-map
            latitude={window.$$global.latitude}
            longitude={window.$$global.longitude}
            layer-style='1'
            style={{
                width: '100vw',
                height: '100vh'
            }}
            markers={markers}
        ></wx-map>
    )
}


export default Main
```
![image](https://user-images.githubusercontent.com/16474244/80202071-a5ca5980-8657-11ea-91e1-3432851a3119.png)
经纬度是正常的，也试过用本地图标，可惜都不能正常显示，wxml里查看是空的
![image](https://user-images.githubusercontent.com/16474244/80202044-9ba85b00-8657-11ea-88c2-d6aa5e71f768.png)

**Comment by JuneAndGreen** [comment]
原因：
![image](https://user-images.githubusercontent.com/7931744/80214302-2e072980-866d-11ea-91e3-3b893cae0f27.png)

https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6

有两种方案：
1、通过 node.setAttribute 方法设进去
2、更新到 miniprogram-element@1.2.9 版本，然后使用 json 串的方式传入来曲线救国

参考 demo：https://github.com/Tencent/kbone/tree/develop/examples/demo16

**Comment by YouWillBe** [comment]
> 原因：
> ![image](https://user-images.githubusercontent.com/7931744/80214302-2e072980-866d-11ea-91e3-3b893cae0f27.png)
> 
> https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6
> 
> 有两种方案：
> 1、通过 node.setAttribute 方法设进去
> 2、更新到 miniprogram-element@1.2.9 版本，然后使用 json 串的方式传入来曲线救国
> 
> 参考 demo：https://github.com/Tencent/kbone/blob/develop/examples/demo16/src/app.jsx

ok了,多谢大佬
