### ISSUE TITLE
视频播放

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#183]
在video 标签中，获取元素后，直接掉用  play，不生效。
![image](https://user-images.githubusercontent.com/23522154/80214865-2005d880-866e-11ea-8a46-7b23c59a8586.png)

**Comment by JuneAndGreen** [comment]
方法的话，需要走 context 来调用（和小程序一样）。context 的获取是异步的，可以使用这个方法获取 context：https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getcontext

这个 context 即是小程序官方提供的 videoContext 对象：https://developers.weixin.qq.com/miniprogram/dev/api/media/video/VideoContext.html

**Comment by Hxmic** [comment]
收到。谢谢。
