### ISSUE TITLE
.$$getContext() canvas 功能，wx.canvasToTempFilePath fail 提示空画布

### ISSUE THREAD

**Issue by lanchuanglanyan** [Tencent/kbone#185]
使用.$$getContext()来使用微信的canvas功能，然后wx.canvasToTempFilePath错误反馈它提示canvasToTempFilePath: fail canvas is empty
![image](https://user-images.githubusercontent.com/31338597/80273607-42e3cb80-8706-11ea-929a-0a950d75e285.png)

**Comment by zairl23** [comment]
可参考[这篇文章](https://developers.weixin.qq.com/community/develop/article/doc/000242073903a04e082ab595b52013)

**Comment by lanchuanglanyan** [comment]
> 可参考[这篇文章](https://developers.weixin.qq.com/community/develop/article/doc/000242073903a04e082ab595b52013)

说是话是没有看懂的，想问的是这个wx.canvasToTempFilePath提示画布为空应该怎么解决
@JuneAndGreen

**Comment by lanchuanglanyan** [comment]
![image](https://user-images.githubusercontent.com/31338597/80275831-9100cb00-8716-11ea-9acf-05b31c629e28.png)
![image](https://user-images.githubusercontent.com/31338597/80275837-9d852380-8716-11ea-8ee6-db77e5fb3ca7.png)
![image](https://user-images.githubusercontent.com/31338597/80275847-aece3000-8716-11ea-8f36-d5d1c3569f7a.png)
使用.$$prepare()编写的话又没有绘制到画布上去

**Comment by zairl23** [comment]
wx.canvasToTempFilePath({
      //fileType: 'jpg',
      //canvasId: 'posterCanvas', //之前的写法
      canvas: canvasObj, //现在的写法

canvasObj得通过query接口获得传入。这个方式我今天使用了，可成功的。。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by lanchuanglanyan** [comment]
@zairl23 老哥有没有你的相应代码让我看看啊，就这一块的，我对他这个有点懵逼

**Comment by zairl23** [comment]
@lanchuanglanyan , a demo code,点击保存，应该可以看到图片
```
<template>
    <div>
        <canvas type="2d" id="myCanvas"></canvas>
        <button @click="saveImg"> 保存图片 </button>
        <img v-if="image!=''" style="margin-top: 40px; width:100px; height:100px" :src="image" />
    </div>
</template>

<script>
export default {
    data() {
        return {
            canvas: null,
            canvasCtx: null,
            image: '',
        }
    },
    mounted() {
        const self = this
        document.querySelector('#myCanvas').$$getNodesRef().then((nodesRef) => {
            nodesRef.node((res) => {
                self.canvas = res.node
                self.canvasCtx = self.canvas.getContext('2d')
                self.draw()
            }).exec()
        })
    },
    methods: {
        draw() {
            const ctx = this.canvasCtx
            ctx.strokeRect(10, 10, 25, 15)
            ctx.scale(2, 2)
            ctx.strokeRect(10, 10, 25, 15)
            ctx.scale(2, 2)
            ctx.strokeRect(10, 10, 25, 15)
        },
        saveImg() {
            const self = this
            wx.canvasToTempFilePath({
                canvas: this.canvas,
                x: 0,
                y: 0,
                width: 100,
                height: 100,
                destWidth: 100,
                destHeight: 100,
                success(res) {
                    console.log('res', res)
                    self.image = res.tempFilePath
                },
                fail(err) {
                    console.log('err', err)
                }
            })
        }
    }
}
</script>
```

**Comment by lanchuanglanyan** [comment]
可以，谢谢老哥了，能拿到了

**Comment by JuneAndGreen** [comment]
估计是新旧两种 canvas 的 context 不兼容作祟，旧 context 不太推荐使用了（getContext 拿到的那种），推荐新 context，也就是楼上大佬提供的方法（新 context 接口与 Web 端对齐）。

另外补充一下，新 context 有更为简便的获取方法：

```js
document.getElementById('#myCanvas').$$prepare().then(domNode => {
    const canvasCtx = domNode.getContext('2d') 
    // do something
})
```

**Comment by lanchuanglanyan** [comment]
好的，谢各位大佬指教
