### ISSUE TITLE
引入小程序原生组件。

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#186]
vue 中引入小程序原生组件和使用，要怎么用呢？

**Comment by zairl23** [comment]
1. 文档 ： [使用小程序内置组件](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6)

1. 代码： [example/demo3](https://github.com/Tencent/kbone/tree/develop/examples/demo3)

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/80279202-91a55b80-872e-11ea-84de-7e2542035e17.png)
这种得也支持的么？

**Comment by Hxmic** [comment]
[demo10]  (https://github.com/Tencent/kbone/tree/develop/examples/demo10/src/custom-components) 好像是的

**Comment by zairl23** [comment]
对，这种应该叫第三方的原生组件

**Comment by Hxmic** [comment]
嗯呢。我明天试下。
