### ISSUE TITLE
kbone 掉用原生小程序方法。

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#188]
例如判断用户是否授权，在kbone也要这样写嘛  ？wx.getSetting()

**Comment by JuneAndGreen** [comment]
有兴趣可以了解下 kbone 的原理，kbone 本身只是一个适配器，本质上用户代码还是让其跑在小程序里的，所以小程序里的接口其实还是可以直接用的。下面推荐两种方案：

1、如果不需要构建到 Web 端，所有 wx 接口基本都可以直接使用（部分接口可以用 kbone 提供的扩展方法更为简洁方便：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-%E5%AF%B9%E8%B1%A1）。如果要构建到 Web 端，直接使用 wx 方法需要加个环境判断，避免在 Web 端使用报错。
2、另外如果是需要构建到 Web 端的，部分接口也可以考虑使用 [kbone-api](https://github.com/wechat-miniprogram/kbone-api)，兼容了部分 Web 接口和 wx 接口，不需要自己做环境判断。
