### ISSUE TITLE
Entrypoint mini-css-extract-plugin = *   打印信息。

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#189]
![image](https://user-images.githubusercontent.com/23522154/80303828-400bd800-87e5-11ea-90b6-2720214f366c.png)

每次写过less之后，总会打印一些信息，大佬有没有什么办法解决。

**Comment by JuneAndGreen** [comment]
这个输出为什么要处理呢？

**Comment by JuneAndGreen** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/138
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/271

**Comment by Hxmic** [comment]
收到
