### ISSUE TITLE
kbone框架开发的小程序怎么使用webview组件

### ISSUE THREAD

**Issue by YuemT** [Tencent/kbone#190]
kbone框架开发的小程序怎么使用webview组件？？ 需要怎么配置，是否支持webview组件

**Comment by JuneAndGreen** [comment]
文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6

demo：https://github.com/Tencent/kbone/tree/develop/examples/demo3
