### ISSUE TITLE
react引用wx-picker属性传递异常?

### ISSUE THREAD

**Issue by YouWillBe** [Tencent/kbone#191]
表现非常奇怪,弄成json串之后第一次选择没问题,再选就什么都不显示了,也试了setAttribute的方法,一样的不好使
```javascript
import React, { useState, useEffect, useRef } from 'react'

const list = ['aaa', 'bbb', 'ccc']

function User() {
    const pickerRef = useRef()
    const [current, setCurrent] = useState(0)
    const handleChange = e => {
        console.log(e)
        setCurrent(parseInt(e.detail.value))
    }
    useEffect(() => {
        pickerRef.current.addEventListener('change', handleChange)
        // pickerRef.current.setAttribute('range', JSON.stringify(list))
    }, [])
    return ( 
        <wx-picker
                ref={pickerRef}
                range={list}
                // range={JSON.stringify(list) }
                value={current}
                onChange={handleChange}
            >
                <div>{list[current].text}</div>
            </wx-picker>
    )
}

export default User
```

**Comment by JuneAndGreen** [comment]
https://github.com/Tencent/kbone/commit/b7b59c46b7dbb93ac7085e4ee009c4ab3b71ab6a

试了下，是可以重复设置 range 的，确认下你的 effect 确定触发了么？如果确实调用了 setAttribute 的花，能否给个更为完整可运行的 demo 呢？

**Comment by YouWillBe** [comment]
> [b7b59c4](https://github.com/Tencent/kbone/commit/b7b59c46b7dbb93ac7085e4ee009c4ab3b71ab6a)
> 
> 试了下，是可以重复设置 range 的，确认下你的 effect 确定触发了么？如果确实调用了 setAttribute 的花，能否给个更为完整可运行的 demo 呢？

这个已经不缺东西了啊,直接在kbone-react-template里引这个组件进去不就好了...
effect触发了啊,第一次的change事件都捕获到了,可以看到console里的日志的

**Comment by JuneAndGreen** [comment]
kbone-react-template 只是一个基本模板而已，所以某种程度上还是得保证简洁，各种场景的问题就放到 demo 里供参考了。

回到原本的问题，你上面贴的代码没有改变 list 的地方，可以照着 demo 看看是否又正常将 list 设置进 dom 节点上去？如果有却没有更新，请给下完整可运行的 demo，我这边定位一下问题。

**Comment by YouWillBe** [comment]
> kbone-react-template 只是一个基本模板而已，所以某种程度上还是得保证简洁，各种场景的问题就放到 demo 里供参考了。
> 
> 回到原本的问题，你上面贴的代码没有改变 list 的地方，可以照着 demo 看看是否又正常将 list 设置进 dom 节点上去？如果有却没有更新，请给下完整可运行的 demo，我这边定位一下问题。

根本就没改list...就是点击进行选择,然后再点击重新选择,就不ok了

**Comment by JuneAndGreen** [comment]
问题已知悉，是 `<div>{list[current].text}</div>` 没有更新是吧，先前以为是 list 被 update 了，但是 picker 列表没有更新。

此问题是子节点更新判断有误导致，已于 miniprogram-element@1.2.12 中修复，可以更新到此版本试试。

**Comment by honorsuper** [comment]
使用wx-picker组件的时候，有用过range-key属性吗

**Comment by YouWillBe** [comment]
> 使用wx-picker组件的时候，有用过range-key属性吗

不用一年多了
