### ISSUE TITLE
关于web端和小程序端的http请求的相关demo有吗？想看看官方推荐的处理方式

### ISSUE THREAD

**Issue by maria028** [Tencent/kbone#195]

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/80452980-fdb7d780-8959-11ea-941b-648bc70487aa.png)

普通请求已经提供了 XMLHttpRequest 对象，也就说基于此对象封装的库，如 axios 也可以直接用。上传的话目前还是要判断环境区分对待。

或者也可以考虑尝试下 kbone-api：https://github.com/wechat-miniprogram/kbone-api

上述两种方式选其一即可。
