### ISSUE TITLE
如何设置 appConfig

### ISSUE THREAD

**Issue by baranwang** [Tencent/kbone#198]
看的生成的 app.js 文件中会执行 appConfig 内的方法，请问如何才能设置 appConfig 呢？

**Comment by JuneAndGreen** [comment]
此变量用于自定义 app.js 的内部实现，使用时无需理解此变量。参考文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss

如果对内部实现有兴趣，也可以阅读源码了解 appConfig/appOptions 这个变量是怎么来的。
