### ISSUE TITLE
使用 vue-cli 如何自定义 app.js

### ISSUE THREAD

**Issue by baranwang** [Tencent/kbone#199]
如果放在 vue.config.js 的 page 里，在网页模式会无法编译

**Comment by JuneAndGreen** [comment]
放到 vue.config.js 里，网页模式和非网页模式应该可以通过环境变量来区分的：
![image](https://user-images.githubusercontent.com/7931744/80686286-17445500-8afb-11ea-8f32-1a96518874ba.png)

所以尝试用这个来判断一下，不同模式返回不同的 vue.config.js 内容？

**Comment by JuneAndGreen** [comment]
插件里的实现也是通过此判断来的：https://github.com/Tencent/kbone/blob/develop/packages/vue-cli-plugin-kbone/src/index.js#L2

**Comment by baranwang** [comment]
thx @JuneAndGreen
