### ISSUE TITLE
多页面 web 模式如何编译呢？

### ISSUE THREAD

**Issue by baranwang** [Tencent/kbone#200]
和小程序一样增加了 `entry` 但是好像并没什么用哎～

**Comment by JuneAndGreen** [comment]
Web 端编译严格来说 kbone 已经不参与了，你想怎么编都行其实（kbone 只参与编译到小程序那块，也就是 mp-webpack-plugin 插件负责的功能）。不过这里也可以参考下 webpack 的文档：https://webpack.js.org/concepts/entry-points/#multi-page-application
