### ISSUE TITLE
Vue import路径中的 “@” 简写无法被识别

### ISSUE THREAD

**Issue by Meowzz95** [Tencent/kbone#202]
根据Vue的文档 "@" -> "src" 目录，但是kbone的build无法识别这个shortcut 报错如下

```
Module not found: Error: Can't resolve '@/components/HelloWorld.vue' 
```

**Comment by JuneAndGreen** [comment]
这是 webpack 构建支持的功能，不是 kbone 处理的。请参考 webpack 文档配置 resolve：https://webpack.js.org/configuration/resolve/#resolvealias
