### ISSUE TITLE
ts 下如何解决掉用微信自带得方法。

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#203]
![image](https://user-images.githubusercontent.com/23522154/81136995-b9e35480-8f8f-11ea-955e-f08569876b70.png)

ts下 会提示  找不到 wx

**Comment by JuneAndGreen** [comment]
可以使用这个：https://github.com/wechat-miniprogram/api-typings 

这里有小程序基础库的类型定义文件，如果有什么问题也可以直接在该仓库上提 issue，让相关负责人提供支持。
