### ISSUE TITLE
kbone 的扩展 API 如何在 web 端挂载？

### ISSUE THREAD

**Issue by baranwang** [Tencent/kbone#204]
如何在 web 端上使用 `$$publish` `$$subscribe` 这类方法呢？

**Comment by JuneAndGreen** [comment]
kbone 本身不侵入到原始的 Web 端应用中，这些是针对或者利用小程序的特殊情况设计的（大部分是因为小程序端无法对齐 Web 端的特性而提供的），在 Web 端不一定可行。如果是小程序提供的 sdk，倒可以使用 [kbone-api](https://github.com/wechat-miniprogram/kbone-api)。

kbone 虽然是一个适配器，但因为平台限制也做不到完全对齐，部分逻辑仍然需要环境判断分开实现。至于Web 端跨页面通信之类的业内应该已经有过不少方案了，比如利用 storage 事件等（这个事件其实 kbone 也实现了），可以直接用。
