### ISSUE TITLE
自定义 app.js 中无法使用拓展 API 吗？

### ISSUE THREAD

**Issue by baranwang** [Tencent/kbone#205]
```ts
import { login } from './utils/core'

App({
  onLaunch() {
    login().then(({ bindPhone }) => {
      window.$$publish('userLogin', bindPhone)
    })
  }
})
```
报 `Unhandled promise rejection TypeError: window.$$publish is not a function`

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/81252974-f1b6ce80-9059-11ea-84d5-e25cf2fca0b9.png)

文档里有写的其实，app 本身不属于任何页面。另外 launch 阶段各个页面还没创建，没法拿到页面实例的 window 对象的。不过像第二次之后的 show 或者 hide 事件等（此时页面已经创建渲染），可以通过小程序官方提供的 getCurrentPages 拿到 page 实例，然后通过 page.window/page.document 就能拿到对应页面的 window/document 对象了。
