### ISSUE TITLE
相同的写法ts 不生效。（不知道是不是我写错了。麻烦看看）

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#206]
```
<template>
    <view class="topbar">
        <!-- 占位栏 -->
        <cover-view
            class="placeholder-bar"
            :style="`height: ${navBarHeight}px`"
        >
        </cover-view>
        <!-- 导航栏主体 -->
        <cover-view
            class="navbar"
            :style="`height: ${navBarHeight}px; background-color: #FFF`"
        >
            <!-- 状态栏 -->
            <cover-view
                class="nav-statusbar"
                :style="`height: ${statusHeight}px;`"
            ></cover-view>

            <!-- 标题栏 -->
            <cover-view class="nav-titlebar" :style="`height: ${navHeight}`">
                <!-- home及后退键 -->
                <div class="bar-out">
                    <cover-view class="bar-options">
                        <cover-view class="back">
                            <img
                                class="back-image"
                                src="https://746c-tllb-applet-ea6du-1302049701.tcb.qcloud.la/img/back.png?sign=fc8cc0bdd821d5745c548934ff738102&t=1588757783"
                                alt=""
                            />
                        </cover-view>

                        <div class="line"></div>

                        <cover-view class="home">
                            <img
                                class="home-image"
                                src="https://746c-tllb-applet-ea6du-1302049701.tcb.qcloud.la/img/home.png?sign=aba90a6cb19cb32d3507461cffa065ad&t=1588757665"
                                alt=""
                            />
                        </cover-view>
                    </cover-view>
                </div>

                <!-- 标题 -->
                <cover-view class="bar-title">我是标题</cover-view>

                <div></div>
            </cover-view>
        </cover-view>
    </view>
</template>
```

ts 代码

![image](https://user-images.githubusercontent.com/23522154/81176275-862c1d00-8fd7-11ea-99b5-c1b75468dedc.png)

js 代码

![image](https://user-images.githubusercontent.com/23522154/81176310-93490c00-8fd7-11ea-8c9b-84cc023246b7.png)

less 代码
```
<style lang="less">
.topbar {
    margin-left: 7px;
}
.navbar {
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    z-index: 99999;
}
.placeholder-bar {
    background-color: transparent;
    width: 100%;
}
 .nav-titlebar {
    display: flex;
    align-items: center;
    position: relative;
    .bar-title {
        font-size: 16px;
        height: 48px;
        line-height: 48px;

        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        text-align: center;
    }
}

.bar-out {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: 7px;
    height: 48px;
    display: flex;
    align-items: center;
}

.bar-options {
    display: flex;
    align-items: center;
    border: 1px solid rgba(151, 151, 151, 0.2);
    border-radius: 25px;
    padding: 0 15px;
    height: 32px;

    .line {
        width: 1px;
        height: 19px;
        background: rgba(0, 0, 0, 0.2);
        margin-right: 15px;
    }
    .back-image {
        width: 12px;
        height: 10px;
        margin-right: 15px;
    }

    .home-image {
        width: 14px;
        height: 13px;
    }
}
</style>
```

js 效果图。
![image](https://user-images.githubusercontent.com/23522154/81175841-cccd4780-8fd6-11ea-8b49-57c20f3c2e8a.png)

ts效果图

![image](https://user-images.githubusercontent.com/23522154/81175883-de165400-8fd6-11ea-95d3-1db90c592d0b.png)

**Comment by Hxmic** [comment]
<template>
    <view class="topbar">
        
        <cover-view
            class="placeholder-bar"
            :style="`height: ${navBarHeight}px`"
        >
        </cover-view>
        
        <cover-view
            class="navbar"
            :style="`height: ${navBarHeight}px; background-color: #FFF`"
        >
            
            <cover-view
                class="nav-statusbar"
                :style="`height: ${statusHeight}px;`"
            ></cover-view>

            
            <cover-view class="nav-titlebar" :style="`height: ${navHeight}`">
                
                <div class="bar-out">
                    <cover-view class="bar-options">
                        <cover-view class="back">
                            <img
                                class="back-image"
                                src="https://746c-tllb-applet-ea6du-1302049701.tcb.qcloud.la/img/back.png?sign=fc8cc0bdd821d5745c548934ff738102&t=1588757783"
                                alt=""
                            />
                        </cover-view>

                        <div class="line"></div>

                        <cover-view class="home">
                            <img
                                class="home-image"
                                src="https://746c-tllb-applet-ea6du-1302049701.tcb.qcloud.la/img/home.png?sign=aba90a6cb19cb32d3507461cffa065ad&t=1588757665"
                                alt=""
                            />
                        </cover-view>
                    </cover-view>
                </div>

                
                <cover-view class="bar-title">我是标题</cover-view>

                <div></div>
            </cover-view>
        </cover-view>
    </view>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
export default class New extends Vue {
    navBarHeight = 0; // 导航栏高度
    statusHeight = 0; // 状态栏高度
    navHeight = 0; // 导航栏高度

    created() {
        var self: any = this;
        wx.getSystemInfo({
            success(res) {
                var isIos = res.system.indexOf('ios') > -1;
                self.statusHeight = res.statusBarHeight;
                self.navHeight = isIos ? 44 : 48;

                self.navBarHeight = self.navHeight + self.statusHeight;
            }
        });
    }
}
</script>

<script>
export default {
    data() {
        return {
            navBarHeight: 0, // 导航栏高度
            statusHeight: 0, // 状态栏高度
            navHeight: 0 // 导航栏高度
        };
    },

    created() {
        var self = this;
        wx.getSystemInfo({
            success(res) {
                var isIos = res.system.indexOf('ios') > -1;
                self.statusHeight = res.statusBarHeight;
                self.navHeight = isIos ? 44 : 48;

                self.navBarHeight = self.navHeight + self.statusHeight;
            }
        });
    }
};
</script>

<style lang="less">
.topbar {
    margin-left: 7px;
}
.navbar {
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    z-index: 99999;
}
.placeholder-bar {
    background-color: transparent;
    width: 100%;
}

.nav-titlebar {
    display: flex;
    align-items: center;
    position: relative;
    .bar-title {
        font-size: 16px;
        height: 48px;
        line-height: 48px;

        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        text-align: center;
    }
}

.bar-out {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: 7px;
    height: 48px;
    display: flex;
    align-items: center;
}

.bar-options {
    display: flex;
    align-items: center;
    border: 1px solid rgba(151, 151, 151, 0.2);
    border-radius: 25px;
    padding: 0 15px;
    height: 32px;

    .line {
        width: 1px;
        height: 19px;
        background: rgba(0, 0, 0, 0.2);
        margin-right: 15px;
    }
    .back-image {
        width: 12px;
        height: 10px;
        margin-right: 15px;
    }

    .home-image {
        width: 14px;
        height: 13px;
    }
}
</style>


**直接复制上面代码可以直接看，用markdown``  的没有生效。。**

**Comment by Hxmic** [comment]
还有一个问题   

我按下面这样写less 不生效。
```
<style lang="less" scope>
</style>
```

**Comment by JuneAndGreen** [comment]
1、你可以打一下日志看看你的数据有没有确实设置到 data 里？
2、scoped 不支持，文档 qa 里有说明：

![image](https://user-images.githubusercontent.com/7931744/81253294-d0a2ad80-905a-11ea-8583-6b02979dfd18.png)

**Comment by JuneAndGreen** [comment]
第一个不更新问题可能是这个被我修掉的 bug 引起的：
![image](https://user-images.githubusercontent.com/7931744/83723303-0f834d80-a671-11ea-85be-7cd178957310.png)

尝试更新 element 和 render 到最新版本试试呢？
