### ISSUE TITLE
小程序 引入 webrtc 直播，有没有好的方案给 推荐下。教育直播（带白板的）。感谢

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#211]

**Comment by JuneAndGreen** [comment]
这个没办法。。因为小程序本身就不支持 webrtc，所以 kbone 也就无法适配，毕竟 kbone 本身也是依赖小程序已有的那些能力来搞的。

**Comment by Hxmic** [comment]
哪就是不可以做，直播相关的了嘛？ 我看有第三方实现直播的。 不要急着关呀。

**Comment by JuneAndGreen** [comment]
直播相关的有啊：https://developers.weixin.qq.com/miniprogram/dev/component/live-player.html

小程序自身有提供 live-player 和 live-push 内置组件，这个不是 kbone 能提供的能力，相关能力和问题可以在微信开放社区里提问咨询：https://developers.weixin.qq.com/community/develop/mixflow。这里主要处理 kbone 自身的问题，以便管理。

如果你是商户，也可以看看这个：https://developers.weixin.qq.com/community/minihome/doc/000a06014745f00d95f9e03d951401?blockType=99，这个直播插件也有个社区小主页可以咨询的：https://developers.weixin.qq.com/community/minihome/mixflow/1216387783892418561。

**Comment by Hxmic** [comment]
这个已经在看了。
