### ISSUE TITLE
支持禁用canvas绑定事件

### ISSUE THREAD

**Issue by lyhper** [Tencent/kbone#212]
当前canvas默认会绑上事件，导致在canvas上滑动时无法滚动页面

**Comment by JuneAndGreen** [comment]
刚用 demo3 尝试了一下，滑动 canvas 是可以触发页面滑动的。能否给下你那边的问题 demo 呢？我看看是什么写法会导致滚动失效。

**Comment by JuneAndGreen** [comment]
其实这里canvas绑定了事件也应该能滚动页面的，但是 iOS 这边应该有个 bug，导致滚动不了，安卓端和开发者工具则正常，这个需要等基础库和客户端那边修复。

另外禁用 canvas 绑定事件的开关，更新至以下版本后，可以使用 :disable-event="true" 这个属性。

- miniprogram-element@1.2.17

**Comment by lyhper** [comment]
> 其实这里canvas绑定了事件也应该能滚动页面的，但是 iOS 这边应该有个 bug，导致滚动不了，安卓端和开发者工具则正常，这个是小程序那边的已知 bug，需要基础库和客户端那边修复。
> 
> 另外禁用 canvas 绑定事件的开关，更新至以下版本后，可以使用 :disable-event="true" 这个属性。
> 
> * miniprogram-element@1.2.17

目前看原生的小程序ios端禁用掉事件滚动正常，不禁用滚动有点问题，但体验比kbone会好很多，kbone完全滚动不了，原生小程序偶现滚动不了
