### ISSUE TITLE
第三方库打包出来直接被注释掉了

### ISSUE THREAD

**Issue by Thyiad** [Tencent/kbone#213]
如题，发现打包出来后，引入第三方库的代码直接被注释掉了，为啥？
![image](https://user-images.githubusercontent.com/3324812/81649168-793d7c80-9462-11ea-8fa3-7bc9e0318146.png)

**Comment by JuneAndGreen** [comment]
kbone 插件和 webpack 不会去做代码注释才对，你这边确保构建前用的代码是未注释的版本么？同时可以确认下有没有用什么特殊脚本/插件去做这种操作呢？

**Comment by Thyiad** [comment]
嗯，原始代码应该是这一块
![image](https://user-images.githubusercontent.com/3324812/81656887-00422300-946a-11ea-8e4a-c6d6fdf334b8.png)

**Comment by Thyiad** [comment]
我用官方的react脚手架尝试加入第三方库，发现第三方库是在的。。
用这个已存在的项目，就会这样，不知道什么情况。。

**Comment by Thyiad** [comment]
呃，貌似找到原因了，我再看下，可能是这个as any的原因。。

**Comment by Thyiad** [comment]
@JuneAndGreen 请问这个createApp为空，可能是什么原因呢？
![image](https://user-images.githubusercontent.com/3324812/81665125-e78a3b00-9472-11ea-9bc0-c33192a32dea.png)

**Comment by JuneAndGreen** [comment]
入口文件需要暴露出一个 createApp 接口，如 demo16：https://github.com/Tencent/kbone/blob/develop/examples/demo16/src/main.mp.jsx#L5 这里，然后构建配置这里的 output 是固定的，如：https://github.com/Tencent/kbone/blob/develop/examples/demo16/build/webpack.mp.config.js#L15，看看这里是否正常？

**Comment by Thyiad** [comment]
@JuneAndGreen 谢谢，的确是createApp函数问题。
上面那个as any，就不会被webpack处理，注释是我误解了。
多谢
