### ISSUE TITLE
如何监听页面元素滚动？

### ISSUE THREAD

**Issue by alex1504** [Tencent/kbone#214]
kbone如何更好的做无埋点上报？这边想要实现一个无埋点sdk，click已实现，expose在web和小程序分别使用相应的intersectionObserverAPI，但发现最终生成的是shadowDom无法找到相应class对应的节点。

```js
const observer = wx.createIntersectionObserver().relativeToViewport({
    bottom: 100
})
observer.observe('.order-item', (changes) => {
    console.log(changes)
})
```

于是想在小程序中通过监听页面scroll来判断元素曝光进行上报，但发现下面两种写法都无法监听成功。
```js
created() {
    window.addEventListener('wxpagescroll', () => {
      console.log('scroll')
    })
}
```

```js
window.addEventListener('scroll', () => {
      console.log('scroll')
})
```

**Comment by JuneAndGreen** [comment]
intersectionObserver 可以参考此 demo：[https://github.com/Tencent/kbone/blob/develop/examples/demo3/src/index/Component.vue#L731](https://github.com/Tencent/kbone/blob/develop/examples/demo3/src/index/Component.vue#L731)

然后如果你想监听页面 scroll，参考文档：[https://wechat-miniprogram.github.io/kbone/docs/config/#global-windowscroll](https://wechat-miniprogram.github.io/kbone/docs/config/#global-windowscroll)，配置完后就可以用 window.addEventListener('scroll', evt => {}) 来监听了。

**Comment by janfzhao** [comment]
> 然后如果你想监听页面 scroll，参考文档：https://wechat-miniprogram.github.io/kbone/docs/config/#global-windowscroll，配置完后就可以用 `window.addEventListener('scroll', evt => {})` 来监听了。

这个还需配置后，不行哇

**Comment by JuneAndGreen** [comment]
> 这个还需配置后，不行哇

因为 window scroll 事件的触发是非常频繁的，但是不是任何场景用户都需要 window scrolll，配置化是为了减少不必要的 window scroll 事件触发。
