### ISSUE TITLE
css变量

### ISSUE THREAD

**Issue by Thyiad** [Tencent/kbone#215]
请问会支持css变量吗？

**Comment by JuneAndGreen** [comment]
原生的话，取决于 wxss 能否支持。

不过使用 less、sass 也可以的吧。

**Comment by Thyiad** [comment]
嗯，原生不支持的。
跟less、sass没关系了，是css变量，类似这种：
元素节点上定义变量，然后css中这样写：
color: var(--theme-color);

https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_custom_properties

**Comment by JuneAndGreen** [comment]
我知道，但是 kbone 只是一个适配器，底层 wxss 不支持，那么 kbone 这里也无能为力的。
