### ISSUE TITLE
很小几率下会出现cannot read property $$cookie of null

### ISSUE THREAD

**Issue by yimiZSK** [Tencent/kbone#217]
很小几率下会出现cannot read property $$cookie of null。如图
![WechatIMG6238](https://user-images.githubusercontent.com/24860389/82007864-e25d0400-969d-11ea-8aa4-71c0e5909b05.jpeg)
没有直接调用$$cookie。看样子应该是xml-http-request.js中，赋值cookie的时候，可能doument不存在。
<img width="1001" alt="WeChat70e5450c3d5f0484a42444cd167ea076" src="https://user-images.githubusercontent.com/24860389/82008053-4b447c00-969e-11ea-8fd8-1a58bf5b8db5.png">

**Comment by JuneAndGreen** [comment]
目测这里可能是在页面 unload 之后才调用进来的，所以此时 document 已经被销毁，那就是 null 了。可以给下这里大致的异步请求调用逻辑么？

**Comment by yimiZSK** [comment]
@JuneAndGreen 就是普通的在mounted的时候调用了获取详情的接口。目前这种情况基本没有，很难还原。很感谢回答
