### ISSUE TITLE
路由错误

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#218]
```
// miniprograp.config.js
entry: '/map',
router: {
    index: [
      '/'
    ],
    map: ['/map']
  },
```

```
// webpack.mp.config.js

index: path.resolve(__dirname, '../src/main.js'),
    map: path.resolve(__dirname, '../src/main.js') // 为了方便直接用现成的页面做的测试
```

这种情况下 $router.push('/map')进入的页面是 /page/index/index 下的router.path === '/map' ,而不是/page/map/index

## 另外,这种配置依赖收集会乱掉
```
index: path.resolve(__dirname, '../src/main.js'),
    map: path.resolve(__dirname, '../src/main.js') // 为了方便直接用现成的页面做的测试
```

**Comment by JuneAndGreen** [comment]
$router.push 是单页跳转，不是多页跳转。但是你这里配置的 index 和 map 是两个页面。

你改成用 location.href = '/map' 试试。

**Comment by TomVista** [comment]
明白了 

## “配置依赖收集会乱掉”

会有两个vue,其他依赖没仔细看,

```
index: path.resolve(__dirname, '../src/index.main.js'),
 map: path.resolve(__dirname, '../src/map.main.js') // 这个页需要vue的时候会去找index下面的vue,多页依赖只有一份
```

```
index: path.resolve(__dirname, '../src/index.main.js'), //index页有自己的vue
map: path.resolve(__dirname, '../src/index.main.js') // map页有自己的vue
```

**Comment by JuneAndGreen** [comment]
多页的话，每个页面的公共代码会打成一份，但是 Vue 定义是隔离的。这里的设计和浏览器的多页设计类似，不同页面的环境/runtime 做了隔离，所以 index 的 vue runtime 和 map 的 vue runtime 是不同的。

如果有数据需要跨页共用，可以参考这个：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%B7%A8%E9%A1%B5%E9%9D%A2%E9%80%9A%E4%BF%A1%E5%92%8C%E8%B7%A8%E9%A1%B5%E9%9D%A2%E6%95%B0%E6%8D%AE%E5%85%B1%E4%BA%AB

**Comment by TomVista** [comment]
```
index: path.resolve(__dirname, 看这里 '../src/index.main.js')
map: path.resolve(__dirname, 看这里 '../src/index.main.js')
```
vue的代码会有两份,
我知道这个操作很骚气 🐶

**Comment by JuneAndGreen** [comment]
这么神奇的么。。。webpack 这里的配置是否有改动呢？

![image](https://user-images.githubusercontent.com/7931744/82428990-d74f0d00-9abd-11ea-8481-06c3fc6249aa.png)

**Comment by TomVista** [comment]
没有改动,直接拉下来kbone vue 模板,添个页面,代码lx2

**Comment by TomVista** [comment]
```
entry: {
    // js 入口
    home: path.resolve(__dirname, '../src/mp/home/main.mp.js'),
    other: path.resolve(__dirname, '../src/mp/other/main.mp.js'),
    home1: path.resolve(__dirname, '../src/mp/home/main.mp.js'),
    other1: path.resolve(__dirname, '../src/mp/other/main.mp.js'),
  },
```
![image](https://user-images.githubusercontent.com/42435611/82429580-bc30cd00-9abe-11ea-86ec-3edc0654c6c5.png)

**Comment by JuneAndGreen** [comment]
你将 common 这个输出目录删掉重新构建下看看呢？我给的 demo 都是增量的，没有删掉旧的输出。所以构建后再新增页面，会重新调整依赖输出，输出可能会有所变化。

**Comment by TomVista** [comment]
删掉重来,就好了 🐶

**Comment by JuneAndGreen** [comment]
好的，看来是这个问题，后续我给 vue\react\preact 这三个模板补下 rimraf 来删除 common 目录。
