### ISSUE TITLE
怎么获取当前页面的PAGE对象？

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#219]
在使用微信原生组件的时候，组件触发的事件是在page对象写的吧？那如何获取page对象呢？或者有其他监听方式

**Comment by xiaojia** [comment]
会了，谢谢，原来wx-component组件的事件不能冒泡，自己写的框架是绑定在父级的，所以针对某些不能冒泡的dom做了处理

**Comment by JuneAndGreen** [comment]
不太理解你原先的问题，如果是使用内置组件的话，可以参考 [demo3](https://github.com/Tencent/kbone/tree/develop/examples/demo3)。内置组件大部分事件没有做冒泡捕获处理，因为原本小程序内部也是如此处理的，但是有些事件比较特殊，会对齐 Web 端，比如 input、focus 等事件。至于如何获取小程序页面实例，使用 getCurrentPages 即可（不过开发者一般应该不需要用到页面实例才对）。

**Comment by xiaojia** [comment]
不好意思 因为是裸用的kbone 把自己的mvvm框架集成进去了，所以遇到了原生组件绑定不上事件的问题，是我自己的问题，其实通过 wxDOM.addEventListener 就能绑定上了，你也说到wx事件不会冒泡 我是做的事件代理 所以没有触发，后来我改了就好了，谢谢
