### ISSUE TITLE
针对dom里的属性值是不是没有做转义？

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#220]
属性的值有可能带双引号 那就需要转义一下 但是我发现kbone里好像没有回转？

比如 <div key="["value"]"></div> 这样取不到值，只能外面改成单引号，但是如果值既有单引号又有双引号就不成了

正常浏览器是可以的 入下图
![image](https://user-images.githubusercontent.com/2154643/82422842-8dfabf80-9ab5-11ea-9339-27d2e79f9dd0.png)

![image](https://user-images.githubusercontent.com/2154643/82422469-12007780-9ab5-11ea-8de8-d443be17aa3b.png)

![image](https://user-images.githubusercontent.com/2154643/82422554-2d6b8280-9ab5-11ea-985c-b3f361ca498d.png)

**Comment by JuneAndGreen** [comment]
是指通过 innerHTML / outerHTML 取的时候没有用实体字符是么？

**Comment by xiaojia** [comment]
是的 因为微信原生组件 比如 wx-picker 里面的属性 range 有可能是 数组对象，而你们内部获取的时候会做 JSON.parse 但是没有转义双引号&quot; 就报错了。。

要是我没表述明白 就加我QQ吧

**Comment by JuneAndGreen** [comment]
已补充实体字符替换：https://github.com/Tencent/kbone/commit/8c01624171fbfdb508d8099c4dc61e061b298779 更新到以下版本即可：

- miniprogram-render@1.4.3
- mp-webpack-plugin@0.9.16

不过你说的 wx-picker 的 range 属性是不会出现在 innerHTML/outerHTML 中的，因为这两者只会拼装常见的那几种属性，并不会将所有属性都拼装进去。会拼装的属性均已对双引号进行实体字符替换。
