### ISSUE TITLE
react中传入boolean类型的属性无效

### ISSUE THREAD

**Issue by lyhper** [Tencent/kbone#221]
只能通过转为字符串

**Comment by JuneAndGreen** [comment]
react 里有这么一段逻辑，会对内置组件的布尔值属性进行丢弃，因此导致没有执行 setAttribute 操作，kbone 里就拿不到对应的值来设置了：

![image](https://user-images.githubusercontent.com/7931744/82533202-6703c280-9b75-11ea-9a1e-28f439f800de.png)

文档已补充说明处理方式：
![image](https://user-images.githubusercontent.com/7931744/82533542-0f198b80-9b76-11ea-9d35-1d37147c52fb.png)
