### ISSUE TITLE
如何在祖先节点上阻止后代组件的事件冒泡

### ISSUE THREAD

**Issue by lyhper** [Tencent/kbone#222]
如题

**Comment by JuneAndGreen** [comment]
阻止内置事件冒泡只有两种方式：
1、event.stopPropagation 方法，但是这个是只能阻止冒泡，但是无法阻止默认行为，也就是说preventDefault 是无效的
2、如果需要冒泡和默认行为可以同时阻止，可以采用 wx-catch

kbone 事件系统说明：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BA%8B%E4%BB%B6%E7%B3%BB%E7%BB%9F

至于怎么利用这两个方法：1 可参考原本 Web 端的用法；2 可参考 kbone 中内置组件的用法。
