### ISSUE TITLE
建议放开 wx-xxxx 原生组件支持

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#223]
目前发现wx-video是不支持的 只能video 这样使用，但是却不支持loadedmetadata事件，建议放开所有，免得如果官方升级某些特性，kbone不能及时跟进的问题

**Comment by JuneAndGreen** [comment]
原理设计上是无法放开的，因为这不是动态编译模板的方案，是采用静态模板来实现递归的方案。

**Comment by JuneAndGreen** [comment]
最新的 video 特性我这边更新一下（后续遇到特性没跟进可以提 issue 或者 pr 即可）。

**Comment by xiaojia** [comment]
感谢，那就建议所有自己维护的组件都更新下最新特性吧
还有一个问题是 小程序的某些组件是需要传布尔值进去的 ，但是html是没法传的，只能通过 element.xxx or setAttribute 这样 这个能否支持下呢？

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/82636974-63844000-9c36-11ea-8ebc-608271baa57b.png)

**Comment by xiaojia** [comment]
是否能判断某些属性只接收布尔值 那就用字符串代替 入  'true' > true 
并且这里只针对微信提供的原生组件来说的

**Comment by JuneAndGreen** [comment]
> 是否能判断某些属性只接收布尔值 那就用字符串代替 入 'true' > true
> 并且这里只针对微信提供的原生组件来说的

不建议这么处理，目前大部分模板引擎不会将 'false' 转成布尔值 false 的，但是反而支持 falsy 的值转为 false，所以传 falsy 的值即可，比如空串。

**Comment by JuneAndGreen** [comment]
已将全部内置组件做了一次属性+事件的升级：https://github.com/Tencent/kbone/commit/8d42befd2e1d7c11cac83ab213b370e19f25c894

可更新到以下版本再试试：

- miniprogram-element@1.4.1
- miniprogram-render@1.4.2
