### ISSUE TITLE
好像没法调用wx.createVideoContext 获取上下文

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#225]
目前需要获取video上下来出发.play()方法
但是好像获取不到呢

video的element上也没有play方法

 wx.createVideoContext(string id, Object this);

kbone页面默认就是在一个大组件下的吧 是不是因为没有this？

**Comment by xiaojia** [comment]
解决了 需要传入 videoDOM._wxComponent 也就是 wx.createVideoContext(id, videoDOM._wxComponent); 但还一个问题是 插入dom虽然是及时的 但是._wxComponent 并不是 需要等一下

**Comment by JuneAndGreen** [comment]
其实 kbone 提供了扩展方法来获取，这样开发者获取会方便些：

参考文档：https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getcontext

**Comment by xiaojia** [comment]
感谢，学艺不精，文档没看全
