### ISSUE TITLE
针对body设置scrollTop无效

### ISSUE THREAD

**Issue by lyhper** [Tencent/kbone#228]
如题

**Comment by lyhper** [comment]
documentElement同样无效

**Comment by JuneAndGreen** [comment]
小程序本身的限制，所以只有 scroll-view 和页面支持 scrollTop（cover-view 其实也支持，不过其本身是设计用于不支持同层的原生组件内部，一般情况不建议使用）。scroll-view 按照内置组件的正常用法即可。

这里你应该是想设置页面的滚动位置，在此提交中已支持：https://github.com/Tencent/kbone/commit/3cd6cbe55d7dc07bd5591ce4c91b122e53a52533
更新到以下版本即可：

- miniprogram-render@1.4.3
- mp-webpack-plugin@0.9.16

用法：设置 document.documentElement.scrollTop（等同于调用 wx.pageScrollTo 方法）。如果要获取页面滚动位置，除非配置了页面的 windowScroll，不然直接通过 document.documentElement.scrollTop 拿到的不一定准确（因为小程序没有提供同步页面读接口，所以无法同步拿到），这种情况可通过 [document.body.$$getBoundingClientRect](https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getboundingclientrect) 接口来获取，它本质上相当于调用：[https://developers.weixin.qq.com/miniprogram/dev/api/wxml/NodesRef.scrollOffset.html](https://developers.weixin.qq.com/miniprogram/dev/api/wxml/NodesRef.scrollOffset.html)，参考其使用即可。
