### ISSUE TITLE
wxCustomComponent 没有处理依赖是吗

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#230]
wxCustomComponent 是单纯的复制过来吗 没有处理里面的 require？ 我看效果是这样的

还有一个问题是我可能会引用多个微信组件，该怎么处理，我不可能把所有组件都放到一个文件夹里吧

能不能直接读取package.json里的数据进行依赖处理呢？

**Comment by JuneAndGreen** [comment]
是的，kbone 不会尝试去理解里面的实现，只会原样拷贝。提供自定义组件的支持是为了提供一个使用原生小程序写法的入口，但是这并不是使用 kbone 时的推荐用法，使用 kbone 时还是建议使用 Web 技术来实现。至于被拷贝目录里面要如何实现，开发者可以采用任意方案（比如直接实现在里面，或者使用构建工具构建到里面）。

如果你的页面里需要大量使用小程序的自定义组件，其实这个页面就已经不适合使用 kbone 来开发。kbone 终究是某一类场景的解决方案，无法做到各个场景都完备支持。若是这种场景，可以全部采用原生实现，也可以使用 kbone 的 generate.app 配置，适合 kbone 的页面用 kbone 实现，不适合的页面使用原生实现。

**Comment by xiaojia** [comment]
感谢，那如果我想混合使用，比如大部分页面可以用kbone来做展示，但是其中几个页面因为需要高性能所以采用原生页面来做，这样改怎么配置呢？

**Comment by JuneAndGreen** [comment]
通过配置 [generate.app](https://wechat-miniprogram.github.io/kbone/docs/config/#generate-app) 可以只生成页面相关文件；

通过配置 [generate.subpackages](https://wechat-miniprogram.github.io/kbone/docs/config/#generate-subpackages) 可以将页面生成到分包目录里，这个不是必须的，但是如果你希望生成的 common、pages 目录都在小程序项目的某个指定目录下，和原生的小程序代码分离开，可以利用这个配置；

然后其他小程序页面、app.js、app.json 登文件就可以采取其他的方式来编写，这样就达到了混合 kbone 使用的目的。
