### ISSUE TITLE
如何自己处理wxCustomComponent

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#231]
刚刚在 https://github.com/Tencent/kbone/issues/230#issuecomment-633878058 问了如何使用wxCustomComponent 你提到可以自己来做复制处理，但是有一个问题是，当我配置wxCustomComponent但是不配置root时，你是不会有自定义组件处理的，也就是生成的目录没有custom-component文件夹，那我就无法自己处理自定义组件了，因为你不会在pages/xxx/xxx.json下引入custom-component 作为通用的自定义组件

那我的需求如果是我自己来处理复制组件这个动作，但配置还得基于你的 wxCustomComponent 配置，该怎么实现呢？

**Comment by JuneAndGreen** [comment]
还是要配置 root，#230 提到的不是自己复制组件到小程序目录中，而是你可以选择任意方法把你的目标代码生成到 root 指定的目录中（注意：这个“自己处理”要在构建小程序之前进行），后续再交由 mp-webpack-plugin 拷贝到小程序目录中即可。

**Comment by xiaojia** [comment]
了解 感谢
