### ISSUE TITLE
useExtendedLib kbone true 的问题

### ISSUE THREAD

**Issue by xiaojia** [Tencent/kbone#233]
如果我开启了useExtendedLib kbone true 的话能不能不自动添加 dependencies render、element 这两个包，不然我开启自动npm或者我有自己的依赖时候，就需要进入到生成目录执行 npm i 并且执行ide构建的时候会提示 
（miniprogram_npm 目录下的 miniprogram-element 包与扩展库 kbone 发生冲突，请移除 miniprogram-element 包或者删除 `useExtendedLib.kbone` 配置）

**Comment by xiaojia** [comment]
另外 增加的 render和element版本都是latest 这样是不是会有风险？，我在用mp-webpack-plugin的时候可能是某一个低版本，样这样会不会出现不兼容的情况？

**Comment by xiaojia** [comment]
虽然我现在通过webpack plugin实现了移除package.json下的 render 和 element 但是有一个问题是，你在自动npm install的时候 执行了 copyDir，我每次运行因为没有依赖 render和element 但是依旧会拷贝，所以会有两条警告，在不改源码的情况下，我好像解决不掉这个问题

**Comment by JuneAndGreen** [comment]
你应该是开了这个吧，把这个关掉试试呢？
https://wechat-miniprogram.github.io/kbone/docs/config/#generate-autobuildnpm

另外 latest 的问题，因为 element/render 的更新频率远远大于 mp-webpack-plugin，所以目前是设定成 latest，方便当这两个包出现更新时开发者可以尽快应用上。我们开发过程中会尽量做到向前兼容，所以不兼容的概率应该很小。

**Comment by xiaojia** [comment]
对哦 是开了autoBuildNpm 因为你说明上是说，自动安装小程序依赖，所以我理解为自己执行 npm install，但是你们在里面又做了其他处理，那我只能自己来实现 自动 npm install 了。。

**Comment by JuneAndGreen** [comment]
两者是有冲突的，文档l里有说明：
![image](https://user-images.githubusercontent.com/7931744/83020993-e7399480-a05b-11ea-98ca-3a89c02cf099.png)

https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%89%A9%E5%B1%95%E5%BA%93

**Comment by xiaojia** [comment]
嗯 这个是我忘记了，不过还有一个问题，当我配置了package.json dependencies 的时候，我有需求在小程序里 npm i 并且构建，问题在于不管怎么样，框架都会生成 render 和 element 这俩依赖，这样的话，就会 kbone: true 冲突了，是否可以判断，如果我开启了 kbone: true 就不生成这俩依赖呢？

**Comment by JuneAndGreen** [comment]
dependencies  里去掉就行了，用任意方式都行。
