### ISSUE TITLE
是否支持 nest router,试了下在小程序中貌似不支持

### ISSUE THREAD

**Issue by Chryseis** [Tencent/kbone#234]
尝试用nest路由时，`routes: [
    {
      path: '/home',
      component: layout,
      children: [
        {
          path: '',
          name: 'home',
          component: Home,
          meta: {
            NotkeepAlive: true
          }
        }
      ]
    }
  ]`，小程序中报错`VM12873:1 TypeError: Cannot read property 'appendChild' of undefined`

**Comment by JuneAndGreen** [comment]
支持的，参考 demo5：https://github.com/Tencent/kbone/blob/421d1672e5ab4cf447510961e1a9105893307c21/examples/demo5/src/page4/main.mp.js

这个报错看起来是代码其他逻辑引起的，检查一下这些组件？

**Comment by Chryseis** [comment]
好的 我检查下
