### ISSUE TITLE
超过domSubTreeLevel的层级被删减掉了

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#236]
这个问题我只在我的项目上复现了,我拉下来git上的vue模板复现不了.

代码不能公开,能不能提供一个测试思路.

**Comment by TomVista** [comment]
element:"version": "1.4.3"

render:"version": "1.4.5"

    "mp-webpack-plugin": "^0.9.11",

**Comment by JuneAndGreen** [comment]
基本在这个方法里：https://github.com/Tencent/kbone/blob/develop/packages/miniprogram-element/src/util/tool.js#L28

domSubTreeLevel 表示一个自定义组件管理的 dom 子树的最高层数，到达这个层数后，再下面的节点会又再生成一个自定义组件，层层递归下去，直到整棵树被生成出来。

你可以先看看 appservice 端的 dom 树生成的是否符合预期，如果 dom 树争吵，可以看看上面我贴的 filterNodes 方法逻辑，这个方法是用来获取这个自定义组件渲染这棵 dom 子树需要的树形结构的数据。

**Comment by TomVista** [comment]
我在window.open打开的页面做了 如下操作
```
setimeout(()=>{
this.$el.parent.remove(this.$el)
},2000)
wx.naback()
``` 

然后返回页面
```
// wxshow
this.address =await ajax.get
```

address  是一个v-for 的数组,
2s后,最后一个address 或者第一个address 会被移除

可以确定不是dom树的问题了,具体我再看看,目前还是不能在其他项目复现

**Comment by JuneAndGreen** [comment]
那这边就暂时关闭了，如果有具体的例子或者其他相关问题复现可 reopen。
