### ISSUE TITLE
如何 把一段 文字渲染在输入框中。

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#240]
例如 
```
<p>whishshui</p> <p>如何 把一段 文字渲染在输入框中。</p>
````

**Comment by Hxmic** [comment]
v-html 不支持。难受

**Comment by JuneAndGreen** [comment]
输出框，是指 input 标签？这个直接配置 value 就可以，如 <input :value="123" />。

如果是上面提到的 v-html，这个指令是支持的，比如 <p v-html="文字"></p> 这样使用，相当于是 innerHTML 了。
