### ISSUE TITLE
$$miniprogram、$$cookie偶尔会报错

### ISSUE THREAD

**Issue by mumuxiaozhu** [Tencent/kbone#243]
![image](https://user-images.githubusercontent.com/24982685/84273397-3524c100-ab61-11ea-86de-9e5d2ca41315.png)
![image](https://user-images.githubusercontent.com/24982685/84273634-7ae18980-ab61-11ea-87db-619762ec4e27.png)

**Comment by JuneAndGreen** [comment]
这里是不是存在定时器或者其他的异步逻辑，导致页面销毁后还有调用/请求发起？

**Comment by mumuxiaozhu** [comment]
是这个原因，在页面销毁的后上一个页面还有异步回调，已修复，谢谢
