### ISSUE TITLE
有计划搞像Taro一样的优化方案吗

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#245]
Taro与其他框架实现原理不同
https://github.com/NervJS/taro/blob/docs/docs/difference-to-others.md

大概是
1. react方面，使用react-reconciler来精简不必要的react浏览器兼容代码
2. dom更新方面，使用setData路径来优化传输量，提升小程序性能

第一点，我觉得不应该做，因为不够「隔离」。

第二点，我觉得可以搞一下

举个随便我们小程序的例子，
![image](https://user-images.githubusercontent.com/5879146/84725770-f017e900-afbd-11ea-8297-66dbdbc7e794.png)

虽然表面看不出来，但是由于有大量交互弹窗类，所以实际上dom结构已经很复杂，并且很多是临时创建的。在安卓机器上，明显感觉很吃力。

之前有心理预期，毕竟结构多了，肯定会卡。但这个产品的结构还没有其他产品1/3多，现在已经吃力，以后估计更难跑起来。

本身优化做了，但性能瓶颈我觉得还是在dom的更新上。

所以，回到小程序原生，优化最简单也最有效果的一点就是setData的频率和传输量。

以前可以控制setData的传输方式，例如搞个diff patch的操作。现在由于接触不到（也不应该接触）到setData。所以没办法进行控制

总而言之，我感觉如果setData可以变成diff patch的方式应该可以提升一下性能。

**Comment by JuneAndGreen** [comment]
第二点可以做，而且也有计划。只是近期在等基础库 2.11.2 的一个特性，准备做一个 2.x 的升级，到时候可能会加进去。

一开始没有做这个其实是考虑到这个只是优化了传输的数据大小（因为小程序无论如何都会做一次数据 merge 和树比较），而且对于数组的增删和换位没有太大的优化效果，所以就一直搁着没有开始。

**Comment by xmsz** [comment]
> 第二点可以做，而且也有计划。只是近期在等基础库 2.11.2 的一个特性，准备做一个 2.x 的升级，到时候可能会加进去。
> 
> 一开始没有做这个其实是考虑到这个只是优化了传输的数据大小（因为小程序无论如何都会做一次数据 merge 和树比较），而且对于数组的增删和换位没有太大的优化效果，所以就一直搁着没有开始。

我的印象还停留在omi （https://github.com/Tencent/westore），通过预先进行diff来优化，不过自己也没测过


关于2.x版本，可以透露一下更新了哪些吗？还有说到基础库，是说会依赖到基础库版本吗

因为我们现在业务都在qq上，所以如果基础库要求太高或者有强关联，可能会不兼容

**Comment by JuneAndGreen** [comment]
主要的变更：准备剔除使用内置组件时引入的额外一层 dom（因为使用自定义组件导致的）。这个需要基础库那边支持创建自定义组件时可以不生成外包那层 dom 结构。

这个支持的话，就不需要在使用内置组件时，在样式中使用类似 .h5-virtual 这样的 class 去处理使用和结构相关的一些样式问题了（比如 flex 样式）。

**Comment by xmsz** [comment]
> 主要的变更：准备剔除使用内置组件时引入的额外一层 dom（因为使用自定义组件导致的）。这个需要基础库那边支持创建自定义组件时可以不生成外包那层 dom 结构。
> 
> 这个支持的话，就不需要在使用内置组件时，在样式中使用类似 .h5-virtual 这样的 class 去处理使用和结构相关的一些样式问题了（比如 flex 样式）。

这个会做兼容处理吗，例如qq小程序那边肯定不支持创建时不生成dom结构。

**Comment by JuneAndGreen** [comment]
> 这个会做兼容处理吗，例如qq小程序那边肯定不支持创建时不生成dom结构。

这个是涉及到整个渲染的变动，不一定能在同一个包完成兼容处理，这个得看最终的效果，所以才准备做一个大版本的变化。如果仍然需要用到低版本基础库的情况，用回 1.x 版本即可。

最新的 mp-webpack-plugin 已经提供了配置 element/render 版本的地方：generate.renderVersion 和 generate.elementVersion，相关文档：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-renderversion

**Comment by Hxmic** [comment]
配置路由，新建页面可不可以简化一点。感觉流程很麻烦。

**Comment by JuneAndGreen** [comment]
@xmsz 目前 2.x 发了个 next 版本，目前看基本能兼容旧基础库的渲染模式，除非原本的小程序里有严格依赖层级关系的样式（比如依赖 .h5-virtual 这个 class 来实现的一些样式）。至于 setData 优化这里，目前看来这里引入的优势是可以减少 appService 端发往 webview 端的数据量，但是会引入染色更新可能不准确的问题，所以此处还待调研一下。

**Comment by JuneAndGreen** [comment]
@Hxmic 新建页面应该就三步（https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html#%E7%BC%96%E5%86%99-webpack-%E9%85%8D%E7%BD%AE）：
1、webpack 配置入口：用于让 mp-webpack-plugin 知道要生成的页面
2、插件配置路由：让 kbone 知道这个页面要响应的 url，这样进行 window.open / location.href 的时候才知道去哪个页面
3、新增入口文件，给 webpack 构建用

相比 Web 端新增页面就多了第 2 步，这些信息 kbone 都无法推测，所以只能开发者来配置了。不过这些步骤都是白盒子，开发者可以自己控制的，也就是说开发者可以自己写脚本一键新增个页面之类的，目前 kbone 提供的模板和 cli 都是比较基础的，所以不会提供此功能。

**Comment by xmsz** [comment]
> @xmsz 目前 2.x 发了个 next 版本，目前看基本能兼容旧基础库的渲染模式，除非原本的小程序里有严格依赖层级关系的样式（比如依赖 .h5-virtual 这个 class 来实现的一些样式）。至于 setData 优化这里，目前看来这里引入的优势是可以减少 appService 端发往 webview 端的数据量，但是会引入染色更新可能不准确的问题，所以此处还待调研一下。

开始用2.x的版本，暂时没看到问题

**Comment by JuneAndGreen** [comment]
setData 局部更新 data path 的方式已实现，更新 miniprogram-element@2.1.0 即可，在 data path 超过一定数量时会降级回全量 setData，先前提到的染色更新问题目前使用强制更新的方案来处理。目前测试案例中对于小范围更新会有一定程度的耗时缩减（在低端机会比较明显，因为 diff 范围不变，所有推测应该是 merge 那块和数据传输的耗时缩减了）。

如遇到问题，可新建 issue 跟进，然后使用此配置快速回退到全量 setData 的模式：https://wechat-miniprogram.github.io/kbone/docs/config/#optimization-setdatamode 。
