### ISSUE TITLE
安装了kbone-ui，使用kbone-ui组件时，单位px如何转化为rem，或者rpx

### ISSUE THREAD

**Issue by github-wbb** [Tencent/kbone#246]

**Comment by JuneAndGreen** [comment]
小程序中 rem 使用参考配置：https://wechat-miniprogram.github.io/kbone/docs/config/#global-rem ，里面用到的 fontSize 计算方式可以根据自己实际使用情况来做调整。

rpx 的话，如果你是只跑在小程序端，直接用 rpx 即可，如果还需要跑在 Web 端的话，需要自己对样式做处理了，因为 Web 端没有 rpx 单位。
