### ISSUE TITLE
推送的模板卡片 无法跳转

### ISSUE THREAD

**Issue by cuiyuanguang** [Tencent/kbone#247]
服务端调用 templateMessage.send;
其中page字段 传入页面url 与 小程序路由均不成功;
导致点击模板卡片无法正常跳转至指定页面.

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/84984635-d4ebdb80-b16d-11ea-93ff-a86183e202c6.png)

小程序的页面路由需要带上页面的 url，参考 QA：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91

**Comment by cuiyuanguang** [comment]
试过这个了 /pages/home/index?type=${type}&targeturl=${encodeURIComponent(location.href)}，
不行，跳转的页面空白

**Comment by cuiyuanguang** [comment]
我们实际的配置是：
/pages/detail/index?type=open&targeturl=https%253A%252F%252Ftest.miniprogram.com%252Fdetail%253Fid%253D21758
并不能正确跳转

**Comment by JuneAndGreen** [comment]
targeturl 你 encodeURIComponent 了两遍。

**Comment by cuiyuanguang** [comment]
好了 多谢
