### ISSUE TITLE
多页面应用子文件夹中的页面打包后，资源路径不正确

### ISSUE THREAD

**Issue by LastHeaven** [Tencent/kbone#248]
entry  
```js
entry: {
        page1: path.resolve(__dirname, '../src/pages/page1/main.mp.js'),
        page2: path.resolve(__dirname, '../src/pages/page2/main.mp.js'),
        page3: path.resolve(__dirname, '../src/pages/page3/main.mp.js'),
        'testp/page3': path.resolve(__dirname, '../src/pages/testp/page3/main.mp.js'),
    },
```

router
```js
{ page1: [ '/page1' ],
  page2: [ '/page2' ],
  page3: [ '/page3' ],
  'testp/page3': [ '/testp/page3' ] }
```

页面路径:  
![image](https://user-images.githubusercontent.com/10590077/84966808-02705f00-b145-11ea-8254-357cd50d6e8f.png)
异常提示：  
![image](https://user-images.githubusercontent.com/10590077/84966901-44010a00-b145-11ea-9d07-a5c19c8dfb75.png)

解决方案：
mp-webpack-plugin/src/index.js
![image](https://user-images.githubusercontent.com/10590077/84967094-ba9e0780-b145-11ea-94c2-23e50b9e5161.png)

**Comment by JuneAndGreen** [comment]
不要用“'testp/page3'”这样带多段路径的串作为页面 key，kbone 这里生成的页面路径需要遵从固定的结构才能有效运行。

如果你需要子目录结构，可以使用分包配置：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-subpackages
