### ISSUE TITLE
提供已编译的miniprogram-element和miniprogram-render?

### ISSUE THREAD

**Issue by ManfredHu** [Tencent/kbone#251]
关闭开发者工具的babel编译，会报错。此处是否应该提供纯净的可直接运行的小程序npm包？
还有kbone demo的babel是否可升级babel7而不依赖开发者工具的编译转化？

**Comment by JuneAndGreen** [comment]
为何需要关闭工具的 babel 呢？如果你是需要处理某些文件不过 babel，可以配置 project.config.json 来处理：

https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html
![image](https://user-images.githubusercontent.com/7931744/85975230-13a15180-ba0a-11ea-921b-96ebbe665c6c.png)

**Comment by JuneAndGreen** [comment]
以下版本已经提供打包混淆后的代码，但是并未通过 babel 编译。

 - miniprogram-element@1.5.0
 - miniprogram-render@1.5.0

如上述所说，可以配置 project.config.json 的 babelSetting.ignore 属性来指定哪些文件/目录跳过 babel 编译，所以如果开发者有些文件需要自己走 babel 不走工具 babel 的话，可以开启后配置此项来指定不通过工具 babel。默认 demo 中 common 就是跳过了工具 babel。
