### ISSUE TITLE
小程序自定义路径无法打开。

### ISSUE THREAD

**Issue by Hxmic** [Tencent/kbone#252]
1. 小程序直接按下面编译无法打开页面。生成得小程序码，也是按这样写的，也不可以。
![image](https://user-images.githubusercontent.com/23522154/86094952-c72a4480-bae3-11ea-8c20-22ea76daa445.png)

2. 生成后小程序文件，都有这个路径为啥不可以呢？
![image](https://user-images.githubusercontent.com/23522154/86095091-05276880-bae4-11ea-93f7-6c7cbfebe703.png)

**Comment by Hxmic** [comment]
@JuneAndGreen  大佬我要怎么处理。

**Comment by JuneAndGreen** [comment]
你的页面可能需要根据 location.href 来响应的吧，这种写法 location.href 是默认值来的。

https://wechat-miniprogram.github.io/kbone/docs/qa/

![image](https://user-images.githubusercontent.com/7931744/86107950-1af15980-baf5-11ea-90d4-753d9380b6d9.png)

你如上面文档描述那样，启动参数带上 type=open&targeturl=${encodeURIComponent(你要打开的页面对应的 url，可以不加 origin 部分以缩减参数的长度)}

**Comment by Hxmic** [comment]
如果我要打开pages/class/index   需要参数id=niumingxin0123

是这样的吗？

![image](https://user-images.githubusercontent.com/23522154/86122571-a1fcfc80-bb0a-11ea-92fb-ac5251cacca4.png)

**Comment by JuneAndGreen** [comment]
type=open&targeturl=${encodeURIComponent('/你的页面路径?id=niumingxin0123')

**Comment by Hxmic** [comment]
感谢了。我这里还是不成功。不弄了。。

**Comment by JuneAndGreen** [comment]
不应该不成功的。。。这里启动时最主要的参数就两个：type 表示打开类型，targeturl 表示打开后这个页面的 location.href 要初始化成哪个，代码在这里：https://github.com/Tencent/kbone/blob/develop/packages/mp-webpack-plugin/src/tmpl/page.tmpl.js#L79

另外你这里也可以不用手动配的，可以配置到插件的 [projectConfig](https://wechat-miniprogram.github.io/kbone/docs/config/#projectconfig) 字段，构建时自动合并到 project.config.json 中。

下面是个简单的例子：

```js
{
        projectConfig: {
		appid: 'wx12345',
		projectname: 'demo',
		libVersion: '2.11.2',
		condition: {
			miniprogram: {
				current: 0,
				list: [{
					id: -1,
					name: 'page1',
					pathName: '/pages/test1',
					query: 'type=open&targeturl=%2Fabc%3Fid%3D123', // /abc?id=123
					scene: null,
				}, {
					id: -2,
					name: 'enterpriseProfile',
					pathName: '/pages/test2',
					query: 'type=open&targeturl=%2Fcba%3Fid%3D321', // /cba?id=321
					scene: null,
				}]
			}
		}
	},
}
```

**Comment by Hxmic** [comment]
嗯嗯。那等等再检查下。感谢大佬了。

**Comment by JuneAndGreen** [comment]
请问这里的问题解决了么？

**Comment by JuneAndGreen** [comment]
> 嗯嗯。那等等再检查下。感谢大佬了。

@Hxmic 请问这里的问题解决了吗？

**Comment by 1927344728** [comment]
遇到同样问题。  
最终发现是从微信开发者工具的，自动添加的 【页面参数】中 targeturl 参数有问题。该参数的值 decodeURIComponent 后，不是所需要的 location.href。  
我手动 encodeURIComponent location.href，添加到 targeturl ，问题解决。
