### ISSUE TITLE
有什么办法控制启动屏

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#254]
现在基本上等到用户小程序下载完，还要等个2s左右才能渲染页面

之间包括了小程序页面启动（包括加载js） + Vue App渲染  + 页面渲染

而前面这段时间白屏时间很久，也没办法控制。

现在的需求就是控制这段时间的显示，不用让用户白屏太久。

Web端的话，直接写在index.html模板里，这样没加载Vue之前就有东西显示给用户，即使只是一句话而已。

而Kbone中要怎么实现？

想象中是，开放页面模板文件

**Comment by JuneAndGreen** [comment]
暂时没有，我看看近期能否提供一下往页面模板注入小程序自定义组件/wxml模板的能力。

**Comment by JuneAndGreen** [comment]
已支持：mp-webpack-plugin@1.1.2
相关文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E5%8A%A0%E8%BD%BD%E8%A7%86%E5%9B%BE
参考 demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo3 ，可通配，也可以单独页面配置。
