### ISSUE TITLE
原有项目使用postcss-px2rem-exclude 进行px转换rem，kbone是否可以支持？

### ISSUE THREAD

**Issue by zmzxn** [Tencent/kbone#255]
原有再跑项目使用的postcss-px2rem-exclude 进行px转换rem，现在kbone需要怎么配置生效，目前暂未找到解决方案

**Comment by JuneAndGreen** [comment]
kbone 中使用 rem： https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8-rem

![image](https://user-images.githubusercontent.com/7931744/86595314-22b86e80-bfcb-11ea-92f9-bac7420e8169.png)

**Comment by zmzxn** [comment]
我们项目目前是通过此插件转译成的rem在写代码的时候还是以px为单位，然后打包生成的时候会自动转换成rem，不是直接使用rem的

**Comment by zmzxn** [comment]
> kbone 中使用 rem： https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8-rem
> 
> ![image](https://user-images.githubusercontent.com/7931744/86595314-22b86e80-bfcb-11ea-92f9-bac7420e8169.png)

我们项目目前是通过此插件转译成的rem在写代码的时候还是以px为单位，然后打包生成的时候会自动转换成rem，不是直接使用rem的

**Comment by JuneAndGreen** [comment]
一样的使用方式，生成到小程序时也可以同样插件处理。只是 fontSize 的计算公式可能得略微调整而已。

**Comment by JuneAndGreen** [comment]
有兴趣可以了解下 kbone 的原理：https://wechat-miniprogram.github.io/kbone/docs/guide/principle.html

kbone 本质是一个适配器，仿造出浏览器环境。怎么生成代码 kbone 不关心，kbone 只关心生成后的代码用到的浏览器接口能否模拟出来的。
