### ISSUE TITLE
web页面可以正常展示，转到小程序端页面空白，

### ISSUE THREAD

**Issue by zmzxn** [Tencent/kbone#257]
![image](https://user-images.githubusercontent.com/23032786/86919722-43afc980-c15b-11ea-9913-718fe6f95532.png)
![image](https://user-images.githubusercontent.com/23032786/86920072-b8830380-c15b-11ea-893b-9d86369e6b8b.png)
将原有项目代码迁移到kbone中，web页面可以正常展示，小程序端页面空白，会是哪些原因造成的

**Comment by JuneAndGreen** [comment]
这个有很多种可能性，配置不对，路由处理不对等问题都有可能。看截图这里你用的初始 url 是 /login，所以你要确保初始进入的页面路由参数里带有这个 url 才行，因为默认进入是 / ，你的这个页面是响应不到的，初始 url 可以配置 [entry](https://wechat-miniprogram.github.io/kbone/docs/config/#entry) 来解决。另外你这个 /login 也得配置到 [route](https://wechat-miniprogram.github.io/kbone/docs/config/#router) 中，这样 kbone 才能知道你使用 location 跳转到 /login 的时候是要进到哪个小程序页面。

另外你可能用了小程序的 tabbar ？如果是的话，你需要在 router 那里配一个 / 跳到 /login 的跳转才行，因为小程序的 tabbar 页面的路由配置不能带参数，所以默认进去的只能是 / 。

如果不是上述问题引入的，可以对比下这个文档：https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html 和 demo：https://github.com/Tencent/kbone/tree/develop/examples，看看是否哪个环节疏忽了？

**Comment by zmzxn** [comment]
> 这个有很多种可能性，配置不对，路由处理不对等问题都有可能。看截图这里你用的初始 url 是 /login，所以你要确保初始进入的页面路由参数里带有这个 url 才行，因为默认进入是 / ，你的这个页面是响应不到的，初始 url 可以配置 [entry](https://wechat-miniprogram.github.io/kbone/docs/config/#entry) 来解决。另外你这个 /login 也得配置到 [route](https://wechat-miniprogram.github.io/kbone/docs/config/#router) 中，这样 kbone 才能知道你使用 location 跳转到 /login 的时候是要进到哪个小程序页面。
> 
> 另外你可能用了小程序的 tabbar ？如果是的话，你需要在 router 那里配一个 / 跳到 /login 的跳转才行，因为小程序的 tabbar 页面的路由配置不能带参数（这个 kbone 无法兼容，所以无能为力了...），所以默认进去的只能是 / 。
> 
> 如果不是上述问题引入的，可以对比下这个文档：https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html 和 demo：https://github.com/Tencent/kbone/tree/develop/examples ，看看是否哪个环节疏忽了？

![image](https://user-images.githubusercontent.com/23032786/86922401-267cfa00-c15f-11ea-89be-10db9cc67d0d.png)
![image](https://user-images.githubusercontent.com/23032786/86922425-309ef880-c15f-11ea-9e47-5e812cc79d94.png)
![image](https://user-images.githubusercontent.com/23032786/86922442-385e9d00-c15f-11ea-98ad-67b143936785.png)
这边我相应的配置都是有的，我将login配置到了tabbar，在原有的路由里面也有这个路由配置
![image](https://user-images.githubusercontent.com/23032786/86922544-6643e180-c15f-11ea-9655-821d60f0d95f.png)

**Comment by JuneAndGreen** [comment]
> 另外你可能用了小程序的 tabbar ？如果是的话，你需要在 router 那里配一个 / 跳到 /login 的跳转才行，因为小程序的 tabbar 页面的路由配置不能带参数（这个 kbone 无法兼容，所以无能为力了...），所以默认进去的只能是 / 。

那你需要按照这个加一个 redirect 的跳转才行，因为 tabbar 页面默认进入的 location.pathname 是 / 。

**Comment by zmzxn** [comment]
> > 另外你可能用了小程序的 tabbar ？如果是的话，你需要在 router 那里配一个 / 跳到 /login 的跳转才行，因为小程序的 tabbar 页面的路由配置不能带参数（这个 kbone 无法兼容，所以无能为力了...），所以默认进去的只能是 / 。
> 
> 那你需要按照这个加一个 redirect 的跳转才行，因为 tabbar 页面默认进入的 location.pathname 是 / 。

这个是加在哪个配置文件下面呢，好像有点萌！是这里嘛
![image](https://user-images.githubusercontent.com/23032786/86993176-e9a01a00-c1d5-11ea-805b-d25e0193f84f.png)

**Comment by JuneAndGreen** [comment]
是指 vue-router 的 redirect：
![image](https://user-images.githubusercontent.com/7931744/87003939-29bfc680-c1ef-11ea-88f2-3248ecdace4b.png)

https://router.vuejs.org/zh/api/#routes
