### ISSUE TITLE
npm下载axios-miniprogram-adapter@^0.3.1提示没有匹配版本

### ISSUE THREAD

**Issue by wu253494078** [Tencent/kbone#258]
No matching version found for axios-miniprogram-adapter@^0.3.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
![image](https://user-images.githubusercontent.com/32081454/86990388-100e8700-c1cf-11ea-9ddf-55eceaeabc22.png)

**Comment by JuneAndGreen** [comment]
不需要 adapter 也可以用了，原生支持了 XMLHttpRequest 对象。

![image](https://user-images.githubusercontent.com/7931744/87003324-fdf01100-c1ed-11ea-8f43-1a41a0686ef4.png)
