### ISSUE TITLE
onShareTimeline 方法不生效

### ISSUE THREAD

**Issue by runyuweng** [Tencent/kbone#259]
wx.onShareTimeline = () => ({
  title: '测试',
  query: 'a=1&b=2'
});

title 展示不符合预期，query 参数通过 wx.getLaunchOptionsSync() 和 window.location.search 都获取不到

**Comment by JuneAndGreen** [comment]
query 参数要参考这个来处理，kbone 的 location.search 不是小程序页面路由的 query，两者不能划等号，但是可以简单认为 location.href 是小程序页面路由 query 的一部分，kbone 根据 query 的 targeturl 等参数来初始化 location 对象：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91

![image](https://user-images.githubusercontent.com/7931744/87004404-ec0f6d80-c1ef-11ea-8b0a-07779eb7c382.png)

至于 title 问题，你试试原生随便写个 demo 是否可以，kbone 没有处理，wx.xxx 方法调用和原生小程序里调用没区别的。

**Comment by JuneAndGreen** [comment]
提供了页面的 onShareTimeline 钩子，可以让 kbone 来处理路径：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-onsharetimeline

需要更新 mp-webpack-plugin 到最新版本。
