### ISSUE TITLE
vue封装的axios 在小程序中报错

### ISSUE THREAD

**Issue by wu253494078** [Tencent/kbone#260]
![image](https://user-images.githubusercontent.com/32081454/87025698-4e2a9b80-c20d-11ea-9a86-53d4f8f8a332.png)
![image](https://user-images.githubusercontent.com/32081454/87025758-63072f00-c20d-11ea-81f3-ad66b1941200.png)

**Comment by JuneAndGreen** [comment]
同 #258 ，不需要 axios-miniprogram-adapter，先去掉试试。另外确保该接口在小程序是能调通的，看报错 Network Error 是请求报错了的样子。
