### ISSUE TITLE
npm run mp 打包后 home.js 变成Home.js

### ISSUE THREAD

**Issue by wangliguokaka** [Tencent/kbone#262]
使用npm run mp打包后在开发工具中打开运行，提示
Cannot read property 'default' of undefined;at "pages/home/index" page lifeCycleMethod onLoad function
后来查看打包文件列表发现，有同名但首字母大小写不同的两个文件，如下图，最后打包的文件里只有Home.js
![1](https://user-images.githubusercontent.com/17798088/87113755-f68e3d80-c2a9-11ea-8e62-f570f80e4e6b.png)

而pages文件夹下的index.js 引用的却是home.js,如图
![2](https://user-images.githubusercontent.com/17798088/87113828-1faece00-c2aa-11ea-99db-42ac656e7701.png)

所以这个问题是webpack.mp的bug 还是 开发过程中对框架使用的问题?

**Comment by JuneAndGreen** [comment]
mp-webpack-plugin 不会对输出文件做大小写的转换的，只会对输出的文件内容包裹一些代码，并且补充小程序相关的代码。common 目录下的文件名均是由 webpack 处理的。检查下 webpack 的配置是否有问题？

**Comment by JuneAndGreen** [comment]
@wangliguokaka 请问这里的问题是否解决？如果 webpack 配置正常的话，看看能否提供一下 demo？

**Comment by wangliguokaka** [comment]
问题已经解决了 是我在其他的界面多引用了router 去掉就好了
