### ISSUE TITLE
window.addEventListener('storage') tab页只能触发当前页面

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#263]
因为getCurrentPages只能获取当前tab页面的实例，所以其他页面不会触发，这个有什么办法吗？

**Comment by JuneAndGreen** [comment]
这个估计得 kbone 来兼容下了，开发者不太好做处理。

**Comment by JuneAndGreen** [comment]
2.x 版本：miniprogram-render@2.0.7  
1.x 版本：miniprogram-render@1.5.1

已兼容。

**Comment by xmsz** [comment]
> miniprogram-render@2.0.7

ok 暂时没发现什么问题
