### ISSUE TITLE
window.addEventListener('storage') 的page.window !== this.$_window都是false

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#264]
背景：
发现没办法触发window.addEventListener('storage')，发现page.window !== this.$_window这个条件都是false

所以什么情况下这个条件是不为true，或者如何让这个条件成立

**Comment by JuneAndGreen** [comment]
你这个页面是不是 tabbar 页面？

**Comment by JuneAndGreen** [comment]
当有其他页面时，会在其他页面上触发 storage，只有一个页面时这里就恒为 false，和 Web 端表现一致，当前页面设置 localStorage 不触发当前页面的 storage 事件。如果其他页面都是 tabbar 页面，那问题应该是和 #263 一样的，找不到其他页面的实例。

**Comment by JuneAndGreen** [comment]
2.x 版本：miniprogram-render@2.0.7
1.x 版本：miniprogram-render@1.5.1

tabbar 页面 storage 事件问题已修复，可更新以上版本试试。
