### ISSUE TITLE
Seems to be a version incompatibility? Has anyone checked the version？

### ISSUE THREAD

**Issue by ksjhb111** [Tencent/kbone#265]
PS D:\kbone-template-vue-master> npm run mp

> vue-kbone@0.0.1 mp D:\kbone-template-vue-master
> rimraf dist/mp/common && cross-env NODE_ENV=development webpack --config build/webpack.mp.config.js --progress --hide-modules

10% building 0/0 modules 0 active
webpack is watching the files…

94% after seal
start building dependencies...

built dependencies successfully

path not exists: "D:\kbone-template-vue-master\dist\mp\node_modules\miniprogram-element\src"
path not exists: "D:\kbone-template-vue-master\dist\mp\node_modules\miniprogram-render\src"

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 81217d738a4ca8184807
Version: webpack 4.43.0
Time: 9406ms
Built at: 2020-07-15 3:30:01 PM
 8 assets
Entrypoint home = vendors~home~other.js default~home~other.wxss default~home~other.js home.wxss home.js
Entrypoint other = vendors~home~other.js default~home~other.wxss default~home~other.js other.wxss other.js

ERROR in Entry module not found: Error: Can't resolve 'D:\kbone-template-vue-master\src\mp\todos\mp\js' in 'D:\kbone-template-vue-master'
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/postcss-loader/lib/index.js??postcss!node_modules/less-loader/dist/cjs.js!node_modules/thread-loader/dist/cjs.js!node_modules/vue-loader/lib/index.js??vue-loader-options!node_modules/vue-improve-loader/src/index.js!src/common/Footer.vue?vue&type=style&index=0&lang=less&:
    Entrypoint mini-css-extract-plugin = *
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/postcss-loader/lib/index.js??postcss!node_modules/less-loader/dist/cjs.js!node_modules/thread-loader/dist/cjs.js!node_modules/vue-loader/lib/index.js??vue-loader-options!node_modules/vue-improve-loader/src/index.js!src/common/Header.vue?vue&type=style&index=0&lang=less&:
    Entrypoint mini-css-extract-plugin = *
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/postcss-loader/lib/index.js??postcss!node_modules/less-loader/dist/cjs.js!node_modules/thread-loader/dist/cjs.js!node_modules/vue-loader/lib/index.js??vue-loader-options!node_modules/vue-improve-loader/src/index.js!src/detail/Index.vue?vue&type=style&index=0&lang=less&:
    Entrypoint mini-css-extract-plugin = *
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/postcss-loader/lib/index.js??postcss!node_modules/less-loader/dist/cjs.js!node_modules/thread-loader/dist/cjs.js!node_modules/vue-loader/lib/index.js??vue-loader-options!node_modules/vue-improve-loader/src/index.js!src/home/Index.vue?vue&type=style&index=0&lang=less&:
    Entrypoint mini-css-extract-plugin = *
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/postcss-loader/lib/index.js??postcss!node_modules/less-loader/dist/cjs.js!node_modules/thread-loader/dist/cjs.js!node_modules/vue-loader/lib/index.js??vue-loader-options!node_modules/vue-improve-loader/src/index.js!src/list/Index.vue?vue&type=style&index=0&lang=less&:
    Entrypoint mini-css-extract-plugin = *

**Comment by JuneAndGreen** [comment]
我这边运行是正常的，kbone-template-vue 模板应该不需要考虑 kbone core 的版本兼容问题，miniprogram-render/miniprogram-element/mp-webpack-plugin 均使用最新的包就行，另外 "src\mp\todos\mp\js" 并不是我们这边提供的，尝试删除依赖和构建输出重新构建一下？或者 clone 最新的模板试试: https://github.com/wechat-miniprogram/kbone-template-vue ？

**Comment by ksjhb111** [comment]
Is it unnecessary to change the entry file and webpack? How to configure webpack in the new template? Just NPM INSTALL ,NPM RUN MP this is the only official document available.

**Comment by JuneAndGreen** [comment]
自行搭建构建配置的文档: https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html （除了个别配置不建议修改外，其他可自行调整）

> Is it unnecessary to change the entry file and webpack?

你当然可以将入口文件合并成一个，只要该入口文件在小程序跑时是暴露出 createApp 方法，且会预先创建好 vue 或者 react 需要的容器节点即可：https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html#%E6%96%B0%E5%A2%9E%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6

**Comment by JuneAndGreen** [comment]
如果有其他补充问题，可 reopen 或者重提 issue。kbone-template-vue 如果有其他问题建议到[该模板的仓库上](https://github.com/wechat-miniprogram/kbone-template-vue/issues)提 issue。
