### ISSUE TITLE
自定义 app.js,在引入其他方法的时候会报错，引入方式如下，报错如下

### ISSUE THREAD

**Issue by zmzxn** [Tencent/kbone#266]
![image](https://user-images.githubusercontent.com/23032786/87849130-b584d180-c918-11ea-97c0-2b73584e1982.png)
![image](https://user-images.githubusercontent.com/23032786/87849138-c33a5700-c918-11ea-8acf-c686f38752c6.png)

**Comment by JuneAndGreen** [comment]
参考文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss

![image](https://user-images.githubusercontent.com/7931744/87897059-c3536780-ca7c-11ea-9411-eb01e1de7ad9.png)

app.js 如果要用到 bom 对象，可以自行注入需要的代码。默认这里的 window 和 document 就是一个空对象。

**Comment by zmzxn** [comment]
> 参考文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss
> 
> ![image](https://user-images.githubusercontent.com/7931744/87897059-c3536780-ca7c-11ea-9411-eb01e1de7ad9.png)
> 
> app.js 如果要用到 bom 对象，可以自行注入需要的代码。默认这里的 window 和 document 就是一个空对象。

我现在要引入方法我这个**appEntryInject**需要如何进行配置呢，有点不明白！

**Comment by JuneAndGreen** [comment]
@zmzxn https://wechat-miniprogram.github.io/kbone/docs/config/#generate-appentryinject
可以参考此文档的例子。
