### ISSUE TITLE
reachbottom 事件只能在小程序页面中配置并注册使用吗？

### ISSUE THREAD

**Issue by itamud** [Tencent/kbone#267]
目前只在 `mp-webpack-plugin` 中看到 [reachbottom](https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-reachbottom-%E4%BA%8B%E4%BB%B6) 事件的配置和注册使用

请问下 web 端有现成的 reachbottom 事件 api 可以用吗？还是要根据环境判断 web 端自己写触底触发事件？

**Comment by JuneAndGreen** [comment]
除了 kbone-ui 和 kbone-api 会对小程序部分组件和 sdk api 逆向兼容到 Web 端外，kbone core 主要的工作是原 Web 端接口兼容到小程序端，并不会对 Web 端代码做任何改造调整，所以 reachbottom 目前是只有小程序端才有。

不过 Web 端要用也不难实现，利用 scroll 事件和 scrollTop 就行，下面给一个简单的 demo，**开发者可参考来自己实现**：
```js
    let lastScrollTop = 0;
    let lastScrollTs = +new Date();
    window.addEventListener('scroll', evt => {
        const now = +new Date();
        const scrollTop = document.documentElement.scrollTop || window.pageYOffset || document.body.scrollTop;

        // 触底事件实现
        if (scrollTop > lastScrollTop && now - lastScrollTs < 200) {
            const reachBottom = document.documentElement.scrollHeight - window.pageYOffset - window.innerHeight <= 200;
            if (reachBottom) {
                // 触发 reachbottom 事件
            }
        }

        lastScrollTop = scrollTop;
        lastScrollTs = now;
    });
```

**Comment by itamud** [comment]
> 除了 kbone-ui 和 kbone-api 会对小程序部分组件和 sdk api 逆向兼容到 Web 端外，kbone core 主要的工作是原 Web 端接口兼容到小程序端，并不会对 Web 端代码做任何改造调整，所以 reachbottom 目前是只有小程序端才有。
> 
> 不过 Web 端要用也不难实现，如你所说根据环境判断，然后利用 scroll 事件和 scrollTop 就行，下面给一个简单的 demo，**开发者可参考来自己实现**：
> 
> ```js
>     let lastScrollTop = 0;
>     let lastScrollTs = +new Date();
>     window.addEventListener('scroll', evt => {
>         const now = +new Date();
>         const scrollTop = document.documentElement.scrollTop || window.pageYOffset || document.body.scrollTop;
> 
>         // 触底事件实现
>         if (scrollTop > lastScrollTop && now - lastScrollTs < 200) {
>             const reachBottom = document.documentElement.scrollHeight - window.pageYOffset - window.innerHeight <= 200;
>             if (reachBottom) {
>                 // 触发 reachbottom 事件
>             }
>         }
> 
>         lastScrollTop = scrollTop;
>         lastScrollTs = now;
>     });
> ```

了解了，感谢回答
