### ISSUE TITLE
会支持SharedWorker吗？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#268]
因为后端不太愿意配合，websocket只能同时连接1个，而且也只搞了1个websocket，所以导致多页情况下使用websocket处理太麻烦了

一般web是用SharedWorker解决，所以kbone会支持吗？

**Comment by JuneAndGreen** [comment]
这是个好提议，我看看能否利用小程序的 worker 封装一个出来。

**Comment by xmsz** [comment]
> 这是个好提议，我看看能否利用小程序的 worker 封装一个出来。

可以 ， 不过小程序的woker不能用 小程序的api会比较蛋疼一点

**Comment by JuneAndGreen** [comment]
不使用小程序的 worker 的话，只能实现成伪并行了，这里还是希望尽量做成真正的并行。

**Comment by JuneAndGreen** [comment]
以下版本已提供，文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8-worker-%E5%92%8C-sharedworker

 - miniprogram-render@2.0.11
 - mp-webpack-plugin@1.1.7

因为是基于小程序的 worker 来实现的，所以实现了真正的多线程，但也多了诸多限制，详细可看文档。如果此特性无法满足的话，开发者也可以自己实现 worker 来实现伪并行：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E6%89%A9%E5%B1%95-dom-bom-%E5%AF%B9%E8%B1%A1%E5%92%8C-api
