### ISSUE TITLE
【讨论】kbone如何优化长列表性能

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#269]
自己测试的数据，kbone大概200条记录的时候就会有点吃不消了

然后web端一般用长/虚拟列表的方式解决，但是呢，kbone是反效果，越弄越卡

最后又变成了混合开发，原生的列表2000条都没任何问题

所以，kbone要怎么优化长列表的性能？

**Comment by JuneAndGreen** [comment]
kbone 虽然兼容了很多 Web 特性，不过相对原生开发的缺陷就在于节点数很多的情况下性能会越来越差，所以根据选择确实是需要做一些取舍的。
目前我这边想到的针对长列表的两个也许可行的方案：
1、列表跟部使用 wx-view 创建一个自定义组件，列表每个卡片创建一个自定义组件，尽量减少更新 diff 范围，因为小程序是根据自定义组件的 shadow tree 维度进行 diff 的；
2、在 1 的基础上使用虚拟列表，可参考 recycle-view 的实现。

**Comment by JuneAndGreen** [comment]
合并到 #297
