### ISSUE TITLE
小程序分享朋友圈 onShareTimeline

### ISSUE THREAD

**Issue by Cydmi** [Tencent/kbone#270]
小程序分享朋友圈 onShareTimeline什么时候加入

**Comment by JuneAndGreen** [comment]
前段时间就已支持了：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-onsharetimeline
demo：https://github.com/Tencent/kbone/tree/develop/examples/demo5

**Comment by Cydmi** [comment]
@JuneAndGreen 发现开发工具可以显示分享朋友圈，真机不知道为啥前几天还显示亮的状态可以点击分享朋友圈，最近突然分享朋友圈真机上变灰，无法分享，不知是小程序bug 还是这边问题

**Comment by Cydmi** [comment]
好像加入 `wx.showShareMenu({
		withShareTicket:true,
		menus: ['shareAppMessage', 'shareTimeline']
	})`代码真机才显示不是灰色的。估计是测试阶段原因

**Comment by JuneAndGreen** [comment]
看看是不是shareTimeline配置没配？
