### ISSUE TITLE
打包 web 版本后 app.js 未执行，且触发了 noscript 标签

### ISSUE THREAD

**Issue by itamud** [Tencent/kbone#271]
打包完成后在本地用静态资源服务器托管，app.js 正常执行，页面能够加载，但是部署到线上后 app.js 虽然下载下来了，但是未执行。把项目迁移到纯 vue 的环境就不会有这样的问题，请问可能是什么原因呢？

**Comment by JuneAndGreen** [comment]
看不太懂问题描述。。。这个 app.js 的内容是什么样的？Web 端的构建输出都是“原汁原味”的，kbone 不会做任何调整才对，kbone 只处理构建到小程序端的代码。原始 Web 端构建的 demo 是直接取自 vue 官方的模板。也就是说 demo 中 Web 端的构建配置，你怎么调整都不会影响到小程序端输出，反之亦然。

**Comment by itamud** [comment]
这个不太好上代码。。。我就用 demo 试了下，构建完用静态资源服务器 static-server 托管一切 ok，但是部署到线上后就只加载了入口文件 `index.html` `app.css` `app.js`，页面只显示了 `<noscript></noscirpt>` 标签里的内容，看样子像是禁用了 js。。。但是把代码放到纯的 vue 环境打包部署就没问题，以前没碰到过这种问题，所以请教下

**Comment by JuneAndGreen** [comment]
感觉还是配置/代码有点问题，也可能是服务本身/资源路径不正确，我这边没有出现过也没有具体的例子所以也无法定位，感觉你可以从这些方面着手。你的纯 vue 环境打包也可以直接挪到 kbone 项目里来用的，正如上面提到，所有 demo/模板，kbone 的构建配置和 Web 的构建配置都是分成两份来的，kbone 不会处理任何 Web 端相关的输出，你可以自由地调整 Web 端构建，而且 Web 端构建的问题也基本上不会是出自 kbone 插件的，因为 kbone 插件的功能只是将原本的 Web 端输出代码进行包装处理成小程序代码，只有小程序端会被 kbone 处理。

**Comment by itamud** [comment]
下午查了下 vue-router 的 base 路径漏了。。。所以只加载了入口文件。搬到纯 vue 环境自己模板有全局配置，不是 kbone 的问题，抱歉耽误你时间了
