### ISSUE TITLE
微信小程序video视频组件的部分属性没有支持？

### ISSUE THREAD

**Issue by lanchuanglanyan** [Tencent/kbone#272]
![image](https://user-images.githubusercontent.com/31338597/88140111-ac9b4500-cc23-11ea-981a-a542d72e75f6.png)
我没办法设置上去video组件的一些属性，包括但不仅限于controls、show-play-btn、show-fullscreen-btn等，请问这都怎么设置上去啊?无论是直接设置controls="false"还是controls="{{false}}"都没有办法配置上去？还是因为kbone上还没有支持？我懵了。。

**Comment by JuneAndGreen** [comment]
react 还是 vue？有些框架可能有这个问题：
![image](https://user-images.githubusercontent.com/7931744/88145021-64345500-cc2c-11ea-9faa-47c153436195.png)

将值换成空串就好了：`controls="{{''}}"`

**Comment by JuneAndGreen** [comment]
更优雅的方法：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E6%89%B9%E9%87%8F%E8%AE%BE%E7%BD%AE%E8%8A%82%E7%82%B9%E5%B1%9E%E6%80%A7

下述版本已支持：

- miniprogram-element@2.0.13
- miniprogram-render@2.0.9
