### ISSUE TITLE
希望button可以支持一下share-type和share-mode

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#275]
目前项目唯一需要定制的就是这两个属性，每次都要构建然后覆盖太麻烦了。

希望可以支持一下这两个属性

**Comment by JuneAndGreen** [comment]
这貌似是 qq 小程序的？

**Comment by xmsz** [comment]
> 这貌似是 qq 小程序的？

没错 目前就差了这两个属性 其他都无所谓 这两个太经常用了

**Comment by JuneAndGreen** [comment]
已支持： 

- miniprogram-element@2.0.13
- miniprogram-render@2.0.9

> PS：不过需要知悉的是，后续大概率不会考虑跟进维护其他小程序的更新，毕竟这会让维护成本和包体积膨胀得厉害，我们更希望的是直接支持微信小程序，其他小程序如果他们愿意跟进微信小程序的特性最好，如果不愿意跟进，那如果想做跨各端小程序的框架/库兼容性也会变得很差。

**Comment by xmsz** [comment]
> 已支持：
> 
> * miniprogram-element@2.0.13
> * miniprogram-render@2.0.9
> 
> > PS：不过需要知悉的是，后续大概率不会考虑跟进维护其他小程序的更新，毕竟这会让维护成本和包体积膨胀得厉害，我们更希望的是直接支持微信小程序，其他小程序如果他们愿意跟进微信小程序的特性最好，如果不愿意跟进，那如果想做跨各端小程序的框架/库兼容性也会变得很差。

非常感恩！
