### ISSUE TITLE
关于原生自定义组件编译（自动编译，支持Typscript/jsx）

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#276]
情况
- 目前修改原生自定义组件不会自动刷新，需要修改其他（非自定义组件）文件才行，这样太麻烦
- 不支持typescrpt文件，写的时候回到了原始社会

需要
- 修改原生自定义组件文件时，自动编译
- 支持.ts => .js,  .tsx => .wxml, .scss => .wxss

现在是用gulp去处理，因为这些文件纯粹只是单文件编译。但是现在得开两个构建脚本太麻烦了

希望官方支持一下

**Comment by JuneAndGreen** [comment]
外部内容的 ts 暂时不会考虑支持，kbone 这边确保你传入的像第三方自定义组件、自定义 tabbar 之类的就是可以直接使用的内容，而不是需要二次处理的内容，因为对这些组件处理本身就不是 kbone 核心应该关注的内容，你可以使用其他任意解决方案来将其构建后输入给 kbone，而不是将其直接集成在 kbone 里面去实现。

watch 倒是可以看看能不能搞。

**Comment by JuneAndGreen** [comment]
第三方自定义组件/自定义 tabbar/loading view 目录的 watch 已支持，更新到 mp-webpack-plugin@1.1.4 可体验。

**Comment by xmsz** [comment]
ok，这步自己处理吧
