### ISSUE TITLE
原生自定义组件中global的内容

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#277]
现在global里是
```
{
 $$runtime: {
   document: {},
   window: {}
 }
}
```

这个是有意而为之的吗？

想象中应该是和app原生的一样

**Comment by JuneAndGreen** [comment]
这个global就是小程序原生的global对象。$$runtime里是为了方便控制台里调试而加进去的当前展示页面的window和document对象，开发者可以忽略管里面的内容。

**Comment by xmsz** [comment]
> 这个global就是小程序原生的global对象。$$runtime里是为了方便控制台里调试而加进去的当前展示页面的window和document对象，开发者可以忽略里面的内容。

那我该如何在原生global对象添加其他属性

如果在app.js添加 global.xxx = xxx ， 原生组件会被覆盖，只有$$runtime这个属性，因为app.js里的global实际上是window

**Comment by JuneAndGreen** [comment]
你是需要在业务代码里拿到小程序的 global 对象是吧。默认 webpack 会用 window 设置给 global，如果要访问小程序的 global，webpack 配置上加上这个即可：

![image](https://user-images.githubusercontent.com/7931744/88371650-0ab45d80-cdc7-11ea-9ef4-01e35b977cee.png)

参考文档：https://webpack.js.org/configuration/node/
