### ISSUE TITLE
小程序转发vue router 获得到的路径为 https://test.miniprogram.com/vuepath

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#281]
右上角，转发小程序页面，除了首页，其他页路径都是https://test.miniprogram.com/vuepath

**Comment by JuneAndGreen** [comment]
test.miniprogram.com 来自配置中的 origin 字段：https://wechat-miniprogram.github.io/kbone/docs/config/#origin
然后 vuepath 的话开发者可以自己配置的：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-onshareappmessage

![image](https://user-images.githubusercontent.com/7931744/88874622-1209ba00-d252-11ea-97e0-18e725f7fba4.png)

上面的几种方式任选一种即可，也可以参考 demo5。

如果还是有问题的话，可以重新描述下具体问题场景并提供下可复现 demo，我这边再定位下。

**Comment by TomVista** [comment]
我配置错了.
