### ISSUE TITLE
kbone 一直报警告:VM17:1 window.SVGElement is not supported

### ISSUE THREAD

**Issue by wu253494078** [Tencent/kbone#283]
![image](https://user-images.githubusercontent.com/32081454/89091033-347a0f80-d3d9-11ea-86e1-f3bf3851a0e8.png)
我页面都把所有的svg给删掉了 还是一直有这个警告 请教一下，可能是什么原因呢

**Comment by JuneAndGreen** [comment]
应该是有用到的第三方库调了 window.SVGElement ？可以排查下第三方库，如果确实没有用到 SVGElement 的功能，那应该不影响正常业务的。

小程序受限于自身的能力影响，目前没法较好地兼容 window.SVGElement。
