### ISSUE TITLE
小程序开发模式调整为development后报错

### ISSUE THREAD

**Issue by hadeshe93** [Tencent/kbone#284]
## 背景

kbone 生成的 demo 工程中，看到 `webpack.mp.config.js` 的 `mode` 为 `production`，故在开发模式下调整为 `development`，删掉 `dist` 整个文件夹，重新运行构建，构建过程成功，小程序开发工具预览路径：`pages/home/index`， console 控制台报错：`Failed to mount component: template or render function not defined`，稳定复现，截图如下：

![image](https://user-images.githubusercontent.com/44319041/89155703-ecefb100-d59b-11ea-8098-2bb5857c010d.png)

另外，将 `src/home/Index.vue` 里面的 `import Web from 'reduce-loader!../common/Web.vue'` 去掉就不会报错了。

## 预期

预期应该是 `development` 和 `production` 模式都不报错才对，目前只有 `development` 报错，`production` 不报错。

请问这里是什么原因导致的？以及如何能够解决这种情况？

目前我是完全不使用内联使用 `reduce-loader` 了。

**Comment by hadeshe93** [comment]
ps：没有调整过源码，没有选择 ts 方式开发，直接生成个 demo，调整 `mode` 可立即复现。

**Comment by JuneAndGreen** [comment]
尽量不要使用 development 模式，因为 development 可能会引入一些小程序无法支持的逻辑，比如 eval 调用等，所以 kbone 提供的文档/demo 都是使用 production 模式。

需要调试业务代码的话，可以去掉压缩处理（demo 里通常会有一个 isOptimize 变量）。如果要调试第三方库，可以利用 alias 功能，例如将 react 等库 reslove 到未压缩的入口上。
![image](https://user-images.githubusercontent.com/7931744/89156364-283eaf80-d59d-11ea-99d6-73ec71e67be7.png)

**Comment by JuneAndGreen** [comment]
以下就是我将 demo2 改成使用 development 模式生成的代码：
![image](https://user-images.githubusercontent.com/7931744/89157417-10682b00-d59f-11ea-88be-618799e5d64f.png)

**Comment by JuneAndGreen** [comment]
文档已补充说明：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E9%99%90%E5%88%B6
