### ISSUE TITLE
【编译错误】pages/base.js 未定义

### ISSUE THREAD

**Issue by yanyang1116** [Tencent/kbone#285]
版本：mp-webpack-plugin 1.1.7版本

描述：
‘pages/base.js 未定义‘
打开源代码查看，是 src 文件中，确实没有 base.js。
<img width="962" alt="WechatIMG107" src="https://user-images.githubusercontent.com/16506028/89258381-a57c2a00-d65a-11ea-8983-3e7f038e22d8.png">

**Comment by JuneAndGreen** [comment]
base.js 用的是这个：
![image](https://user-images.githubusercontent.com/7931744/89260119-386a9380-d65e-11ea-959e-1ed9f6aea214.png)

**Comment by JuneAndGreen** [comment]
https://github.com/Tencent/kbone/blob/12ebd307e07981c7009c72352af6dc5abc9f4f4d/packages/mp-webpack-plugin/src/index.js#L261

只要 mp-webpack-plugin 有正常工作，有页面的生成就必然有 base.js 的生成，你那边有没有额外自定义的构建相关的逻辑？还是单纯拿某个 demo 来跑的？

**Comment by yanyang1116** [comment]
可能是有别的文件逻辑，没仔细分析。
不过我回退到  1.1.1 版本，就可以正常工作了。源代码包里，没有 base.js 相应的代码
![image](https://user-images.githubusercontent.com/16506028/89261422-9f894780-d660-11ea-8cae-6705b87eba7a.png)

**Comment by JuneAndGreen** [comment]
base.js 主要是抽取各个页面的公共代码，减少代码包体积用。我这边的模板和 demo 都重新跑过，1.1.7 都是能够正常生成 base.js 的，除非有外部逻辑强行去做一些处理（如目录调整之类的）才有可能导致找不到 base.js。

你可以检查下是否有其他的构建逻辑影响到了。

**Comment by yanyang1116** [comment]
这边，查明是有后续的文件操作。
base.js 是在 1.1.1中新增的，没有移动到需要的位置。
