### ISSUE TITLE
贡献代码是否需要权限？？？

### ISSUE THREAD

**Issue by lubyxu** [Tencent/kbone#286]
贡献代码是否需要权限？？？ 

开发碰到childNodes undefined问题，导致页面渲染不正确。

需要在dealWithLeafAndSimple函数加一个默认值：[]。

**Comment by JuneAndGreen** [comment]
可以通过 pr 的方式来参与开发哈，规范参考：https://wechat-miniprogram.github.io/kbone/docs/guide/develop.html#%E7%89%88%E6%9C%AC%E8%A7%84%E8%8C%83

**Comment by JuneAndGreen** [comment]
另外你说的问题具体是何处？我这边可以看看。

**Comment by lubyxu** [comment]
![image](https://user-images.githubusercontent.com/8433782/89389191-b51d7080-d737-11ea-9930-bbbf982b4c75.png)
这个地方。

**Comment by lubyxu** [comment]
急需修复。。 childNodes undefined的时候，小程序setData 就会有问题，然后，渲染就有问题了。。。

**Comment by JuneAndGreen** [comment]
这里应该是初始就没有 childNodes 字段的，如果改成 `if (childNode.childNodes && childNode.childNodes.length) childNode.childNodes = dealWithLeafAndSimple(childNode.childNodes, onChildNodesUpdate)` 是否也能符合你的预期？

**Comment by lubyxu** [comment]
非常可以~ 还这个好~ 麻烦啦

**Comment by JuneAndGreen** [comment]
已修复：miniprogram-element@2.1.2

**Comment by lubyxu** [comment]
说好的`if (childNode.childNodes &&  childNode.childNodes.length)`呢。。 怎么变成了`if (childNode.childNodes)`这个。。。还是undefined.......

**Comment by JuneAndGreen** [comment]
那我再调整一下，顺便给下你那边具体的案例吧，可能你的问题我想的可能性不是一回事。
