### ISSUE TITLE
 #286 还是有问题

### ISSUE THREAD

**Issue by lubyxu** [Tencent/kbone#287]
2.1.2的版本修改还是有问题。 测试之后只有`childNode.childNodes = dealWithLeafAndSimple(childNode.childNodes, onChildNodesUpdate) || []`这种写法有效果。。。

**Comment by lubyxu** [comment]
@JuneAndGreen #286

**Comment by JuneAndGreen** [comment]
miniprogram-element@2.1.3 改成 `xxx || []` 的方式，顺便可以给下问题用例么，我补下单测。

**Comment by lubyxu** [comment]
用react的时候，当render出现三元运算符的时候。比如 {loading && <Loading />} 就会有问题

**Comment by JuneAndGreen** [comment]
`{loading && } ` 这个是指？可以贴一下稍完整一点的代码片段么？

**Comment by lubyxu** [comment]
比如：加载一个列表

```jsx
const PromiseList = () => {
  const {loading, data} = useRequest(api.get);

  return (
    <div>
       {loading && <div>加载中</div>}
    </div>
  );
};
```
这样就有问题
