### ISSUE TITLE
我这里打不开文档地址了

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#288]
这个地址我（这个地区）打不开，不管是Wifi 还是 移动网

wechat-miniprogram.github.io

```
wechat-miniprogram.github.io 拒绝了我们的连接请求。
```

希望有个国内的镜像地址

**Comment by JuneAndGreen** [comment]
这个是直接用的 github pages，你那边访问 github 或者 github pages 站点正常么？

**Comment by xmsz** [comment]
> 这个是直接用的 github pages，你那边访问 github 或者 github pages 站点正常么？

github可以打开不过很慢 , 翻墙速度倒是很快
pages以前可以现在也被墙了，翻墙也上不去

**Comment by JuneAndGreen** [comment]
无法访问你的时候，可以暂时先使用这个：https://github.com/wechat-miniprogram/wechat-miniprogram.github.io/tree/master/kbone

这是文档的仓库，如果需要访问网页版，直接在这个目录下执行 `npm run dev` 就可以了。

**Comment by xmsz** [comment]
> 无法访问你的时候，可以暂时先使用这个：https://github.com/wechat-miniprogram/wechat-miniprogram.github.io/tree/master/kbone
> 
> 这是文档的仓库，如果需要访问网页版，直接在这个目录下执行 `npm run dev` 就可以了。

嗯，我现在是这么操作，就是有点麻烦。还有就是只能用搜索引擎的快照了

**Comment by JuneAndGreen** [comment]
估计是 github.io 被解析成 127.0.0.1 导致访问不了，现在先提供一份镜像，包含 kbone 完整文档和部分 kbone-ui 文档（暂不包含示例）：
https://developers.weixin.qq.com/miniprogram/kbone/docs/
