### ISSUE TITLE
是否支持输出组件形式，而不是一个页面

### ISSUE THREAD

**Issue by RaindropSaber** [Tencent/kbone#289]

**Comment by JuneAndGreen** [comment]
目前最小粒度是页面，如果按照目前的方案将最小粒度做到组件的话，可能会有：同页面的组件互斥问题、同一小程序内的组件的树管理问题、bom/dom api 的隔离和兼容问题、和原生页面其他部分的耦合问题等等。

事实上如果对标原生 Web 能力的话，最适合用来作为输出组件的接口是 Web components，而小程序的组件系统其实就是基于这个理念设计出来的，所以对于组件这种比较细粒度的话，推荐是原生页面直接嵌入原生的自定义组件比较合适，无需任何桥接逻辑，性能方面肯定更优，而且体积也更小。

kbone 这边目前暂不会考虑将粒度细化到组件层面。
