### ISSUE TITLE
miniprogram-element@2.1.4有点小问题

### ISSUE THREAD

**Issue by lanchuanglanyan** [Tencent/kbone#291]
今天下午编译代码包的时候发现miniprogram-element更新2.1.4了，然后编译出了一点问题，进行导航栏跳转的时候提示我'type' of null，看了一天没法解决，npm安装之2.1.3也不行，编译出来还是2.1.4，有没有办法编译时使用指定版本？或者这个问题能解决也行，求大佬帮忙
miniprogram-element@2.1.4
![image](https://user-images.githubusercontent.com/31338597/89542320-1a558c80-d832-11ea-8463-3742b8fec705.png)
我的代码
![image](https://user-images.githubusercontent.com/31338597/89542396-36592e00-d832-11ea-8673-2d2461abce89.png)
执行出错
![image](https://user-images.githubusercontent.com/31338597/89542431-3f49ff80-d832-11ea-84b1-7da6cc7eb077.png)
代码大概位置
![image](https://user-images.githubusercontent.com/31338597/89542457-48d36780-d832-11ea-8fc1-526b450c5566.png)
求大佬看下，上线了，我要死了

**Comment by lanchuanglanyan** [comment]
@JuneAndGreen 求大佬帮助，要不然编译的时候可以指定依赖包版本(或者使用安装的依赖包)，或者大佬帮忙看下问题，我要疯了

**Comment by lanchuanglanyan** [comment]
我现在临时那半个月前的依赖包1.5.0先用着了，老版本是没有这个问题的，有办法编译的时候不是用最新的而是用指定版本或者npm安装的模块包吗？

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/89602679-de561200-d899-11ea-8a14-ed35988ef9d6.png)

指定版本可以用这个配置。type of null 问题我看看

**Comment by JuneAndGreen** [comment]
更新到 miniprogram-element@2.1.5 试试。

**Comment by lanchuanglanyan** [comment]
好的
