### ISSUE TITLE
kbone为什么不能正常支持原生小程序的分享功能呢？

### ISSUE THREAD

**Issue by weidashuai** [Tencent/kbone#292]
是这样场景。我们自己团队开发了一个小程序插件，然后想在其他小程序中接入这个插件，插件是用原生小程序开发的，其中包含了分享功能。然后，使用插件的小程序是使用kbone开发的，发现使用kbone开发的小程序接入插件之后，不支持分享，页面打不开。感觉让人无语啊。。。

**Comment by JuneAndGreen** [comment]
一直都支持的啊：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-onshareappmessage

参考 demo：https://github.com/Tencent/kbone/tree/develop/examples/demo5

**Comment by JuneAndGreen** [comment]
如果是非 kbone 页面分享 kbone 页面，需要自己拼装路由：
![image](https://user-images.githubusercontent.com/7931744/89766588-fa241700-db2a-11ea-895a-17162bcdb3da.png)

文档：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91

**Comment by weidashuai** [comment]
> kbone 页面分享 kbone 页面，kbone 页面分享非 kbone 页面，按照上面文档就像。但是如果是非 kbone 页面分享 kbone 页面，需要自己拼装路由：
> ![image](https://user-images.githubusercontent.com/7931744/89766588-fa241700-db2a-11ea-895a-17162bcdb3da.png)
> 
> 文档：https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91

你好。我的情况现在应该是非kbone分享kbone页面，不是你说的kbone页面分享kbone页面，kbone页面分享非kbone页面。

**Comment by JuneAndGreen** [comment]
那按照截图中的 qa 来拼装 url 就可以。在路由后面带上 type 和 targeturl 参数。不带的话，默认进入页面的是 / 。
