### ISSUE TITLE
scroll-view 内置组件改为 v2.x 渲染模式后,性能下降很明显

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#293]
使用scroll-view的onscroll 事件,改变头部元素透明度,有明显卡顿,v1.0渲染没有问题

```
<wx-scroll-view @scroll='scroll'>
<header :style='headerStyle' />
</wx-scroll-view>

scroll(e){
this.headerStyle={
 opacity: getOpacity(e) ;
}
}
```

**Comment by JuneAndGreen** [comment]
使用的基础库版本是？

**Comment by TomVista** [comment]
@JuneAndGreen 2.11.3 和2.8.2

**Comment by TomVista** [comment]
两个不同的小程序,都有这个问题.

**Comment by JuneAndGreen** [comment]
用的 miniprogram-element/miniprogram-render 是哪个版本呢？最近更新了小范围更新优化，只是更新 style 的话应该不会像以前那样全量更新的。

**Comment by TomVista** [comment]
2.1.7/2.1.1 都是最新的,然后全部替换为了1.x的最后一个版本

**Comment by JuneAndGreen** [comment]
这不是性能问题，看来是子组件的 setData 中断了滚动，才让表现看起来卡顿。

**Comment by JuneAndGreen** [comment]
可以先用这个方法来兼容一下：把 scroll-view 的内容用 wx-view 包一下，比如你给的例子中，改成这样 `<wx-scroll-view @scroll='scroll'><wx-view><header :style='headerStyle' /></wx-view></wx-scroll-view>`

**Comment by JuneAndGreen** [comment]
已兼容，更新到 miniprogram-element@2.1.8 即可。
