### ISSUE TITLE
mp-webpack-plugin 1.1.8 *号选择器改[class^="h5-"] 在开发者工具上编译不过去,

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#296]

**Comment by JuneAndGreen** [comment]
报错信息是什么样的呢？

**Comment by TomVista** [comment]
![image](https://user-images.githubusercontent.com/42435611/90741314-bcc94180-e301-11ea-9c29-db06060995d9.png)
@JuneAndGreen

**Comment by TomVista** [comment]
![image](https://user-images.githubusercontent.com/42435611/90741789-dcf90080-e301-11ea-952e-881b11649cc9.png)
开发者工具 版本

**Comment by JuneAndGreen** [comment]
看来 wcsc 还不支持 >[class^="h5-"] 的写法。。。我先加个配置，默认是旧的方式好了

**Comment by TomVista** [comment]
🐶

**Comment by JuneAndGreen** [comment]
更新到 mp-webpack-plugin@1.1.9，默认用回旧实现，可以自由选择采用哪种实现：

https://wechat-miniprogram.github.io/kbone/docs/config/#optimization-wxssuniversalselector
![image](https://user-images.githubusercontent.com/7931744/90748992-7544b480-e305-11ea-876e-aa3bfa310d89.png)
