### ISSUE TITLE
fundebug使用vue模式进行插件使用，不行

### ISSUE THREAD

**Issue by lanchuanglanyan** [Tencent/kbone#299]
求大佬帮忙，或者有没有kbone能用的线上bug监控工具||插件？
![image](https://user-images.githubusercontent.com/31338597/91022106-4725e400-e627-11ea-9859-a7ac2ec11ffa.png)
![image](https://user-images.githubusercontent.com/31338597/91022151-55740000-e627-11ea-9647-3328657e4d12.png)
因为使用的vue+axios的，所以就是用的vue版本，微信小程序版本无法查到axios：500等问题，数据资源监控也不行，所以使用vue版本，接过来发现并不能使用，求大佬帮忙啊

**Comment by lanchuanglanyan** [comment]
@JuneAndGreen 求大佬

**Comment by JuneAndGreen** [comment]
要去除报错不难，在配置 generate.globalVars 里补一项 `['scripts', 'document.scripts = [document.createElement(\'script\')]']` 就可以：

![image](https://user-images.githubusercontent.com/7931744/91250996-f29c7900-e78c-11ea-8f36-971236f7b502.png)

或者你也可以使用这个：https://github.com/Tencent/kbone/tree/develop/packages/file-wrapper-loader ，在 import fundebug 之前给 document.scripts 注入上内容。

但是这里不敢保证 fundebug 就一定能正常运行，因为简单看了下里面的代码，是需要操作 script 标签的，这个受限于小程序环境无法拿到，所以如果 fundebug 最终需要依赖到 script 的一些特性的话，就很难了。当然，kbone 这里是有提供 window 的 error 事件的，如果可以自己手动调接口上报，也是可以的。
