### ISSUE TITLE
textarea autofocus属性小程序原生用的是auto-focus,kbone用的是autofocus,需要统一一下.

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#300]
miniprogram-render 2.1.1

**Comment by JuneAndGreen** [comment]
textarea 这种不带 wx- 前缀的组件，都是尽量对齐 Web 端，以确保在 Web 端不用再而外多补一个 autofocus：

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/textarea
