### ISSUE TITLE
react wx-swiper onChange 不触发

### ISSUE THREAD

**Issue by wulunyi** [Tencent/kbone#302]
使用 React 编写页面使用 wx-swiper 绑定 onChange 事件不触发
```javascript
export default class Template extends Component {
    state = {
        list: [1,2,3]
    }

    render() {
        return (
            <wx-swiper 
                autoplay 
                className="swiper"
                onChange={(ev) => {
                    // 不会执行
                    console.log(ev);
                }}
            >
                {
                    this.state.list.map((item, index) => (
                        <wx-swiper-item key={index}>
                            hello
                        </wx-swiper-item>
                    ))
                }
            </wx-swiper>
        );
    }
}
````

通过 addEventListener 可以捕获

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/92346359-13ef5480-f0ff-11ea-8f2c-2e93fe38abcc.png)

https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E6%89%B9%E9%87%8F%E8%AE%BE%E7%BD%AE%E4%BA%8B%E4%BB%B6%E7%9B%91%E5%90%AC%E5%99%A8

原因在于 react 它对事件做了拦截，swiper 不是 Web 标准的表单组件，所以无法通过 jsx 的方式监听到 change 事件。这个事件相当于普通节点的自定义事件，所以通过 addEventListener 可以正常监听到。这里有两种做法，开发者自己使用 addEventListener/removeEventListener 来处理，或者使用上述链接中提供的批量监听事件的方式绕过 react 的检测。
