### ISSUE TITLE
[BUG]使用小程序自定义组件时如果存在属性名为name的props，可能导致该自定义组件不渲染。

### ISSUE THREAD

**Issue by izyh** [Tencent/kbone#303]
【bug描述】
以demo10为例，将其中某一个自定义组件，如CompA，增加一个prop name，然后调用该组件时正常为name传入值，可以发现整个CompA不会渲染出来，把prop name改成其他属性名，可以正常渲染。
【复现步骤】
如上bug描述。
【期待结果】
对于存在 prop 为 name 的自定义组件也能正常渲染。

**Comment by izyh** [comment]
经过分析源码发现该bug和kbone实现对小程序第三方组件的支持的方案有关，同样以demo10为例，自定义组件最终会被 mp-webpack-plugin 编译成 custom-components 组件，比如 comp-a 组件被编译到 wxml 后如下：
```
<comp-a wx:if="{{name === 'comp-a'}}" id="{{id}}" class="{{class}}" style="{{style}}" prefix="{{prefix}}" suffix="{{suffix}}" bindsomeevent="onsomeevent"><slot/></comp-a>
```
可以看到组件是否渲染是通过`wx:if`控制的，判断的条件是`name === 'comp-a'`，我们看到 custom-components 组件的 index.js，发现对`name`的定义如下：
```js
    properties: {
        name: {
            type: String,
            value: '',
        },
    },
```
这里的`name`是作为 custom-components 组件的 `properties` 存在的，而自定义组件的 `props` 最终会变成 custom-components 组件`data`，如果`props`中也存在`name`，就会造成模版渲染时的混淆，从而导致`name === 'comp-a'`为`false`，组件不会渲染。

**Comment by JuneAndGreen** [comment]
已修复，相关更新：

 - miniprogram-element@2.1.13
 - mp-webpack-plugin@1.1.12

**Comment by izyh** [comment]
这方案也可以，一般自定义组件也不会出现 kboneCustomComponentName 这种 prop
