### ISSUE TITLE
【bug】detached销毁导致的error

### ISSUE THREAD

**Issue by qianjunsteve** [Tencent/kbone#304]
【复现】打开一个新页面，快速关掉页面报错：TypeError: Cannot read property '$$setCookie' of null
看了下逻辑是因为关闭按钮后先调用了detached，将this.document = null; 后面执行到请求回调this.$_window.document.$$setCookie(setCookie)导致的问题；
【希望】1、修复该问题；2、具体原因是啥？deatched后页面的进程不是已经杀死了吗？

**Comment by JuneAndGreen** [comment]
小程序的架构里，页面 js 代码是在一个进程里的。这里应该是请求返回后 window/document 已经销毁了导致。本质上来说业务代码里 page unload 时也应该 abort 掉请求的。对于 set-cookie 我这边也补充一下 document 存在判断。

**Comment by JuneAndGreen** [comment]
已兼容到：miniprogram-render@2.1.4，可以试试
