### ISSUE TITLE
React componentDidMount 访问 ref.current.$$wxComponent 为 undefined 

### ISSUE THREAD

**Issue by wulunyi** [Tencent/kbone#305]
```jsx
import { createRef, Component } from 'react';

class A extends Component {
    ref = createRef(null);
    componentDidMount() {
        // 这拿不到
        console.log(this.ref.current.$$wxComponent);

        // setTimeout 后能拿到
        setTimeout(() => {
            console.log(this.ref.current.$$wxComponent);
        }, 0)
    }
    render() {
         return (<wx-view ref={this.ref}>{this.props.children}</wx-view>)
    }
}
```

**Comment by JuneAndGreen** [comment]
还没渲染完成的节点是没有 $$wxComponent 的，这里不是立即 setData，而会等同步流结束来做一次 setData（为了减少碎片化 setData 的次数，提高效率，目前是采用 Promise.resolve().then 来实现的），在处理 setData 的过程才会挂上实例：https://github.com/Tencent/kbone/blob/develop/packages/miniprogram-element/src/util/tool.js#L53

这里你加个 setTimeout 0 可以拿到就是以上原因。或许你也可以尝试下这个接口，强制进行 setData，前提是如果在业务层面真的有必要的话：https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-forcerender

**Comment by wulunyi** [comment]
收到
