### ISSUE TITLE
dom diff检查逻辑是否可以优化？

### ISSUE THREAD

**Issue by qianjunsteve** [Tencent/kbone#307]
因为domSubTreeLevel的逻辑。dom tree是由多个自定义组件构成，这样理论上自定义组件应该实现数据自治。但是目前的逻辑是：如果更改了顶层dom的属性，还是会对子级别的自定义组件触发$$childNodesUpdate，但是很多时候子组件是不需要更新了。带来了整树检查的时间成本。建议通过element.js中的trigger进行优化，可以对性能带来提升

**Comment by JuneAndGreen** [comment]
嗯，可以考虑的，后面我看看这里的优化空间。

**Comment by qianjunsteve** [comment]
赞 期待
