### ISSUE TITLE
使用omi模板不支持小程序内置组件

### ISSUE THREAD

**Issue by apimall** [Tencent/kbone#309]
使用omi模板创建的项目，如果使用了类似wx-scroll-view等方式引用小程序内置组件，无效。wx-scroll-view会被编译为element，而非scroll-view。而使用vue项目模板则可以。该如何解决？

**Comment by JuneAndGreen** [comment]
可能模板的依赖有点旧，尝试更新一下 mp-webpack-plugin/miniprogram-element/miniprogram-render 的依赖到最新试试呢？

**Comment by apimall** [comment]
> 
> 
> 可能模板的依赖有点旧，尝试更新一下 mp-webpack-plugin/miniprogram-element/miniprogram-render 的依赖到最新试试呢？

依赖已经是最新的。mp-webpack-plugin版本为1.1.13，miniprogram-element版本为2.1.13，miniprogram-render版本为2.1.4。

**Comment by apimall** [comment]
你们自己写个Case测试一下吧，这是个BUG。

**Comment by dntzhang** [comment]
@apimall 我来看下

**Comment by apimall** [comment]
> 
> 
> @apimall 我来看下

运行小程序的时候，报了一个警告：“value "" is not supported for wx-component's behavior”
应该是omi在执行时，把kbone的element中的behavior给抹掉了，导致kbone无法识别组件，只能渲染为默认的element。

**Comment by dntzhang** [comment]
多谢 @JuneAndGreen 提示，多谢 @apimall 反馈，更新 omio 到 2.8.3 就好了。 https://github.com/omijs/template-kbone/commit/26ea9b3648d15cb602ba9b6e4809a7debf8148e3
