### ISSUE TITLE
babel 配置

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#310]
因为奇奇怪怪的原因新版小程序开发者工具和windows 小程序,跑不动含有js新特性的kbone项目....
比如:promise async/await

下面是解决办法:
```
// build/webpack.mp.config.js
//去掉babel
{
        test: /\.js$/,
        use: [
          'thread-loader',
         // babel-loader 去掉
        ],
        include: [path.resolve(__dirname, '../src'), path.resolve(__dirname, '../node_modules/vue-auto-routing')],
      },
```

```
// build/miniprogram.config.js
// 更换编译模式

projectConfig: {
    projectname: '***',
    appid: '***', 
    setting: {
      es6: false,
      enhance: true,
      babelSetting: {
        ignore: null,
        disablePlugins: [],
        outputPath: ''
      },
    }
  },

```

* 不再支持vue路由懒加载

**Comment by JuneAndGreen** [comment]
应该是被编了两次吧，默认生成的 project.config.json 里会有一个 babelSetting.ignore ，表示那些目录不需要再被工具的 babel 转换，你看看你的代码里有没有这个配置？或者已经过了 babel 的 js 文件有没有命中这个 ignore 而被忽略掉呢？

**Comment by TomVista** [comment]
babel 之后的代码,被 ignore忽略掉,然后在开发工具上走不通,真机是没问题的.
我感觉是开发工具更新了编译机制的原因
@JuneAndGreen

**Comment by TomVista** [comment]
没人看,暂时关掉了.有类似问题可以@我.

**Comment by JuneAndGreen** [comment]
可以给个简单的 demo 么？我跟工具大佬反馈下。

**Comment by TomVista** [comment]
## 测试代码
https://github.com/TomVista/kboneDemo7

就是kbone/exp/demo7
```
 // src/page1/App.vue

 async mounted(){
    console.log('mounted start')
    await new Promise((resolve,reject)=>{
      setTimeout(() => {
        resolve();
      }, 1000);
    })
    console.log('mounted end')
  },
```
https://github.com/TomVista/kbone-cliDemo

kbone-cli 生成的项目
```
// src/App.vue
 async mounted() {
    console.log('mounted start')
    await new Promise((resolve, reject) => {
      setTimeout(() => {
        console.log('i m mounted')
        resolve()
      }, 1000)
    })
    console.log('mounted end')
  }
```

## 主要表现 在新版开发工具 (1.03.2006090 之后发布的版本,不包含1.03.2006090), windows小程序上
* promise async/await 不走resovle
* 疑似js特性不支持
 
## 其他
* kboneDemo7 的问题只表现在windows小程序

**Comment by TomVista** [comment]
## 一些图片
![image](https://user-images.githubusercontent.com/42435611/93756653-ff02dd00-fc37-11ea-9458-ed30c4ac2bb9.png)
![41](https://user-images.githubusercontent.com/42435611/93756665-032efa80-fc38-11ea-8d6d-83e5e4f61352.gif)
![42](https://user-images.githubusercontent.com/42435611/93756672-04f8be00-fc38-11ea-8830-5c4b2f8b8517.gif)

**Comment by TomVista** [comment]
需要其他请@我

**Comment by JuneAndGreen** [comment]
在工具上看来并不会报错，是只有 windows 版 pc 微信预览里才有问题么？

**Comment by TomVista** [comment]
我这里 promise 不走resovle，vue路由懒加载，不进路由

**Comment by TomVista** [comment]
开发者工具版本 1.03.2009140

**Comment by JuneAndGreen** [comment]
工具那边已确定，是新版的 bug，会跟进修复到下一个 nighlty 版本中。另外看到社区那边有帖子（https://developers.weixin.qq.com/community/develop/doc/000ce4de468dd0aa69fa057645b400），这边就交由工具团队继续跟进，我这边先 close 了。
