### ISSUE TITLE
kbone编译后的代码可以在企业微信里正常运行吗？

### ISSUE THREAD

**Issue by qianjunsteve** [Tencent/kbone#311]
RT，谢谢

**Comment by JuneAndGreen** [comment]
基本是可以的，不过会有些细节不同，另外企业微信目前的基础库版本相对旧一点。详情可参考文档：https://developers.weixin.qq.com/miniprogram/dev/dev_wxwork/

企业微信小程序和微信小程序可以认为是同源的，底层原理差不多，所以基本都是可以直接跑的。
