### ISSUE TITLE
kbone构建的小程序在企业微信报错

### ISSUE THREAD

**Issue by lwy21** [Tencent/kbone#312]
kbone构建的小程序在企业微信报如下错。是因为需要将kbone的npm打包引入吗？另外，企业微信体验版预览是正常的。
![IMG_1601431632222_b2ad1df3-ebcf-4f53-9463-b26e69b33d8c](https://user-images.githubusercontent.com/24711526/94637477-3d6c5c00-030a-11eb-8762-1ea5644cdc1b.jpg)

**Comment by JuneAndGreen** [comment]
看报错是你输出的代码里有 Function 构造器的使用。小程序环境是屏蔽了 Function 构造器和 eval 等动态执行 js 的方式的，你可以尝试去掉相关逻辑试试。
