### ISSUE TITLE
react下2个bug

### ISSUE THREAD

**Issue by Thyiad** [Tencent/kbone#314]
### className

写了一个组件，其中一个prop名叫className，在小程序端，这个属性死活为空，换个名字就好了，比如clsName

### finally
promise在ios下不能写finnally，否则直接白屏。。。
比如： Promise.resolve(1).then(res=>console.log(res)).finnally(()=>{// 这里不会进来，整个小程序直接白屏})

**Comment by yanyang1116** [comment]
顶！

**Comment by JuneAndGreen** [comment]
第二个问题：你有没有自己引进 promise 的 polyfill？还是直接用小程序提供的 promise？

**Comment by Thyiad** [comment]
@JuneAndGreen 没有引入polyfill呢

**Comment by JuneAndGreen** [comment]
@Thyiad  第二个问题应该是基础库那边的问题，已经提了 bug 单，应该近期版本会修复，待基础库支持即可，我这边就不再继续跟进了。

第一个问题方便给个 demo 么？按我理解 className 应该是 react 的保留属性才对。

**Comment by Thyiad** [comment]
@JuneAndGreen 任意组件，只要props定义了className就行，比如：
TestComp:
```
import React, { FC } from 'react'

interface TestProps {
    className: string
}

const TestComp: FC<TestProps> = ({ className }: TestProps) => {
    console.log(`test---当前环境：${process.env.isMp ? '小程序' : 'h5'}`)
    console.log(`test---className: ${className}`)

    return <div>啦啦啦</div>
}

export default TestComp
```
引用：
```
<TestComp className="abc"/>
```
最后在h5和小程序端的打印日志分别为：
h5:
![image](https://user-images.githubusercontent.com/3324812/96531519-686c1f00-12bc-11eb-8f8a-1fa5a777eee3.png)

mp:
![image](https://user-images.githubusercontent.com/3324812/96531546-7752d180-12bc-11eb-9192-df634f841a2a.png)

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/96842208-51c1f580-147f-11eb-9893-9ad27d1bd426.png)

我这边在工具和真机都是这样的输出，不过我这边是将你给的 TestComp 代码改成 jsx 嵌入到 demo24 来跑的，看起来并不是 kbone 底层没处理。你看看是不是你那边项目编译构建过程有一些特殊逻辑处理？

**Comment by Thyiad** [comment]
嗯，确实很奇怪，看了一下配置，暂时找不到原因了。。
