### ISSUE TITLE
在 vue 组件里用 wx.createSelectorQuery().selectAll('#canvas').node().exec()获取不到 template 中的 canvas 实例

### ISSUE THREAD

**Issue by tianqingfish** [Tencent/kbone#315]
返回的 res 是一个空数组

我看文档中进阶使用中，有提到用 window.$$createSelectorQuery 这个扩充的 api，但是会显示 t.$$createSelectorQuery.selectAll is not function。

**Comment by tianqingfish** [comment]
有个需求是想通过 lottie 来做动画，一开始的想法是用 vue-lottie，发现不会触发 animCreated 事件。
后来想用官方出的 lottie-miniprogram，看官方案例的时候，发现获取不到 template 中的 canvas，不太清楚这是为什么，求解惑～感谢🙏

**Comment by tianqingfish** [comment]
示例代码：

template:
<canvas id="canvas" type="2d"></canvas>

export default {
  name: 'test',
  created() {
    wx.createSelectorQuery().selectAll('#cvs1').node((res) => {
      console.log(res)
    }).exec()
  }
}

自己也查阅了网上的一些说法，用 wx.createSelectorQuery().in(this) 的形式，也不行，这样就直接不进入 node 的回调函数了

**Comment by JuneAndGreen** [comment]
需要调 .in(this)，这个 this 是小程序组件的实例，不是 vue 的实例，因为这个是小程序的方法，可以通过 domNode.$$wxComponent 获取到对应的小程序组件的实例。不过有一个更简便的方法可以拿到 context 对象：

```js
document.getElementById('#canvas').$$prepare().then(domNode => {
    const ctx = domNode.getContext('2d') // 注意，这种用法需要设置 canvas 节点的 type 属性，相关文档：https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html
    
    // do something
})
```

> PS：相关文档：https://wechat-miniprogram.github.io/kbone/docs/domextend/#canvas-prepare，demo 可参考 demo3。

**Comment by tianqingfish** [comment]
> 需要调 .in(this)，这个 this 是小程序组件的实例，不是 vue 的实例，因为这个是小程序的方法，可以通过 domNode.$$wxComponent 获取到对应的小程序组件的实例。不过有一个更简便的方法可以拿到 context 对象：
> 
> ```js
> document.getElementById('#canvas').$$prepare().then(domNode => {
>     const ctx = domNode.getContext('2d') // 注意，这种用法需要设置 canvas 节点的 type 属性，相关文档：https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html
>     
>     // do something
> })
> ```
> 
> > PS：相关文档：https://wechat-miniprogram.github.io/kbone/docs/domextend/#canvas-prepare ，demo 可参考 demo3。

document.getElementById('#canvas').$$wxComponent() 和 document.getElementById('#canvas').$$prepare() 这个会报 Cannot read property '$$prepare' 和 '$$wxComponent' 的错误

**Comment by tianqingfish** [comment]
想问下，如果想使用 lottie 动画的话，作者有啥好的建议吗？

**Comment by JuneAndGreen** [comment]
document.getElementById('#canvas')  这个是我举的例子，id 改成你给 dom 节点设置的 id。$$wxComponent 不是方法，是属性，具体可参考文档或 demo3。
