### ISSUE TITLE
kbone小程序中vue图片懒加载v-lazy无效

### ISSUE THREAD

**Issue by wu253494078** [Tencent/kbone#317]
main.mp.js里面定义了VueLazyLoad 使用v-lazy没有实现懒加载的效果 图片一直是默认显示的加载图片
![image](https://user-images.githubusercontent.com/32081454/96685589-ea894000-13af-11eb-9b86-67ad090ca92e.png)

**Comment by JuneAndGreen** [comment]
给一下完整可运行的 demo ？

**Comment by wu253494078** [comment]
换一个说法。就是vue-lazyload源码里面计算懒加载的距离是用的getBoundingClientRect,在kbone里面是不支持的，要用$$getBoundingClientRect，这样的话怎么去解决呀。（代码是之前的vue项目直接拿过来的）
![image](https://user-images.githubusercontent.com/32081454/96721117-45d22700-13de-11eb-9679-f25fc3ba29e4.png)

**Comment by JuneAndGreen** [comment]
getBoundingClientRect 这个目前无法兼容成同步接口，所以先提供了异步的 $$getBoundingClientRect 接口。

这个是受限于小程序自身的能力，所以目前 kbone 底层是没法解决的，只能修改业务引用的 vue-lazyload 代码或者寄望于小程序能提供同步接口了。

或者还可以尝试一下：使用小程序自身的图片懒加载能力？比如 <img :lazy-load="true"></img>，它会转成利用小程序 image 组件的 lazy-load 属性，参考文档：https://developers.weixin.qq.com/miniprogram/dev/component/image.html

**Comment by wu253494078** [comment]
好的 谢谢~
