### ISSUE TITLE
富文本解析报错

### ISSUE THREAD

**Issue by wu253494078** [Tencent/kbone#318]
后台返回的富文本如果包含< >使用v-html或者设置innerHTML时会报错，详情看图片，可不可以优化一下
![image](https://user-images.githubusercontent.com/32081454/97411510-54b75d00-193b-11eb-8be9-43ecafbaf641.png)
![image](https://user-images.githubusercontent.com/32081454/97411552-613bb580-193b-11eb-8326-8e2f5dffd65c.png)

**Comment by wu253494078** [comment]
富文本内容是<p>< 180测试富文本<img src="http://img.wifenxiao.com/16/79/6/2020-10/5f8184cd49ef7.jpg"/></p>

**Comment by JuneAndGreen** [comment]
你这个不是标准的富文本格式啊。

**Comment by wu253494078** [comment]
是的呢 因为有的用户（比如跳伞项目）会设置 <180斤 <190斤 这种格式的

**Comment by JuneAndGreen** [comment]
> 是的呢 因为有的用户（比如跳伞项目）会设置 <180斤 <190斤 这种格式的

像 <180斤 这种，应该要转成 &lt; 这样的实体字符后再拼到富文本吧，不然再多一个 >，有自动矫错能力也不一定能识别的。

**Comment by wu253494078** [comment]
我转出实体字符在拼到富文本还是不行哦 在kbone编译后还是会变成 < 。这个等你们后期优化了，谢谢~

**Comment by JuneAndGreen** [comment]
建议不要依赖自动纠错，浏览器也是经历了各种 html 版本为了向前兼容才是现在这个样子，依赖自动纠错会引入难以预期的问题，最好业务端就做好实体字符的处理，一方面可以防止注入，一方面也可以防止难以预料的渲染问题。
