### ISSUE TITLE
wx-view-scroll 组件如何绑定 bindscrolltolower

### ISSUE THREAD

**Issue by yanyang1116** [Tencent/kbone#319]
请问：React 中，wx-view-scroll 组件如何绑定 bindscrolltolower

<wx-view-scroll />

**Comment by JuneAndGreen** [comment]
自定义事件被 react 屏蔽了，所以不能直接用 onXXX 的方式，目前有两个方法：
1、直接走原生的 dom 方法，走 addEventListener/removeEventListener
2、走 kbone 提供的特殊属性：kbone-event-map，可参考 demo16 中的 picker-view 的事件监听，具体文档戳[这里](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E6%89%B9%E9%87%8F%E8%AE%BE%E7%BD%AE%E4%BA%8B%E4%BB%B6%E7%9B%91%E5%90%AC%E5%99%A8)。
