### ISSUE TITLE
rem的配置和兼容方式有点太麻烦了

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#320]
现在要支持rem需要
1. 在配置文件中设置`global.rem`，这一步倒是没啥
2. 在每个页面设置
```
window.onload = function() {
    if (process.env.isMiniprogram) {
        // 小程序
        document.documentElement.style.fontSize = wx.getSystemInfoSync().screenWidth / 16 + 'px'
    }
}
```

这一步就比较不优雅。

首先
如果是web端，或者其他小程序平台，例如QQ，就根本不需要这一步。
只有在微信里需要，那就真的属于「多此一举」的操作

其次
每个页面都要写这种胶水代码，非常的麻烦

最后
如果我不设置rem，或者设置了但没有写兼容代码，那么微信最后的表现就是比其他平台的实际px大了2倍
这个是最气人了，就是不知道为什么要这么搞，搞了还跟以前表现差那么多，然后就变成要额外做更多事。 

-----

所以，我觉得太麻烦了，有没有简单一点的设置方法

例如

1. 可以不设置rem，保持和其他平台一样的表现。
这个没有测试，不知道是否可行

2. 在配置环节直接可以配置基准值，在运行阶段自动注入代码
例如我在配置的时候和postcss-pxtorem一样，配置一个      `rootValue: 75`。运行时则自动计算这个基准值的实际root-font-size
这个基本就能解决问题了，配置的时候也没那么繁琐

3. 可修改page的模板页面，或者可以自己编写一个页面插件
例如我写了一个插件，插件在每个页面的某个生命周期执行某些操作。这样的好处就是扩展性比较强

**Comment by JuneAndGreen** [comment]
```js
window.onload = function() {
    if (process.env.isMiniprogram) {
        // 小程序
        document.documentElement.style.fontSize = wx.getSystemInfoSync().screenWidth / 16 + 'px'
    }
}
```

这段代码写到一个公共的 js，每个地方 require 一下就可以吧？

**Comment by xmsz** [comment]
> ```js
> window.onload = function() {
>     if (process.env.isMiniprogram) {
>         // 小程序
>         document.documentElement.style.fontSize = wx.getSystemInfoSync().screenWidth / 16 + 'px'
>     }
> }
> ```
> 
> 这段代码写到一个公共的 js，每个地方 require 一下就可以吧？

强迫症太不喜欢了，就为了兼容微信小程序需要额外引用一个文件。还是希望这种需求可以不和业务代码一起，在构建阶段处理比较合适

**Comment by JuneAndGreen** [comment]
这个和引用 polyfill 之类是一样的呀，只需要在页面入口开头 require 一下就行。而且如果只有小程序需要的代码，基本上可以这么写：

```js
if (process.env.isMiniprogram) {
  window.onload = function() { /**/ }
}
```

webpack 构建时在非小程序端会去除的。如果实在不想 require，加个脚本或者 webpack 插件 prepend 一下到每个入口文件也行。

**Comment by xmsz** [comment]
> 这个和引用 polyfill 之类是一样的呀，只需要在页面入口开头 require 一下就行。而且如果只有小程序需要的代码，基本上可以这么写：
> 
> ```js
> if (process.env.isMiniprogram) {
>   window.onload = function() { /**/ }
> }
> ```
> 
> webpack 构建时在非小程序端会去除的。如果实在不想 require，加个脚本或者 webpack 插件 prepend 一下到每个入口文件也行。

没错，就是已经都用了构建工具了，就不想手动加了。然后希望可以集成在kbone里。
自己写的话，组里其他同学不同意觉得这个不应该加到通用里

**Comment by JuneAndGreen** [comment]
这不合理，因为不是每个应用配的 fontsize 都是要用我提供的范例。rem 说到底是根据 fontsize 来算的，而 fontsize 必须运行时计算，开发者可以用任意方式来计算设置 fontsize。而且这就是一个应用的前置代码，就跟 reset.css、部分 polyfill 一样的，属于业务本身的一部分，另外 kbone 也没法集成：1、没法动态执行 eval/new Function 来嵌入运行时代码，2、rem 是走 page-meta 组件实现的，`document.documentElement.style.fontSize` 的设置本身就是 page-meta 组件的一个快捷设置方式了，让开发者自己来改页面 wxml/js 反而更复杂更容易出现问题。

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/98325131-097f0780-2029-11eb-8344-0d926189df64.png)

mp-webpack-plugin@1.1.16 补了动态计算的默认值，和我提供的范例一致。如果需要其他的计算值，那就仍然需要自己计算了。
