### ISSUE TITLE
kbone默认babel配置生成的代码,不支持电脑版微信

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#321]
这个问题在#310 中提到过,但是被小程序开发者工具的错误掩盖了.

310中提到了解决办法,考虑支持一下吗?

[微信社区帖子](https://developers.weixin.qq.com/community/develop/doc/00004c85bd02e85aca2b24ffb56800)

**Comment by JuneAndGreen** [comment]
promise async/await 的问题用最新 nightly 还是有问题么？我这边看已经 close 了。

还是说还有其他的 js 特性没有支持？

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/98196207-82655d00-1f5e-11eb-9332-3be9869ca2b3.png)

**Comment by TomVista** [comment]
就是有些语法电脑微信小程序不支持,需要es5或者更低..

pc小程序内核是53.

**Comment by JuneAndGreen** [comment]
咨询了下，pc 端有计划年内开始灰度升级到 81 内核了，到时应该就能解决问题。你那边有特殊需求的话可以先修改下 babel 配置？我这边模板就暂时不做降级处理了。

**Comment by TomVista** [comment]
好的
