### ISSUE TITLE
主包体积优化

### ISSUE THREAD

**Issue by wu253494078** [Tencent/kbone#322]
现在主包体积1200多kb 有一大半是被这几个文件占用了 
![image](https://user-images.githubusercontent.com/32081454/98889926-d67bbe80-24d5-11eb-9ce8-3b5b733f6e1b.png)
有没有方案优化这几个文件的大小呀

**Comment by JuneAndGreen** [comment]
如果都是必要的业务代码的话，只能自己做压缩裁剪了，如果里面包含了一些在小程序端用不到的代码，可参考：https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E4%BB%A3%E7%A0%81%E4%BD%93%E7%A7%AF%E7%B2%BE%E7%AE%80

顺便补充几点建议：
1、如果开发过程有页面改动，建议删除构建结果重新构建（因为页面变更会调整输出结果，旧的文件却不会被删，会占用体积）。
2、有需要，可以上分包，相关配置：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-subpackages
