### ISSUE TITLE
跟Rax怎么说

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#323]
[《Rax 小程序运行时方案解密与思考》](https://zhuanlan.zhihu.com/p/271886068) 

Rax原来是和Taro@2.x一样编译时，但编译时开发体验确实不好，所以后来直接参考kbone适配了运行时。

里面讲到最大问题就是之前谈论的性能问题，Rax也做了一些优化，但是实际没有测试体验。
setData优化部分kbone也做了，不过实际体验上有点难说。

不知道Rax尝试的性能方案是否有效，kbone是否要试一下

-------

另外，有个想法想说
感觉kbone确确实实是很好的一个小程序解决方案，而且我们公司项目也是依靠kbone跑得很稳定。非常感谢kbone，不仅提高开发效率，体验也是大大的提高

而问题也是之前讨论的，关于到底什么用户在使用kbone，react开发者肯定首选Taro。
所以理论上只有vue开发者会选择kbone，就像我们团队。但这已经只剩30%的人了，因为基本有规模的公司都是使用react。

这30%的人其中只有20%的人水平是入门及以上的。毕竟vue确实入门最简单，而剩下80%的人真的都是**，这些人估计都不知道kbone，或者可能连开发环境都搭不起来。最适合他们估计就是Uni-APP这种东西

所以kbone社区真的实在是太冷清了... 并且还要在微信开发者社区解答一些很傻的问题。

而我本身很好看好Rax的前景就是因为看到一个生态，生态和社区的活跃才是最重要

另外我看kbone也只有一个作者，这感觉实在有点憋屈，所以从技术方面，要不就去Rax吧。创造更多的价值，薪资肯定更高。

**Comment by JuneAndGreen** [comment]
感谢建议，关于优化方面我这边如果有好的方案会去尝试一下的；对于 react 相关的用户，其实 kbone 一开始的设计确实只有 vue 的 demo 的，不过参照我这边收到的咨询（大部分是腾讯内部团队的咨询），还是有不少 react 用户的，所以 vue 和 react 的问题我这边都会同步跟进；至于只有一个作者的问题嘛，目前比较稳定，没有大改的思路出现时，或者我这边一个人能 hold 住时，就不投入过多人力去改造了，事实上有很些东西我们有尝试直接在基础库/客户端层面支持或优化，这方面其实也算是 kbone 的需求，只是不在这个仓库内进行实现而已（比如先前的 virtual host 设计等）。

> PS：你的思虑我是明白的，推广运营一直都是我们的软肋，不止是 kbone，很多小程序特性功能开发者都不知道（除非有产品经理介入的功能，可以借由产品自身的渠道来，否则就只能想办法利用技术们自己的渠道来推广了），确实被吐槽了不少，我们也有在摸索怎么做到让更多的开发者知晓；关于入门门槛的问题，我这边也有在尝试新的东西（比如 kbone-ui 的改进，我这边就在尝试直接用 web component 来实现，不耦合任何框架，让开发者直接配置一下就能直接用）。最后关于挖墙脚这事，我其实也不止负责 kbone 的开发的😂，还兼顾小程序底层的一些开发，所以肯定不会因为一个开源项目而出走。
