### ISSUE TITLE
dom 生成出错了,不知道什么原因,

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#324]
![QQ图片20201120095308](https://user-images.githubusercontent.com/42435611/99748124-deabad80-2b16-11eb-8eb6-422dc8702532.png)

看一下这个选中的dom的 data-private-node-id , 这个是错的,不知道发生了什么.

具体操作是:

进入下一页,返回,点击按钮更新数据, dom 被错误的更新成为图上的状态.

很急,能不能先给出一个解决方案.

**Comment by TomVista** [comment]
没有办法给出源码,

小程序名字是  万行

测试演示如下

最后这个商品加减操作 出的问题

![421](https://user-images.githubusercontent.com/42435611/99749497-a22d8100-2b19-11eb-8ec5-632397e39390.gif)

**Comment by TomVista** [comment]
![image](https://user-images.githubusercontent.com/42435611/99750117-c2aa0b00-2b1a-11eb-8c75-731e9a254976.png)
这几个都改成false 后 ,dom 上没有问题了,但是vue 绑定关系 还是不行

**Comment by TomVista** [comment]
目前在 页面周期 onshow 中,重建了vue引用关系,解决了这个问题.

**Comment by JuneAndGreen** [comment]
vue 绑定关系具体是指？是说更改 vnode 节点，不会反馈到 dom 节点上是么？

**Comment by TomVista** [comment]
对,下面这个购物车金额是个计算属性,不再随动了

**Comment by JuneAndGreen** [comment]
试了下，不知道是不是定位问题，我这边进去是没有商品的。方便搞些假数据或者强行使用固定定位的代码（去掉鉴权那些），发到 `wx-miniprogram@qq.com` 这个邮箱么？脱敏后给 dist 后的小程序代码包也行，只要我本地能跑起来，我就可以本地来调试看看是什么问题。

**Comment by TomVista** [comment]
ok,稍等,我想想办法

**Comment by TomVista** [comment]
好了,让邮件飞一会  🐶

**Comment by JuneAndGreen** [comment]
你的提交订单页面中，代码里是不是有地方一直保留着对 dom 节点的引用/操作没有释放？我发现我原本在回收时就干掉了 vue 挂载在 dom 节点上的属性（比如 __vue__ 属性），但是重新分配时，vue 属性又被挂载上了，看起来是提交订单页面中还有相应的 vue 操作导致，比如定时器或者异步调用之类的？如果有的话，可以监听 beforeunload/wxunload 事件干掉这些东西试试？

**Comment by TomVista** [comment]
我按照这个思路找一找

**Comment by JuneAndGreen** [comment]
另外还有个问题，可能是导致上面问题的原因。原本挂载在页面的 app 是通过 createApp 方法返回的，但是你代码中这个返回的好像并不是标准的 vue 实例？因为发现调不了 $destroy 方法(vue2)，也没有 unmount 方法(vue3)。如果你是用 vue3 的话，入口那里可以参考下 demo26，走 Vue.createApp 创建实例。

**Comment by TomVista** [comment]
知识盲区,稍等,再让邮件飞一下,

**Comment by TomVista** [comment]
好像是魔改后的 vuex 的原因.

目前是,通过 window.$$publish / window.$$subscribe 通知所有页面的 vuex store 进行数据通信,可能某个环节搞错了什么,

官方提供的全局vuex通信,好像不太好用的样子,组里的亲替换成了这个方案

**Comment by JuneAndGreen** [comment]
问题应该找到了，你的  createApp 是 async 函数，我给的所有 demo 都是普通函数，所以是按照普通函数调用来获取 app 实例的，导致我在页面中没有拿到正确的 app 实例，最终结果就是在页面退出时，没有正常调用 destroy 实例的方法。

**Comment by JuneAndGreen** [comment]
mp-webpack-plugin@1.1.17

试试这个，我这边自测没有问题了。

**Comment by TomVista** [comment]
收到,大佬nb

**Comment by TomVista** [comment]
dom 没问题了,但是 计算属性还是不能够随动, 就下面这个金额
![image](https://user-images.githubusercontent.com/42435611/99948971-3e26e900-2db5-11eb-8884-816013a06b08.png)

**Comment by TomVista** [comment]
计算属性 不是 kbone 的原因, 这个崽把购物车数据挂到 window.$$global

上个页面销毁后,引用自然就对不上了,

**Comment by JuneAndGreen** [comment]
因为你这里的 window.$$global.shoppingCart 每次进入页面都会作为新页面的 storeShoppingCart 数据，而 vue 针对 shoppingCart 只会保留一个 observer 对象，导致后面页面的 observer 覆盖了前面页面的 observer。

有一个比较简单的做法，每次进入页面时，都重新拷贝一下数据，干掉 observer（或者也可以尝试干掉数据的 __ob__ 属性？），让这个页面重新给数据追加 observer：

![image](https://user-images.githubusercontent.com/7931744/99963840-5a368480-2dcd-11eb-946e-f29974d9927d.png)

以上代码是在 merchantDetail.vue 中，其他有类似问题也可以尝试按照同样方式试试。

**Comment by JuneAndGreen** [comment]
另一种方案是，可以试试 kbone-tool，在 main.js 加下就行：

![image](https://user-images.githubusercontent.com/7931744/99964589-7edf2c00-2dce-11eb-91db-d28ec4aa248e.png)

这里会重写 Object.defineProperty，让 vue 在通过这个方法设置 observer 的时候进行缓存、不覆盖，每次获取 observer 的时候获取 currentPage 的 observer。

以上两种方法应该均可行，选择合适的即可。

**Comment by TomVista** [comment]
感谢大佬
