### ISSUE TITLE
有什么方案可以避免或者解决循环引用顺序导致undefined的问题

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#325]
用户场景
- 进入小程序页面A，小程序页面A跳转到小程序页面B
- 从小程序页面B返回
- 会报错 xxx is undefined

如果直接进入小程序页面A，而不进行跳转则不会出现这个问题，应该是由循环引用js造成。
像这种情况有没有好的解决方法或者避免的

尝试方案
- 将循环引用的内容放在独立文件，且不引用其他文件 => 没有用
- 将循环引用的内容在小程序页面A main.js 中引用 => 可以 ，但是非常不优雅

**Comment by JuneAndGreen** [comment]
具体是怎么循环引用的呢？这里 js 的引用应该都交给 webpack 构建期来解决了，不同的页面也都做成独立的 runtime，按道理底层像 window、document 等都是没有循环引用的才对。

方便给个具体的例子/demo么？

**Comment by xmsz** [comment]
我先关闭吧 写了demo发现没有复现 看来和很多原因相关 暂时也没时间测试了

现在临时的解决办法就是在页面A的main.ts文件中引用一遍循环引用的值，这样能保证页面A一定先引用
