### ISSUE TITLE
小程序基础库2.14.1,kbone异常

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#327]
@JuneAndGreen 
邮箱给你发过去一批小程序,你试一试,全部是kbone项目,

小程序基础库 2.14.1

问题:
* 文字丢失
* 图片丢失
* 路由跳转白屏

**Comment by TomVista** [comment]
基础库 2.14.1

**Comment by TomVista** [comment]
线上 v1.x 渲染模式 的kbone项目,没有出现问题.

**Comment by TomVista** [comment]
基础库2.14.1 , 应该是回滚了,找不到这个版本的基础库了.

**Comment by JuneAndGreen** [comment]
原因知悉了，基础库模块系统的修改出现问题导致，现已回退并 revert，我用内部最新构建的 2.14.1 测过已经恢复。后续可继续观察 2.14.1 的再次灰度，感谢此次的及时反馈🙏。

**Comment by JuneAndGreen** [comment]
问一下，你那边是不是同时本地构建的 kbone 的 npm，也开了 kbone 扩展库呢？看起来有两份 kbone 的 miniprogram-render/miniprogram-element 代码。

**Comment by TomVista** [comment]
我检查了一下，没有开启拓展库，只有本地构建，
···
 appExtraConfig: {
    sitemapLocation: 'sitemap.json',
    useExtendedLib: {
      kbone: false, // 和 generate.autoBuildNpm 只保留一个
    },

···

**Comment by TomVista** [comment]
我明天把webpack配置和mp-webpack-p 配置发给你，手机没办法操作。之前邮件那份脱密的代码的webpack配置，和今天发给你的小程序们是一致的。

**Comment by TomVista** [comment]
配置已通过邮件发过去了.
