### ISSUE TITLE
有没有人遇到无法传递给原生自定义组件对象或者数组

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#329]
情况
1. 给原生自定义组件传递了对象或者数组
2. 原生自定义组件成功接受到数据
3. 修改对象或者数组
4. 原生自定义组件没有收到更新后的值

如果传递的是数字或者字符串就正常能更新

Demo后面再补

**Comment by JuneAndGreen** [comment]
已修复，请更新到 mp-webpack-plugin@1.1.19 试试。
