### ISSUE TITLE
react 使用 window.console.log 不会自动转换成 console.log

### ISSUE THREAD

**Issue by zdwork** [Tencent/kbone#336]

**Comment by JuneAndGreen** [comment]
- miniprogram-element@2.1.21
 - miniprogram-render@2.1.8

以上版本已将 console 补充到 window 下了。

**Comment by zdwork** [comment]
详解见附件&nbsp;
还是不行 已经更换到

miniprogram-element@2.1.21

miniprogram-render@2.1.8



主题:&nbsp;Re: [Tencent/kbone] react 使用 window.console.log 不会自动转换成 console.log (#336)





  
miniprogram-element@2.1.21
 
miniprogram-render@2.1.8
  
以上版本已将 console 补充到 window 下了。

**Comment by JuneAndGreen** [comment]
确实加了：https://github.com/Tencent/kbone/blob/8a54c4dc461ac5dadcb1c178241ce20d7a6334e9/packages/miniprogram-render/src/window.js#L608 使用 demo 16 自测可以使用 window.console.log，你看看跑的版本是否确实是我提供的版本？在小程序里还需要构建到 miniprogram_npm 的，只是更新了 node_modules 还不行。

**Comment by zdwork** [comment]
多谢，我把mp删除掉重新构建下就可以了




 
确实加了：https://github.com/Tencent/kbone/blob/8a54c4dc461ac5dadcb1c178241ce20d7a6334e9/packages/miniprogram-render/src/window.js#L608 使用 demo 16 自测可以使用 window.console.log，你看看跑的版本是否确实是我提供的版本？在小程序里还需要构建到 miniprogram_npm 的，只是更新了 node_modules 还不行。
