### ISSUE TITLE
开发者工具自动预览报错 

### ISSUE THREAD

**Issue by zdwork** [Tencent/kbone#338]
![zd](https://user-images.githubusercontent.com/24469374/103121655-209cb600-46b8-11eb-847c-81772377b2c7.png)

**Comment by JuneAndGreen** [comment]
这报错看来是出自业务代码，工具本地预览、手机扫码预览是否正常？

**Comment by zdwork** [comment]
工具本地预览正常，无法在手机上预览

**Comment by JuneAndGreen** [comment]
看来这个是业务代码里存在不支持代码保护功能，关闭代码保护试试？
![image](https://user-images.githubusercontent.com/7931744/103122751-8f7c0e00-46bc-11eb-8d91-21503157dbd4.png)

**Comment by zdwork** [comment]
关闭自动保护可以
