### ISSUE TITLE
请问下没有react的demo吗，vue的看着很多

### ISSUE THREAD

**Issue by zdwork** [Tencent/kbone#340]

**Comment by JuneAndGreen** [comment]
demo16 、demo24 是 react demo，这里还有个 react 的项目模板：https://github.com/wechat-miniprogram/kbone-template-react。

本质上来说无论是 react 还是 vue，底层都是一样的，kbone 不会对 react 框架做任何的魔改，只在底层适配，所以就以 vue 为主，其他 Web 框架基本都是可以套用配置的。
