### ISSUE TITLE
demo24：react + 多页

### ISSUE THREAD

**Issue by zdwork** [Tencent/kbone#343]
这个没有跑通 可以给个完整的demo吗，index.js不知道怎么定义

**Comment by JuneAndGreen** [comment]
demo24 就是完整的 demo 了，你可以先看看上手文档再着手开发：https://wechat-miniprogram.github.io/kbone/docs/guide/quickstart.html#%E4%BD%BF%E7%94%A8-kbone-cli-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%8F%91 和 https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html#%E7%BC%96%E5%86%99-webpack-%E9%85%8D%E7%BD%AE

基本上是先走 webpack 构建 build 出小程序，demo 里通常命令是 npm run mp；
然后 build 出来的小程序在 demo 里一般是放到 dist/mp 下，然后进到这个目录执行 npm i，安装小程序需要的 npm 依赖；
然后用工具打开 dist/mp，执行工具的 “构建 npm”，然后就 ok 了。

**Comment by zdwork** [comment]
请问下vue当前跳转右上方有个小房子，react当前页跳转咋没有呢




 
Closed #343.

**Comment by JuneAndGreen** [comment]
你说的是左上角的主页按钮吧，这是小程序逻辑，和 kbone 无关，取决于当前页面栈的情况，比如 demo 里栈里只有一页，而且是非首页，就会有此按钮。
