### ISSUE TITLE
不支持 使用插件提供的自定义组件

### ISSUE THREAD

**Issue by TomVista** [Tencent/kbone#344]

**Comment by JuneAndGreen** [comment]
目前暂时不支持直接使用插件里的自定义组件，所以当前如果要用的话得走一个比较迂回的方式：先写一个自定义组件，然后在这个自定义组件中使用插件组件（https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6）

> PS：后续有计划支持直接引用插件，不过短期内应该搞不掂。
