### ISSUE TITLE
需求: Vue3支持

### ISSUE THREAD

**Issue by shawn-yee** [Tencent/kbone#345]
请问Vue3支持吗?
可否增加案例?
谢谢.

**Comment by JuneAndGreen** [comment]
demo26 就是：https://github.com/Tencent/kbone/tree/develop/examples/demo26

> PS：目前 vue3 较新，我们这边使用较少，收到的反馈也比较少，尚有一些不确定性，demo26 只是做了个比较简单的应用。

**Comment by parkerisme** [comment]
能不能把demo26打包h5和kbone-ui接入啊。我自己尝试接入kbone-ui1.x，一直失败。代码如下：

import { createApp } from 'vue'
import * as vue from 'vue'
import components from '@/components'
import KBoneUI from 'kbone-ui'
KBoneUI.register()

window.Vue = vue
const initApp = (view) => {
  // KBoneUI.register()
  const app = createApp(view)
  app.use(components)
  // app.use(KBoneUI)
  app.mount('#app')
  return app
}

入口处已经KBoneUI.register()

测试了一下，控制台报警告，找不到wx-picker：
runtime-core.esm-bundler.js:238 [Vue warn]: Failed to resolve component: wx-picker
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>

**Comment by JimmyVV** [comment]
已经收到哦~~~~
