### ISSUE TITLE
vue demo 运行失败

### ISSUE THREAD

**Issue by bhabgs** [Tencent/kbone#346]
## 问题流程
1. 按照`kbone`官网提示 安装`cli`
2. 使用cli 创建 app， 选择`vue template`
3. 安装依赖，根据根目录README.md 调试，并报告错误
* 错误如下
![image](https://user-images.githubusercontent.com/19221378/103854568-b9392a00-50eb-11eb-9974-d3285bfdb0a6.png)

**Comment by JuneAndGreen** [comment]
需要点一下工具的 npm 构建，把依赖正常构建出来：https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
