### ISSUE TITLE
元素只有 data-* 属性时无法 querySelector 选中

### ISSUE THREAD

**Issue by sssession** [Tencent/kbone#347]
createApp 中向 body 插入一个 div **只有 data-key** 时无法 querySelector 选中。

![image](https://user-images.githubusercontent.com/4843262/104434099-ca8ba600-55c5-11eb-9d97-45d78429d481.png)

![image](https://user-images.githubusercontent.com/4843262/104434037-b9db3000-55c5-11eb-8667-f5925e0eaed2.png)

搭配有非 data-* 属性时则可以选中

![image](https://user-images.githubusercontent.com/4843262/104434205-ee4eec00-55c5-11eb-90e0-de32edc28756.png)

![image](https://user-images.githubusercontent.com/4843262/104434232-f9098100-55c5-11eb-9e35-83d2adb3ef64.png)

看了一下源码，element 在 init attribute 时不会设置 data- 为 attr。在 querySelector 时判断 $__attrs 为 null 就跳过了。

**Comment by JuneAndGreen** [comment]
已在 miniprogram-render@2.2.3 中 fixed
