### ISSUE TITLE
支持 tap 事件后破坏了 zepto 的 tap 事件

### ISSUE THREAD

**Issue by sssession** [Tencent/kbone#349]
https://github.com/Tencent/kbone/commit/3d9cd5e80e453aa6fe384e359a48b770fedc55ab

看到这个提交中增加支持原生 tap 事件。

但是 web 中没有原生的 tap，zepto 用 touch 相关事件模拟了 tap。原生支持 tap 后会触发两次 tap 回调。

**Comment by JuneAndGreen** [comment]
miniprogram-element@2.2.3

支持了一个配置，可以禁止抛出小程序原生的 tap、longpress 事件，避免冲突：

https://wechat-miniprogram.github.io/kbone/docs/config/#runtime-disablempevent
