### ISSUE TITLE
kbone小程序预览白屏，提示module "pages/miniprogram-render.js" is not defined，真机调试是好的

### ISSUE THREAD

**Issue by 521314xiongCheng** [Tencent/kbone#350]
![image](https://user-images.githubusercontent.com/54136501/106087984-0c892000-6160-11eb-8b8a-9da62615707b.png)
https://github.com/wechat-miniprogram/kbone-template-vue 官方demo也有这个问题。

**Comment by JuneAndGreen** [comment]
看看是不是没有构建出 miniprogram-npm 目录：

![image](https://user-images.githubusercontent.com/7931744/106099806-3fd6a980-6176-11eb-9576-e94564cad424.png)

**Comment by 521314xiongCheng** [comment]
![image](https://user-images.githubusercontent.com/54136501/106100386-3d288400-6177-11eb-98d5-4c813d87e557.png)
生成了的，我把原来的删除了，重新导入还是报这个错
![image](https://user-images.githubusercontent.com/54136501/106100659-af00cd80-6177-11eb-8dc5-916ae8ea5837.png)

**Comment by zenooool** [comment]
同样有这个问题，换机器试，直接用官方demo都不行

**Comment by JuneAndGreen** [comment]
你预览时用的基础库是哪个版本？

**Comment by 521314xiongCheng** [comment]
2.14.3 2.12.2 2.14.4都试过了，问题一样，切换版本之后也重启开发者工具了

**Comment by 521314xiongCheng** [comment]
![image](https://user-images.githubusercontent.com/54136501/106260425-5e62a080-625b-11eb-8882-be5814dcc77b.png)
如果我改成这样预览就ok了
我电脑是 MacBook Pro (Retina, 13-inch, Mid 2014) 系统版本10.15.7 (19H2)

**Comment by JuneAndGreen** [comment]
你试下关掉工具的代码保护，看看是不是正常呢？我这边怀疑是代码保护那块导致的。。。

**Comment by 521314xiongCheng** [comment]
果然如此。。。。谢谢了

**Comment by JuneAndGreen** [comment]
代码保护问题，最新 nightly 版本已修复：https://developers.weixin.qq.com/miniprogram/dev/devtools/nightly.html
