### ISSUE TITLE
kbone有没有兼容到vant呢？使用过程中发现完全没有兼容vant的可能

### ISSUE THREAD

**Issue by guoChopper** [Tencent/kbone#351]

**Comment by JuneAndGreen** [comment]
受限于小程序本身的环境，外部 Web 版 ui 库大多受制于 getComputedStyle、getBoundingClientRect 等一些无法直接模拟的接口而无法完全兼容，目前应该只有部分组件能用。

而外部小程序版的 ui 库，可以通过[使用第三方自定义组件](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)的方式间接使用，但是建议按需使用，而不要大范围采用第三方组件。

如果是官方提供的 weui 组件库，可以参考[此文档](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#ui-%E5%BA%93)，兼顾了小程序端和 Web 端。
