### ISSUE TITLE
使用 Kbone 时 onError 无法监听到报错信息

### ISSUE THREAD

**Issue by skylinelayla** [Tencent/kbone#352]
如图，在使用 demo5 中提供的例子测试时，发现 onError 并不能捕获到脚本错误
![image](https://user-images.githubusercontent.com/7480378/108938313-d077ab00-768a-11eb-9bc5-058e864f110b.png)
在 page1/App.vue 里的 「promise reject 模拟」绑定的事件中抛出了一个异常，但是 onError 里并不能捕获到。
![image](https://user-images.githubusercontent.com/7480378/108938493-23e9f900-768b-11eb-9a2d-4002cdd318ed.png)

**Comment by JuneAndGreen** [comment]
同步 error 会先被 vue 捕获，所以我这边拿不到。你可以加个 vue 的 errorHandler 试试：https://cn.vuejs.org/v2/api/index.html#errorHandler
