### ISSUE TITLE
请问使用kbone开发分享功能，打开分享页面生命周期执行两次是为什么？

### ISSUE THREAD

**Issue by big-zhangjun** [Tencent/kbone#353]
window.onShareAppMessage = () => {
      console.log(this.mid, "====");

      return {
        title: "XXX分享音频给您",
        path: `/audio?mid=${this.mid}`,
        imageUrl:
          "https://zino-common.oss-cn-beijing.aliyuncs.com/backbground/c_share.png"
      };
    };
![微信图片_20210303115042](https://user-images.githubusercontent.com/53329880/109767582-b7df3600-7c32-11eb-82fb-577581944da6.jpg)

**Comment by JuneAndGreen** [comment]
是一开始进入就有一次 onload，调分享又跑了一次 onload 么？

另外，这个分享是如何调用的，是右上角菜单分享还是 wx-button 触发的分享呢？

**Comment by big-zhangjun** [comment]
> 是一开始进入就有一次onload，调分享又跑了一次onload么？
> 
> 另外，这个分享是如何调用的，是右上角菜单分享还是wx-button触发的分享呢？

不是，就是点击分享的卡片后，生命周期执行两次

**Comment by big-zhangjun** [comment]
> > 是一开始进入就有一次onload，调分享又跑了一次onload么？
> > 另外，这个分享是如何调用的，是右上角菜单分享还是wx-button触发的分享呢？
> 
> 不是，就是点击分享的卡片后，生命周期执行两次
分享是使用wx-button来触发的

**Comment by JuneAndGreen** [comment]
生命周期是指什么生命周期？我这边尝试写了个 demo，但是无论是 onload 还是 onShareAppMessage 都只会调一次，show 和 hide 会有两次正常，因为拉起分享页面本身会触发底下页面的隐藏，这是原生逻辑。你可以检查一下你的代码会不会监听了某个事件两次而导致这种现象？

**Comment by JuneAndGreen** [comment]
这个生命周期是指哪个生命周期？我这边试了下并没有这个现象，如果你指的是当前手机分享出去后，又用当前手机点开自己分享出去的卡片，这时候看到会有原页面出现 unload，分享页面 load 的情况，这是正常的。因为刚分享出去后，又直接当前手机点开分享卡片，这时候小程序还在后台进程，会直接唤起执行 relaunch，这是小程序本身就有逻辑。这和小程序还在后台时，你又扫码打开小程序的逻辑类似，都会先打开然后执行 relaunch 到某个页面。

**Comment by JuneAndGreen** [comment]
另外你上面的日志可能还残留着上一次打开小程序的日志（也就是有两次 onload 的日志），因为小程序进程没被杀而重新被唤起的话，日志就不会被清除，你可以手动打下日志加个标志符或者时间戳区分一下。
