### ISSUE TITLE
Input onFocus 和 onBlur 无法在 react@17 下触发

### ISSUE THREAD

**Issue by woody** [Tencent/kbone#354]
项目使用 react@17， 参照 [demo 16](https://github.com/Tencent/kbone/tree/develop/examples/demo16) 事例代码实现 `input onFocus` 无法被触发，降级至 react@16 可正常触发。

Kbone 使用 React 是否有版本要求？

**Comment by JuneAndGreen** [comment]
miniprogram-element@2.2.4

react17 没有监听 focus/blue 事件，改成监听 focusin/focusout 来触发 onFocus 和 onBlur 导致，已支持 focusin/focusout
