### ISSUE TITLE
真机使用canvas时，为什么获取触摸事件有延时？

### ISSUE THREAD

**Issue by sunyayue** [Tencent/kbone#355]
我使用的是vue3+kbone，中间有一个需求是需要用户点击canvas，然后画出方框。

可以进入页面后，vconsole有触发触摸事件：

Invoke event onCanvasTouchStart in component: miniprogram_npm/miniprogram-element/index

Invoke event onCanvasTouchMove in component: miniprogram_npm/miniprogram-element/index

Invoke event onCanvasTouchEnd in component: miniprogram_npm/miniprogram-element/index

但是并没有执行touchStart对应的函数，要等大概10-30秒，重新点击，才会执行函数，期间点击canvas，vconsole都会相应如上事件。

从这个可以看出，明明canvas接收到了事件，就是不执行我的函数，非要等一段时间，真的搞不懂。

这个在开发者工具里面是秒出的，没有这个延时，然后真机无法调试canvas，预览和发布体验版就会有这个延迟，很影响体验，请问是什么问题呢？

有没有什么好的方法可以规避。

这是补充的代码图和vconsole的展示图，vconsole那边真的等了很慢，10-30秒
![1583045caf8d58332df349f6846e3d6](https://user-images.githubusercontent.com/68684132/110888425-1e491000-8327-11eb-927d-8ffc6676ddbd.png)
![c1017302ff79f4470e3cec22f656247](https://user-images.githubusercontent.com/68684132/110888428-21440080-8327-11eb-9141-c81bbd2a5652.png)
![bd72c1370477098c29f3c16c29f84dc](https://user-images.githubusercontent.com/68684132/110888426-1f7a3d00-8327-11eb-83d6-41235721b7bb.jpg)

前面等待时不会打印gaga，过了很久才会打印，并且不会触发之前的点击

**Comment by JuneAndGreen** [comment]
我这边尝试写了个 demo，但是没能复现。你可以尝试写个更简单的 demo，看看是不是有业务代码影响到了，另外也可以对照下 vue2 会不会有问题？

**Comment by sunyayue** [comment]
> 我这边尝试写了一个demo，但是没能复现。你可以尝试写个更简单的demo，看看是不是有业务代码影响到了？另外也可以对照下vue2会不会有问题？
> 
> ![图像](https://user-images.githubusercontent.com/7931744/110905095-e94bb600-8344-11eb-9679-3cd26bdeb0c3.png)

没错，我自己写demo也无法复现BUG，那就是被自己的业务代码影响了，业务代码太复杂了，一时无法定位具体问题。
但是我有一个疑问就是明明我那边显示触发了事件，函数为什么不响应，如果能搞清楚这个或许能帮我定位问题所在。
我业务场景类似与做很多题，第一题若是canvas就不会有问题，第一题不是，跳第二题，前10s以上就无法响应canvas的事件，仅仅是无法响应事件，相关dom都能获取到。我再继续定位问题，看看根因是什么。

**Comment by sunyayue** [comment]
> 我这边尝试写了个 demo，但是没能复现。你可以尝试写个更简单的 demo，看看是不是有业务代码影响到了？另外也可以对照下 vue2 会不会有问题？
> 
> ![image](https://user-images.githubusercontent.com/7931744/110905095-e94bb600-8344-11eb-9679-3cd26bdeb0c3.png)

实在是不明白原因，我已经剥离两个子组件的所有内容了，仍然是这个问题，就是父组件中，切换两个子组件，但是调试时发现click事件可以照常响应，遂取click事件作为touchstart的替代方案，这个BUG就只能暂时搁置了，因为我还有其他开发任务，在这个BUG上已经耽误了过多时间。
暂时的怀疑点几乎已经排除了性能原因（子组件的切换），可能和底层的事件绑定有关。
可以确定的是这是个BUG，特别是在 click能照常响应而touchstart事件却不能响应 情况下看，而等个十几秒却又能响应了。
只不过简单的demo无法复现，我仍然未找到触发BUG的核心要素。希望官方能检查一下相关的底层代码，看看能不能有什么收获。

**Comment by JuneAndGreen** [comment]
底层代码并没有什么特殊逻辑，几乎所有事件都是一视同仁的，调用顺序是这样的：
1、监听 canvas touchstar 事件：https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-element/src/util/component.js#L2368
2、调 EventTarget.$$process 方法进行捕获冒泡：https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-element/src/base.js#L226
3、调 $$trigger 进行触发：https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-render/src/event/event-target.js#L145
4、触发 handler：https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-render/src/event/event-target.js#L243

底层代码大概是这样，你可以在这几个地方看看有没有延迟，如果到 handler 阶段都没延迟，那就是 Web 框架/业务逻辑问题了。或者还有个可能就是这里的每个 handler 都是同步触发的，会不会有哪个 handler 里面的逻辑执行特别久导致后面的 handler 被卡住了之类的。

**Comment by sunyayue** [comment]
> 底层代码并没有什么特殊逻辑，几乎所有事件都是一视同仁的，调用顺序是这样的：
> 1、监听 canvas touchstar 事件：
> 
> https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-element/src/util/component.js#L2368
> 
> 
> 2、调 EventTarget.$$process 方法进行捕获冒泡：
> https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-element/src/base.js#L226
> 
> 
> 3、调 $$trigger 进行触发：
> https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-render/src/event/event-target.js#L145
> 
> 
> 4、触发 handler：
> https://github.com/Tencent/kbone/blob/5cc6112cbc28e6844ae0ea4b4fab8184fea2162a/packages/miniprogram-render/src/event/event-target.js#L243
> 
> 底层代码大概是这样，你可以在这几个地方看看有没有延迟，如果到 handler 阶段都没延迟，那就是 Web 框架/业务逻辑问题了。或者还有个可能就是这里的每个 handler 都是同步触发的，会不会有哪个 handler 里面的逻辑执行特别久导致后面的 handler 被卡住了之类的。

我再你第二点捕获冒泡那边加了这行代码（压缩过后的，e是domNode,t是evt）：
if(e.tagName === 'CANVAS'&&t.type === 'touchstart') console.log('t:',t)
刚进去一次点击只会打印一次，等待一段时间后，一次点击会打印两次，所以就是两次打印之间有些同步操作阻塞了？
但是我不是很确定这两次打印是什么意思。
这两次是事件捕获和事件冒泡吗？
我加了一个touchstart事件捕获的响应函数，现象与冒泡一致，都是刚开始无法响应。
我比较疑惑的是click事件是可以照常触发，而touchstart系列事件不行，理论上click事件应该是在touchend事件之后。
我也在删减项目代码和编写新demo方面做了一些尝试，但是都没能定位到决定性的代码，我会继续尝试，至于底层代码阅读实在是有点超乎我的能力水平，我很难短时间厘清我vue源代码的事件是怎样在小程序中响应的。
还有一点就是微信开发者工具是不会出现此bug的，只有预览和体验版会出现，至于真机调试功能则无法调试canvas。

**Comment by JuneAndGreen** [comment]
你可以在第四点那里的 handler.call 那里加个耗时计算看看？这里就是调 addEventListener 绑定的事件句柄的地方，如果有阻塞，这里应该会有耗时很久的情况出现。

**Comment by sunyayue** [comment]
> 你可以在第四点那里的 handler.call 那里加个耗时计算看看？这里就是调 addEventListener 绑定的事件句柄的地方，如果有阻塞，这里应该会有耗时很久的情况出现。

查了，没有阻塞，一切正常，包括这个handler.call(this || null, event, ...args)都执行了，无论是可响应，还是不可响应，都没有阻塞。我还是继续删代码定位问题吧，争取给出最小复现代码。

**Comment by sunyayue** [comment]
> 你可以在第四点那里的 handler.call 那里加个耗时计算看看？这里就是调 addEventListener 绑定的事件句柄的地方，如果有阻塞，这里应该会有耗时很久的情况出现。

我自己写的demo终于可以复现问题了，关键差别应该就是vue3，
怪不得用我们项目，几乎代码删完仍然能复现，而用官方demo就不行。我下面附上最小复现代码
[demo2.zip](https://github.com/Tencent/kbone/files/6154283/demo2.zip)
现象就是进入小程序后，点击切换进入有canvas的子路由，点击有颜色的canvas块，不响应touchstart事件，需要等一会儿才能响应。
这个几乎可以证明和我们业务逻辑无关了，就是单纯的vue3和kbone冲突。
请问一下这个应该怎么处理呢，是不支持vue3，还是说后面什么时候会解。

**Comment by JuneAndGreen** [comment]
vue@3.0.7，在工具/iOS 上都复现不了，是有特定机型才这样么？

![image](https://user-images.githubusercontent.com/7931744/111592716-18aa6900-8804-11eb-9080-a97dfca684b5.png)

**Comment by sunyayue** [comment]
> vue@3.0.7，在工具/iOS 上都复现不了，是有特定机型才这样么？
> 
> ![image](https://user-images.githubusercontent.com/7931744/111592716-18aa6900-8804-11eb-9080-a97dfca684b5.png)

不是哦，我刚刚更新到3.0.7，试了一下还是这样，我是小米11，又找同事试了一下同事是iphone xsmax
我的vconsole图：
![image](https://user-images.githubusercontent.com/68684132/111594313-e00b8f00-8805-11eb-91ea-301052a9857f.png)

同事vconsole图：
![image](https://user-images.githubusercontent.com/68684132/111594217-bf433980-8805-11eb-91c6-a6160d52c3a1.png)

完整触发步骤是：点完切换后，猛点有颜色的canvas区域，然后打开vconsole就能看到，我自己的手机三秒之后就可以响应了，同事手机要等6秒以上，这还是项目结构很简单，我们公司的项目足足需要10-30秒。
你无法复现可能是你手机响应速度比较快，而您的操作比较慢造成的。
开发者工具完全无法复现，必须真机预览或者体验版小程序。

**Comment by JuneAndGreen** [comment]
感觉机子性能无关，我换成 SE 也是正常的。

那你可以尝试以下几个方式试试（我这边没法复现也无法尝试），看看问题有没有改善：

1、使用同步回调换掉 async 回调
2、不走 vue 的事件监听，改成 addEventListener 或者 kbone-event-map 属性的方式

**Comment by sunyayue** [comment]
> 感觉机子性能无关，我换成 SE 也是正常的。
> 
> 那你可以尝试以下几个方式试试（我这边没法复现也无法尝试），看看问题有没有改善：
> 
> 1、使用同步回调换掉 async 回调
> 2、不走 vue 的事件监听，改成 addEventListener 或者 kbone-event-map 属性的方式

我把复现代码传到git了：https://github.com/sunyayue/kbone-vue3.git
让另一个同事成功复现bug，她是华为nova5 pro，至于你说的我去试试看。

**Comment by sunyayue** [comment]
> 感觉机子性能无关，我换成 SE 也是正常的。
> 
> 那你可以尝试以下几个方式试试（我这边没法复现也无法尝试），看看问题有没有改善：
> 
> 1、使用同步回调换掉 async 回调
> 2、不走 vue 的事件监听，改成 addEventListener 或者 kbone-event-map 属性的方式

去掉 async 标识无用，但是替换vue的事件监听，改成addEventListener则可以了。。。。。

**Comment by sunyayue** [comment]
> > 去掉 async 标识无用，但是替换vue的事件监听，改成addEventListener则可以了。。。。。
> 
> 如果 addEventListener 正常，那肯定是 vue3 内部搞了什么东西了。我晚点再用你的新 demo 试试

好的，麻烦了，暂时我可以用addEventListener来规避这个问题，新demo我有提交addEventListener监听代码，你可以回退初始版本测，感谢指导！

**Comment by JuneAndGreen** [comment]
嗯，晚点我看看 vue3 的实现。

话说。。。我好像不小心编辑了你的评论，已改回，避免引起混淆。

**Comment by sunyayue** [comment]
> 嗯，晚点我看看 vue3 的实现。
> 
> 话说。。。我好像不小心编辑了你的评论，已改回，避免引起混淆。

okk，谢谢！

**Comment by JuneAndGreen** [comment]
我这边搞了好几台手机都不能复现，iOS 和安卓都尝试过，你那边有另外尝试过其他机型来跑这个 demo 么？或者你看看能不能把你编好的有问题的 demo 给我呢（就是 dist/mp 目录下可以直接跑的小程序项目）。

**Comment by sunyayue** [comment]
> 我这边搞了好几台手机都不能复现，iOS 和安卓都尝试过，你那边有另外尝试过其他机型来跑这个 demo 么？或者你看看能不能把你编好的有问题的 demo 给我呢（就是 dist/mp 目录下可以直接跑的小程序项目）。

https://github.com/sunyayue/kbone-vue3.git这边的相应目录的传上去了
上次说过 vue3 的绑定监听改为 手动addEventListener 就可以了，估计你没有改回去
这次我最新更新改成有问题的代码，直接dist/mp 下 预览 就可以复现，但是这个是压缩后的代码，估计没法看
然后复现时要记得：点击切换后立马点击有颜色区域，看vconsole就可以了，，现象为前几秒触发事件不会打印相应console.log（console.info 会有事件invoke 的信息，log为我函数中打印），我刚刚实测 中间仍然有三秒以上的触发时间，所以应该是很容易复现的，同事的手机也是，无论安卓和ios，还是无法复现我可以录制复现视频，到时候看怎么发视频给你。

**Comment by JuneAndGreen** [comment]
addEventListener 其实我是改回去了的，我再试试你遍出来的版本。

**Comment by sunyayue** [comment]
好

**Comment by JuneAndGreen** [comment]
知道原因了，你这里应该只有渲染出 canvas 时触摸 canvas 才会这样，vue3 里面有个拿事件时间戳和 performance 时间戳比较的逻辑，坑在这里了，导致有些事件被 vue3 丢了。

**Comment by sunyayue** [comment]
> 知道原因了，你这里应该只有渲染出 canvas 时触摸 canvas 才会这样，vue3 里面有个拿事件时间戳和 performance 时间戳比较的逻辑，坑在这里了，导致有些事件被 vue3 丢了。

哦哦，那这个是kbone 这边适配，还是应该属于VUE3 自己解BUG呢。

**Comment by JuneAndGreen** [comment]
我把事件时间戳对齐到 window.performance 了，不再用小程序事件提供的时间戳

 - miniprogram-element@2.2.5
 - miniprogram-render@2.2.10
 - mp-webpack-plugin@1.3.9

**Comment by sunyayue** [comment]
> 我把事件时间戳对齐到 window.performance 了，不再用小程序事件提供的时间戳
> 
> * miniprogram-element@2.2.5
> * miniprogram-render@2.2.10
> * mp-webpack-plugin@1.3.9

可以了，谢谢
