### ISSUE TITLE
kbone-cli初始化出来的项目kbone-ui是0.x的，能否升级下，里面还有多余文件和样式没删除

### ISSUE THREAD

**Issue by WormGirl** [Tencent/kbone#357]

**Comment by WormGirl** [comment]
升级了kbone-ui版本,报下面的错
![image](https://user-images.githubusercontent.com/16078260/111428176-1bd52480-8732-11eb-816b-4671542489a1.png)

**Comment by WormGirl** [comment]
https://github.com/WormGirl/kboneui-template  改了下可以了

**Comment by JuneAndGreen** [comment]
kbone-ui 的模板已更新
