### ISSUE TITLE
请问，小程序扫码后进入白屏是什么原因？

### ISSUE THREAD

**Issue by big-zhangjun** [Tencent/kbone#359]
生成小程序二维码后，扫码进入白屏，但是有的页面又可以正常显示，请问是和分包有关系吗？

![微信图片_20210324141044](https://user-images.githubusercontent.com/53329880/112263899-fbb1e200-8caa-11eb-879c-b62ab70ee7c5.jpg)

**Comment by JuneAndGreen** [comment]
在工具上一切正常，只有手机扫描预览白屏么？vconsole 有报错信息么？可以真机调试一下看看？

**Comment by big-zhangjun** [comment]
> 在工具上一切正常，只有手机扫描预览白屏么？vconsole有报错信息么？可以真机调试一下看看？

通过开发者工具使用二维码编辑，也是白屏，报错信息如下
![微信图片_20210324142049](https://user-images.githubusercontent.com/53329880/112264734-454efc80-8cac-11eb-96f1-2e763df8c4b6.png)

**Comment by big-zhangjun** [comment]
> > 在工具上一切正常，只有手机扫描预览白屏么？vconsole有报错信息么？可以真机调试一下看看？
> 
> 通过开发者工具使用二维码编辑，也是白屏，报错信息如下
> ![微信图片_20210324142049](https://user-images.githubusercontent.com/53329880/112264734-454efc80-8cac-11eb-96f1-2e763df8c4b6.png)

当前页面内的生命周期，方法都没有执行

**Comment by JuneAndGreen** [comment]
> > 在工具上一切正常，只有手机扫描预览白屏么？vconsole有报错信息么？可以真机调试一下看看？
> 
> 通过开发者工具使用二维码编辑，也是白屏，报错信息如下
> ![微信图片_20210324142049](https://user-images.githubusercontent.com/53329880/112264734-454efc80-8cac-11eb-96f1-2e763df8c4b6.png)

这个不是报错，是正常的 warning。如果本地也是白屏，你可以看看 dom 树是否正常创建出来；如果本地正常只有手机白屏，你可以使用远程真机调试看看是否正常，同时也看看 wxml 面板里有没有对应的节点树，可以排查一下是 dom 树没有创建导致、样式问题、dom 树创建了但是小程序的组件树没有创建，还是所有树和样式都正常就是渲染不出来导致的。

**Comment by myzoediray** [comment]
> > 在工具上一切正常，只有手机扫描预览白屏么？vconsole有报错信息么？可以真机调试一下看看？
> 
> 通过开发者工具使用二维码编辑，也是白屏，报错信息如下
> ![微信图片_20210324142049](https://user-images.githubusercontent.com/53329880/112264734-454efc80-8cac-11eb-96f1-2e763df8c4b6.png)

IOS是好的吗？我们这边也出现安卓首次进入kbone的子包时页面白屏

**Comment by JuneAndGreen** [comment]
是的，我这边写的分包 demo 都正常，你可以先按照我上面的描述排查一下是哪个环节导致的？

**Comment by JuneAndGreen** [comment]
一直未收到回复，故这边先关闭了，如果有后续新问题或者问题补充，可新开 issue 或在此 issue 中补充。
