### ISSUE TITLE
如何取消kbone 的js错误拦截

### ISSUE THREAD

**Issue by JingFanWang** [Tencent/kbone#361]
我们使用了 webfunny 监控平台，但是发现js报错被kbone框架给直接捕获了，我们如何处理一下，才能让kbone框架不进行js报错的捕获吗

**Comment by JuneAndGreen** [comment]
是指事件句柄那里？

**Comment by JingFanWang** [comment]
对，是事件句柄那里
![image](https://user-images.githubusercontent.com/48482482/112831950-3a8ad200-90c7-11eb-8281-8b4e05ef0062.png)

**Comment by JuneAndGreen** [comment]
miniprogram-render@2.2.9  补充事件句柄异常会抛出 window error 事件。

PS：以上只能针对手动绑定事件或者不处理异常的 Web 框架绑定事件。如果是像 vue 等 Web 框架可能会对事件句柄再包一层 try-catch，这种就需要 Web 框架自身的异常处理机制来监听异常了。
