### ISSUE TITLE
请问Kbone支持将react native转换成小程序运行吗？

### ISSUE THREAD

**Issue by shu-ming** [Tencent/kbone#365]
请问Kbone支持将react native转换成小程序运行吗？

**Comment by JuneAndGreen** [comment]
kbone 没有支持考虑 rn 的场景，主要目标是 web 上的应用同构。如果你的 rn 应用可以转成 web 上运行的 react 应用，理论上应该可以，但是那些 rn 的组件可能有部分需要自己来实现或调整（因为小程序上不一定有完全对应的组件实现，而 web 实现版本不一定能完全转到小程序中，假如有组件依赖了如同步 getBoundingClientRect 这样的接口的话，小程序中目前需要替换成移步接口才行）
