### ISSUE TITLE
vue3.0用vue-cli-plugin-kbone初始化的项目运行报错

### ISSUE THREAD

**Issue by PengfeiShi** [Tencent/kbone#366]
用vue-cli4脚手架搭建的vue3.0项目，用vue-cli-plugin-kbone初始化后在小程序运行报错
![图片](https://user-images.githubusercontent.com/28526358/116355364-526f8600-a82c-11eb-8d56-a93a8d6b973e.png)
是vue-cli-plugin-kbone还未对vue3.0提供支持吗

**Comment by JuneAndGreen** [comment]
是的，vue-cli-plugin-kbone 还未支持 vue3.0

**Comment by PengfeiShi** [comment]
好的，感谢解答
