### ISSUE TITLE
vue-cli-plugin-kbone 用这个插件注入环境变量无法成功，除了修改插件源码还有什么好的解决方案么？

### ISSUE THREAD

**Issue by sunyayue** [Tencent/kbone#367]
"vue-cli-plugin-kbone": "^1.3.9",
    "@vue/cli-service": "~4.5.0",

无论用vue-cli 自带的环境变量配置文件，还是再vue.config.js里面注入
![image](https://user-images.githubusercontent.com/68684132/118959984-6757b900-b995-11eb-8fc7-89e836419278.png)

小程序中均无法使用。
可能是被插件覆盖了，
![image](https://user-images.githubusercontent.com/68684132/118959936-59a23380-b995-11eb-9f4a-c10ba4be2f44.png)
有什么好的处理方案么？

**Comment by JuneAndGreen** [comment]
vue-cli-plugin-kbone@1.4.1 支持了修改插件中的 webpack 配置，参考用法：

https://github.com/Tencent/kbone/blob/3233841e47bcb6aa1fc4036772c499a70733583e/examples/demo4/vue.config.js#L11

**Comment by sunyayue** [comment]
> vue-cli-plugin-kbone@1.4.1 支持了修改插件中的 webpack 配置，参考用法：
> 
> https://github.com/Tencent/kbone/blob/3233841e47bcb6aa1fc4036772c499a70733583e/examples/demo4/vue.config.js#L11

谢谢啊，亲测可用，这种就可以将环境变量注入小程序中，配合之前的webpack注入，就可以多端适配兼容了。
