### ISSUE TITLE
发现了一个input 的样式问题，仅开发者工具出现。

### ISSUE THREAD

**Issue by sunyayue** [Tencent/kbone#368]
大概就是kbone使用rem时，input默认会用一个min-height:1.4rem来初始化，而不是用input直接的样式。
比如1rem=100px，给input的高度为30px，那么初始化的input高度就是140px，但是却只显示30px的高度，会导致input只露出上方很小一部分而看不见字。
大概现象如下：
进入页面看不见文字，但节点审查会发现value存在
![image](https://user-images.githubusercontent.com/68684132/119135087-8bd49380-ba70-11eb-9219-80b583f0734d.png)
点击灰色区域后，文字出现
![image](https://user-images.githubusercontent.com/68684132/119135165-a1e25400-ba70-11eb-8a5c-ec2b48ffad32.png)
推测应该是点击触发了重新渲染。
完整复现代码上传到了这个项目里：
https://github.com/sunyayue/kbone-vue3.git
核心复现代码如下：
<label>
      <input
          value="姓名"
          placeholder="请输入"
          type="text"
      />
    </label>

<style>
label{
  height: 0.3rem;
  display: inline-block;
  background: #eeeeee;
}
input{
  height: .3rem;
  min-height: 0;
}
</style>
然后小程序配置文件中：
global: {
		...
		rem: true
	},
最后在app.vue的mounted函数中添加：
document.documentElement.style.fontSize = 100 + "px"
具体现象与操作就是：
进入页面灰色部分无汉字，点击灰色区域汉字出现。

复现平台只有微信开发者工具，实测预览和真机调试均不会出现此现象。

不清楚这个是否是kbone的问题，满提一下。

**Comment by JuneAndGreen** [comment]
基础库内部实现 bug，预计跟 2.17.2 修复，kbone 这边就不再跟进此问题。

**Comment by sunyayue** [comment]
> 基础库内部实现 bug，预计跟 2.17.2 修复，kbone 这边就不再跟进此问题。

好的，谢谢
