### ISSUE TITLE
kbone-ui将字体转换base64后放到浏览器使用，页面加载渲染相当耗时！

### ISSUE THREAD

**Issue by dongnanyanhai** [Tencent/kbone#369]
目前示例页面中也存在此情况：
https://wechat-miniprogram.github.io/kbone/docs/examples/kbone-ui/weui/index.html

字体weui的数据是base64，页面加载时，这个base64转换字体会耗时1~2秒，等待期页面都是空白的。

**Comment by JuneAndGreen** [comment]
是说 wx-icon 里的字体图标 ？

**Comment by JuneAndGreen** [comment]
kbone-ui@1.0.9 延迟了 wx-icon 里的字体加载，目前应该不会阻塞初始渲染了。

**Comment by dongnanyanhai** [comment]
给力！
