### ISSUE TITLE
vitejs build

### ISSUE THREAD

**Issue by aolsx** [Tencent/kbone#370]
现今vue3项目大都使用 vite 进行开发和构建，
kbone 使用 webpack 构建，感觉比较臃肿。
是否可以通过 vite 构建小程序呢？

**Comment by JuneAndGreen** [comment]
短时间内不会投入人力到其他构建方案上，webpack 的方案已经很成熟了，各方面工具链比较完善，所以我这边会更关心核心能力和 bug fixed。不过开发者们如果了解 kbone 原理的好，倒是可以来帮忙搭建这块生态，目前看最主要的工作就是移植 mp-webpack-plugin 插件。

**Comment by wanxxz** [comment]
粗略 vibe 了一个 mp-webpack-plugin 的 vite 版
能 "跑起来" 但没有深入测试
https://github.com/wanxxz/vite-plugin-kbone
