### ISSUE TITLE
v-html在小程序内渲染单位为百分比的img标签，会将百分比重置为px

### ISSUE THREAD

**Issue by dang0705** [Tencent/kbone#371]
在editor中插入img图片，并且设置默认值为100%。输出的标签正常，单位正常。

```
insertImage() {
  wx.chooseImage({
    count: 1,
    success: (res) => {
      this.editorCtx.insertImage({
        src: res.tempFilePaths[0],
        data: {
          id: 'abcd',
          role: 'god'
        },
        width: '100%',
        success: function (data) {
          console.log(data);
          console.log('insert image success');
        }
      });
    }
  });
}
```

但将editor数据拿到v-html中去渲染后发现，百分比被渲染成了px

**Comment by sunyayue** [comment]
他的v-html渲染前的数据为：`<img src='https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2496571732,442429806&fm=26&gp=0.jpg' width="100%">`
实测确实会将宽度渲染成100px，
直接绑定style="width:100%"则为正常，绑定width="100%"会被渲染成style="width:100px;"。

**Comment by JuneAndGreen** [comment]
miniprogram-render@2.2.12 已修复。

**Comment by sunyayue** [comment]
> miniprogram-render@2.2.12 已修复。

大佬辛苦了。

**Comment by dang0705** [comment]
神速, 谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月25日(星期二) 晚上9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/kbone] v-html在小程序内渲染单位为百分比的img标签，会将百分比重置为px (#371)





 
***@***.*** 已修复。
