### ISSUE TITLE
vue3 ReferenceError: SVGElement is not defined

### ISSUE THREAD

**Issue by aolsx** [Tencent/kbone#372]
vue@3.0.8 开始支持将 app 挂载到 svg 容器，
3.0.7 没问题,taro 之前的BUG。

**Comment by aolsx** [comment]
> svg 组件小程序没有支持，所以 kbone 也没法正儿八经的支持上 svg。
> 
> 另外 taro 的 bug 是指？

demo26：vue3（beta）

vue3版本 > v3.0.7  报错 ReferenceError: SVGElement is not defined

**Comment by JuneAndGreen** [comment]
全局变量问题，配置补充下这个即可兼容：
![image](https://user-images.githubusercontent.com/7931744/119945791-80c9b800-bfc8-11eb-8af1-1446adfe94a2.png)

参考文档：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-globalvars
