### ISSUE TITLE
vue-cli-plugin-kbone无法使用webp图片

### ISSUE THREAD

**Issue by sunyayue** [Tencent/kbone#373]
rt，在vue.config.js里面加了配置不生效
![image](https://user-images.githubusercontent.com/68684132/119925703-88796480-bfa8-11eb-8b6d-7adf07d6b0ba.png)
被vue-cli-plugin-kbone给覆盖了
![image](https://user-images.githubusercontent.com/68684132/119925801-b6f73f80-bfa8-11eb-8414-81c1ca99daf1.png)

能不能添加一个webp的配置或者提供自己修改的配置参数如mpPluginConfig.vue.cdnLimit。
因为小程序每个分包有2M限制，所以我们尽量使用相对较小的webp格式的图片。

**Comment by JuneAndGreen** [comment]
可以在 vue.config.js 的 pluginOptions.kbone.configureWebpack 里修改 kbone 构建中的 webpack 配置，在里面可以追加 webp 相关 rule，demo4 中有修改配置的简单例子。

**Comment by sunyayue** [comment]
> 可以在 vue.config.js 的 pluginOptions.kbone.configureWebpack 里修改 kbone 构建中的 webpack 配置，在里面可以追加 webp 相关 rule，demo4 中有修改配置的简单例子。

对吼，跟上次那个环境变量一样的增加，原来这边可以拿到所有webpack配置进行修改，我以为上次只是追加了插件扩展。
![image](https://user-images.githubusercontent.com/68684132/119938306-c97c7380-bfbe-11eb-8db8-cd955f0d268b.png)
学到了。谢谢大佬！

**Comment by sunyayue** [comment]
> > 可以在 vue.config.js 的 pluginOptions.kbone.configureWebpack 里修改 kbone 构建中的 webpack 配置，在里面可以追加 webp 相关 rule，demo4 中有修改配置的简单例子。
> 
> 对吼，跟上次那个环境变量一样的增加，原来这边可以拿到所有webpack配置进行修改，我以为上次只是追加了插件扩展。
> ![image](https://user-images.githubusercontent.com/68684132/119938306-c97c7380-bfbe-11eb-8db8-cd955f0d268b.png)
> 学到了。谢谢大佬！

这个写法虽然能打包成功，但是会导致其他图片被base64编码两次而无法显示，应为：
![image](https://user-images.githubusercontent.com/68684132/119941302-ffbbf200-bfc2-11eb-89de-ea1802140723.png)
