### ISSUE TITLE
有没有可能监听到节点内部滚动？

### ISSUE THREAD

**Issue by sunyayue** [Tencent/kbone#374]
比如父节点高度为固定值，子节点在父节点内部滚动。
设置kbone的global.windowScroll为true只能监听页面滚动，无法监听上述场景。
尤其是现在使用的VantUI的List与Sticky组件，动态加载与粘性布局均无法使用，想要监听页面滚动手动触发也无法做到。
所以kbone能否实现类似如下的监听：
![image](https://user-images.githubusercontent.com/68684132/119947781-b374b000-bfca-11eb-9dac-c75338db3cf5.png)

**Comment by JuneAndGreen** [comment]
小程序 view 本身没有提供，只有 scroll-view 有 scroll 事件，所以 kbone 也无能为力。如果需要节点 scroll 事件的场景，可以考虑使用 wx-scroll-view。

**Comment by sunyayue** [comment]
> 小程序 view 本身没有提供，只有 scroll-view 有 scroll 事件，所以 kbone 也无能为力。如果需要节点 scroll 事件的场景，可以考虑使用 wx-scroll-view。

嗯，我刚刚也是试了下将父节点替换为scroll-view,是可以的，只是在web端会报错而已。
<wx-scroll-view
    class="base-home"
    ref="home"
    @scroll="handleScroll"
    :scroll-y="true"
  >

**Comment by JuneAndGreen** [comment]
web 端可以引入 kbone-ui，实现了 web 版的 scroll-view

**Comment by sunyayue** [comment]
试了下，好像不支持vue3

**Comment by JuneAndGreen** [comment]
要使用 kbone-ui 1.x 版本，基于 web component 实现的。

**Comment by sunyayue** [comment]
> 要使用 kbone-ui 1.x 版本，基于 web component 实现的。

会有黄色的警告，类似：
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Failed to resolve component: wx-scroll-view 
只能暂时先无视这个警告了
