### ISSUE TITLE
请问kbone中的onShow获取的参数和原生的为啥不一样？

### ISSUE THREAD

**Issue by big-zhangjun** [Tencent/kbone#375]
这边是原生的方式获取onShow的参数
![微信图片_20210615112241](https://user-images.githubusercontent.com/53329880/121989895-759bc800-cdcf-11eb-815a-4b4eaa46eea6.png)

这边是kbone框架里打印的onShow参数
![微信图片_20210615112328](https://user-images.githubusercontent.com/53329880/121989907-792f4f00-cdcf-11eb-9fd2-4aeaae7113ff.png)
请问在kbone onshow的时候中怎么获取shareTicket的参数？

**Comment by JuneAndGreen** [comment]
你需要的是 app onshow 吧，不是 page 的 onshow。page 的 onshow 我记得应该没有参数的？

**Comment by JuneAndGreen** [comment]
app onshow 可以用 wx.onAppShow 或者自定义 app.js （https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss）

**Comment by big-zhangjun** [comment]
> app onshow 可以用 wx.onAppShow 或者自定义 app.js （[https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4 %B9%89-app-js-%E5%92%8C-app-wxss](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89-app-js-%E5%92%8C-app-wxss)）

好的，非常感谢~
