### ISSUE TITLE
通过kbone打包小程序原生组件使用@bindinput绑定editor输入监听不生效

### ISSUE THREAD

**Issue by didudidudu** [Tencent/kbone#376]
通过kbone打包小程序原生组件使用@bindinput绑定editor输入监听不生效，求助一下
另外，打包后的editor组件class类中的height无法生效，如何解决

**Comment by didudidudu** [comment]
经调试，清掉小程序缓存，kbone打包使用@input可以绑定原生组件editor输入监听事件，可以取到输入值

**Comment by JuneAndGreen** [comment]
问题1: 绑定事件不用加 bind，bind 本来是小程序表示绑定事件形式加的前缀，直接监听事件名 @input 的方式。
问题2: 加多一个 min-height，官方样式还有个 min-height

![image](https://user-images.githubusercontent.com/7931744/123217623-5b639780-d4fd-11eb-936c-4c37df210caa.png)
