### ISSUE TITLE
onShareAppMessage同样的return值分享的链接点进去参数不同

### ISSUE THREAD

**Issue by sunyayue** [Tencent/kbone#377]
大致业务流程是这样的：
①首页可以直接进入详情页（分包3）；
②然后首页进入搜索页（分包2），搜索页也可以进入详情页。
出BUG的地方就在于，首页进入详情页分享是成功的，搜索页进入详情页分享出来的消息卡片点进入不显示。
原因详情页是根据id去查询接口显示的，后者此id丢失了，但是两种方式进入的详情页是同一个页面，通过vconsole也确定了return的值是相同的，
通过在app.js 那边打印options发现query有细微不同。
这个是首页分享的消息卡片进入打印的：
![image](https://user-images.githubusercontent.com/68684132/123390435-7e5d7c80-d5cd-11eb-80ed-0acb4d4859f6.png)
这个是搜索页分享的消息卡片进入打印的：
![image](https://user-images.githubusercontent.com/68684132/123390535-99c88780-d5cd-11eb-97c9-6e3d695835a9.png)
后者的query多一个hash，
onShareAppMessage的return代码如下：
![image](https://user-images.githubusercontent.com/68684132/123390699-c7153580-d5cd-11eb-96cd-449b274adbad.png)
然后为了规避这个问题，我采用了如下写法：
![image](https://user-images.githubusercontent.com/68684132/123390832-f3c94d00-d5cd-11eb-947a-6542da77470f.png)
现在二者都是正常了，但是之前的写法为什么在特定场景下失败还是不懂。
所以怀疑是不是onShareAppMessage里面return值的解析有什么问题，同样的return值为什么回出现不同的结果？

**Comment by JuneAndGreen** [comment]
你的做法应该是读出 location.hash 再从里面解出 id，但是后者多了个 hash 参数，会覆盖 targeturl 的 hash 参数，导致你解不开。猜测后者的 hash 参数是来自当前页面的 hash 参数，先前这里的实现在设置 path 时也会带上当前页面的 hash 和 search 参数，这个是不合理的，已在 `mp-webpack-plugin@1.4.1` 中修复，可以试试。

**Comment by sunyayue** [comment]
> mp-webpack-plugin@1.4.1

试过了，我把vue-cli-plugin-kbone更新到1.4.2，用回旧方法可以了。
我获取id用的是这个this.$route.query?.objId，从vue-router里面取的query，之前的query会被置空。

**Comment by sunyayue** [comment]
幸苦了，谢谢！
