### ISSUE TITLE
'appendChild' of undefined

### ISSUE THREAD

**Issue by kaziii** [Tencent/kbone#378]
![image](https://user-images.githubusercontent.com/12526958/124225854-b53a1200-db3a-11eb-82cf-6160d6a9e97c.png)
![image](https://user-images.githubusercontent.com/12526958/124225888-c420c480-db3a-11eb-9503-31064447ee42.png)
这个是我less 编译器的问题吗？
用的vue-cli-plugin-kbone 1.4.2

**Comment by JuneAndGreen** [comment]
小程序不支持动态插入样式，所以如截图中动态插入 style 标签到 head 里的方式无法使用。需要将 css extra 出来，然后 mp-webpck-plugin 插件会转成 wxss，具体可以参考下 demo 的 ？
