### ISSUE TITLE
[BUG]自定义tabbar组件，导致代码上传失败

### ISSUE THREAD

**Issue by Rexexe** [Tencent/kbone#380]
出现的错误如下
![image](https://user-images.githubusercontent.com/27289798/125910722-f458f091-1cb7-4c32-ae4d-9d0d5c7bf420.png)

miniprogram.config.js
![image](https://user-images.githubusercontent.com/27289798/125910662-e8a951bb-324e-41dd-a9ce-e25b0f155a74.png)

打包好之后的app.json
![image](https://user-images.githubusercontent.com/27289798/125910785-103b3a8c-5d85-4e7c-8b8c-97ac681788fa.png)

打包自行添加了iconPath和selectedIconPath导致路径问题，这两个属性在使用自定义tabbar组件的时候没有用，删除即可正常上传代码

**Comment by bobby169** [comment]
#333

**Comment by JuneAndGreen** [comment]
已在 mp-webpack-plugin@1.5.1 中修复，看来是工具那边有上传前的强校验逻辑。
