### ISSUE TITLE
kbone 扩展库的更新机制和基础库的对应关系？

### ISSUE THREAD

**Issue by sssession** [Tencent/kbone#382]
如题。

在文档中看到这样的一句话。

> 因为 kbone 迭代较快，扩展库的版本会稍微落后于 npm 上最新版本，使用时敬请注意。

想了解一下用户微信内扩展库的更新机制是什么？kbone 扩展库和基础库微信版本之间的关系？

**Comment by JuneAndGreen** [comment]
和基础库没有直接关系，除非基础库的版本特别老旧，老旧到连小程序npm功能都还不支持才会有问题。这句话的意思是当npm版本比较稳定时，就会更新一波到扩展库，扩展库你可以认为是一个不占空间计算的插件，可以独立更新，它的更新不依赖于基础库。
