### ISSUE TITLE
kbone中使用<wx-scroll-view>, 为此标签增加的class，渲染后消失了，中间发生了什么？

### ISSUE THREAD

**Issue by niurouweidexiaoyu** [Tencent/kbone#383]
代码中：
wx-scroll-view 标签增加了 class=“common-nav”

渲染后：
scroll-view标签中的 class="h5-wx-component wx-scroll-view wx-comp-scroll-view node-b-1629716649871" 不再存在 类名“common-nav”

对于同一个页面第一次进入的时候，类名是存在的，返回后再次进入，类名就消失了，不太确定中间发生了什么？

**Comment by JuneAndGreen** [comment]
可以log一下对应dom节点的classList？类会在这里面维护，渲染时从这里读取。如果确定排除了业务做了处理的原因的话，可否抽个可复现demo给我？

**Comment by niurouweidexiaoyu** [comment]
用空项目试了下wx-scroll-view 组件，确实没有发现上述问题。目前还不明确，是代码的哪个部分影响了结果，暂时采用了 在 <wx-scroll-view> 生成结构类名中 比如： .wx-scroll-view 写需要的属性；或者直接写到scroll-view的style里面也可以 解决此问题

**Comment by JuneAndGreen** [comment]
ok，那我暂时先 close。后续如果有复现 demo，可以在此处补充给我来试试。
