### ISSUE TITLE
引入了腾讯视频插件，但页面没有渲染出来，也没有任何报错，请问是不支持还是怎么回事？

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#385]
miniprogram.config的配置如下：
![image](https://user-images.githubusercontent.com/29198542/133035211-9886e486-7466-494e-8c6c-4314225f0e4e.png)
页面引用如下：
![image](https://user-images.githubusercontent.com/29198542/133030648-802a7466-4092-44ad-8171-ed9bf4193322.png)
微信开发者显示：
![image](https://user-images.githubusercontent.com/29198542/133030725-b1d59d74-8145-4118-a259-f290b59f2387.png)

**Comment by 1026203093** [comment]
请问有大佬成功引入么

**Comment by JuneAndGreen** [comment]
kbone 没有直接支持插件的引入，要使用插件的组件，必须得用迂回的方式。（这里失败是因为 usingComponents 会被处理掉，而且插件里的组件本身属于自定义组件，无法动态声明）

具体方式：

1、需要先自己实现一个自定义组件，然后 kbone 里面引入该自定义组件：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6
2、之后这个自定义组件里，就可以引入插件了。（实际上几乎所有 kbone 没有直接支持的小程序特性都可以通过这个方式使用）

**Comment by 1026203093** [comment]
嗯 我现在也是通过这种方式才能实现，但是因为我这个视频页面 是一个咨询详情页面，是后台返回出来的数据，我这边就是直接v-html解析出来展示的。这种实现方式总感觉怪怪的

**Comment by JuneAndGreen** [comment]
是的，这个一直有考虑，只是目前仍然没有想到比较优雅的结合方案。
