### ISSUE TITLE
项目编译后base.js有报错，不影响运行，但是想处理掉，不知道改源码的哪一个文件

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#386]
报错：
![image](https://user-images.githubusercontent.com/29198542/133180143-392a4bbb-df39-42ee-a4f8-d7eb2a84508e.png)
报错行：
![image](https://user-images.githubusercontent.com/29198542/133180203-bc67880e-eb84-47c7-bcd3-5dd9d6d4ba70.png)
需要先判断下typeof this.app.then是不是为undefined 但不知道在哪里修改

**Comment by JuneAndGreen** [comment]
噢，可以给你的 createApp 方法是返回一下根组件实例（如果存在的话）或者promise。我这里也补个 app 是否存在的判断。

**Comment by JuneAndGreen** [comment]
> 噢，可以给你的 createApp 方法是返回一下根组件实例（如果存在的话）或者promise。我这里也补个 app 是否存在的判断。

发现我已经补了，你更新 mp-webpack-plugin 到 1.5.1 试试。

**Comment by 1026203093** [comment]
好的呢  谢谢啦   现在不报了。
