### ISSUE TITLE
怎样使用小程序原生的onPageScroll方法 ，或者有没有其他方法 监听滚动条的位置

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#388]
功能是如果窗口显示了某一个元素   页面底部按钮要变成悬浮  所以想通过监听滚动条的位置 然后根据$$getBoundingClientRect()来获取元素的位置，进行判断，但是无法监听滚动条的位置.
document.getElementById("") .addEventListener()方法无效

**Comment by JuneAndGreen** [comment]
https://wechat-miniprogram.github.io/kbone/docs/config/#global-windowscroll

需要配置开启，之后就可以监听 window 的 scroll 事件了（本质上就是 onPageScroll），scroll 事件中的 scrollTop 的获取方法也兼容成 Web 的模式，通过 document.documentElement.scrollTop 获取

**Comment by JuneAndGreen** [comment]
另外根据你的具体需求场景，也可以看看 https://wechat-miniprogram.github.io/kbone/docs/domextend/#window-createintersectionobserver  intersectionObserver 能不能派上用场，demo3 有简单示例

**Comment by 1026203093** [comment]
谢谢大佬
