### ISSUE TITLE
怎样动态改变tabar 的selected

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#390]
![8C59A56C-BC17-4D1F-B10B-377899B69FCA](https://user-images.githubusercontent.com/29198542/134686567-ee4fe2a6-1067-43db-a180-4e90227efe50.jpeg)

在进入健康这个选项的时候，怎样通过某个判断条件来跳转首页去，我在健康页面中通过wxshow方法来监听，但没有改变tabar

**Comment by JuneAndGreen** [comment]
你这个截图看起来不是 kbone 的问题？原生写法 tabbar/自定义 tabbar 问题可以到[微信开放社区](https://developers.weixin.qq.com/community/develop/mixflow)里咨询。

**Comment by 1026203093** [comment]
是kbone中的自定义tabBar，参考的是demo11 ，因为不能在tabBar中动态处理，我就在进入首页之前添加了页面，项目默认进入这个页面，不默认进入首页了，但是不知道有没有其他的解决办法

**Comment by JuneAndGreen** [comment]
我其实没有很理解你的问题，你是想从 tabbar 中的某一页跳到 tabbar 中的另一页吗？如果是的话，你可以直接在自定义tabbar 里封装一个跳页的接口（如果参考 demo11，那就要改一下 selected，同时调一下 switchTab 来切页），然后业务页面里通过 `window.getTabBar()` 这个方式就可以拿到 tabbar 实例，然后调该接口就行。
