### ISSUE TITLE
wx-picker组件中的range-key属性失效

### ISSUE THREAD

**Issue by honorsuper** [Tencent/kbone#391]
<wx-picker mode={'selector'} range={enums} range-key={'label'}>
        <div>{children}</div>
      </wx-picker>

然后range-key属性没有生效

**Comment by JuneAndGreen** [comment]
本地未能复现，react 的话可以参考一下 demo16，里面有使用 range-key 的例子:

![image](https://user-images.githubusercontent.com/7931744/134792658-7dbe1d6a-0a9c-4bbe-8d81-fcd7841c7307.png)

**Comment by honorsuper** [comment]
> 本地未能复现，react 的话可以参考一下 demo16，里面有使用 range-key 的例子:
> 
> ![image](https://user-images.githubusercontent.com/7931744/134792658-7dbe1d6a-0a9c-4bbe-8d81-fcd7841c7307.png)

解决了，是好的，但是原始数据需要使用JSON.stringify()处理一下

**Comment by JuneAndGreen** [comment]
对的，因为 react 它会将属性值强转字符串，为了让对象也能准确传到 kbone 这一层，需要做一下 stringify。
