### ISSUE TITLE
window.$$createIntersectionObserver报找不到node节点

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#393]
相关代码：
![image](https://user-images.githubusercontent.com/29198542/136726076-0fc0a96d-0be7-4ca7-b1f4-fe7564b9d1c7.png)
控制台及页面：
![image](https://user-images.githubusercontent.com/29198542/136726145-ea7fc86c-1c99-4add-a6ca-f9a85f578096.png)

**Comment by JuneAndGreen** [comment]
两个问题：
1、要么使用跨组件选择器，要么将 component scope 必须改为组件，默认小程序的 intersectionObserver 是以组件 shadowTree 范围的
2、observer 传入的也必须是选择器

参考 demo3:

![image](https://user-images.githubusercontent.com/7931744/136757922-058754ac-adf7-48bf-97e4-753535c6e3c9.png)

这里使用了 `.h5-body >>>` 这样的前缀，即使用了跨组件选择器：https://developers.weixin.qq.com/miniprogram/dev/api/wxml/SelectorQuery.select.html

![image](https://user-images.githubusercontent.com/7931744/136758341-ff344c3f-e5b3-4a61-99f1-e1d304f95ac5.png)

当然你也可以直接调用 `wx.createIntersectionObserver`，通过 `[dom].$$wxComponent` 拿到所属自定义组件实例作为 component scope 传入 `wx.createIntersectionObserver`（也就是这个接口的第一个参数）。
