### ISSUE TITLE
每次进入面，控制台会报错，报错信息感觉和业务代码无关 

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#395]
报错如下：
![image](https://user-images.githubusercontent.com/29198542/138646624-947f7499-5ced-4cab-98fc-2c480677334e.png)
报错行：
![image](https://user-images.githubusercontent.com/29198542/138646665-bc67a1ea-e643-4cc0-9f7a-63dbbd8b3d1c.png)
应该是底层代码的或者我配置哪里有问题，请问这个怎么解决呢

**Comment by JuneAndGreen** [comment]
一直未收到回复，故这边先关闭了，如果有后续新问题或者问题补充，可新开 issue 或在此 issue 中补充。
