### ISSUE TITLE
引入echarts后设置makeline 报错，但是同样的代码在echarts官网例子中正常展示

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#397]
控制台报错：
![image](https://user-images.githubusercontent.com/29198542/139362653-8d1bf774-b79d-4478-9616-acf5fda94095.png)

报错源码：
![image](https://user-images.githubusercontent.com/29198542/139362667-4f5699ea-0495-4b73-8091-b0de26ba9633.png)

echarts官网例子：
![image](https://user-images.githubusercontent.com/29198542/139362700-fe4520c5-f474-42f4-8b1c-191d512b591f.png)

自己引用代码：
![image](https://user-images.githubusercontent.com/29198542/139362730-19585323-2f8a-4f76-82b0-63e66e9eb5a3.png)

**Comment by JuneAndGreen** [comment]
一直未收到回复，故这边先关闭了，如果有后续新问题或者问题补充，可新开 issue 或在此 issue 中补充。
