### ISSUE TITLE
引入live-player-plugin直播组件之后报错

### ISSUE THREAD

**Issue by asong51** [Tencent/kbone#398]
![image](https://user-images.githubusercontent.com/23691710/140479910-a9119e86-064a-494f-bea3-c7bd29c514d7.png)
![image](https://user-images.githubusercontent.com/23691710/140479977-9cbce079-7c17-4a4a-af64-c3772422de9d.png)
代码只是多引入了组件这一段

**Comment by JuneAndGreen** [comment]
只是多了这份配置，其他什么代码都没加就报错么？
![image](https://user-images.githubusercontent.com/7931744/140482348-159cb1ec-bf5c-4bfa-88c6-cb5d45227e41.png)

**Comment by asong51** [comment]
是的

**Comment by JuneAndGreen** [comment]
试了下，貌似复现不出来。这里追加的配置也只会写到 app.json 中，按道理不会影响运行中的代码的，你确认去掉配置就不会报错了么？

如果是的话，看看能不能抽一个可以简单浮现问题的 demo 给我？

**Comment by asong51** [comment]
https://github.com/Tencent/kbone/issues/335
更加这里的回答的思路解决了，谢谢

**Comment by JuneAndGreen** [comment]
ok
