### ISSUE TITLE
是否支持 npm 自定义组件？

### ISSUE THREAD

**Issue by sssession** [Tencent/kbone#399]

**Comment by JuneAndGreen** [comment]
如果整个小程序是完整的 kbone 项目的话，目前没有直接支持，不过开发者如果对 webpack 比较熟的话，是可以通过一些定制化插件来做后处理以达到支持效果的；

如果想快捷支持 npm 自定义组件的话，有两个方法。需要先了解下 [kbone 如何引入原生的自定义组件](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)。

然后具体方法实现：

一个是写个脚本，将 npm 组件对应的组件文件拷贝到原生自定义组件的目录中，即配置的 `generate.wxCustomComponent .root` 目录中然后进行声明，可以当成本地的自定义组件来处理。

另一个是将小程序做成原生小程序和 kbone 的混合模式，通过配置 [generate.app](https://wechat-miniprogram.github.io/kbone/docs/config/#generate-app) 可以做到仅输出页面内容，然后走使用自定义组件的方式引入一个原生的自定义组件，然后在该自定义组件中就可以当成是原生小程序开发了，包括引用 npm 自定义组件。

个人觉得如果想快捷处理的话，第一个方法应该可以比较方便的实现你的需求。

**Comment by sssession** [comment]
是否可以 PR 支持这个特性呢？ @JuneAndGreen

**Comment by sssession** [comment]
![image](https://user-images.githubusercontent.com/4843262/142807968-ab344bf4-757c-489a-91ee-7ce9f58d17cc.png)

比如在 usingComponents 中加个属性 isNpm 来标记是来自 npm 的组件。

**Comment by JuneAndGreen** [comment]
可以的，欢迎来提 pr
