### ISSUE TITLE
该项目支持初始化Typescript项目吗？

### ISSUE THREAD

**Issue by Leonard907** [Tencent/kbone#400]
本人目前在做小程序开发，在纠结选择用哪个框架。需要的技术栈是React + Typescript，看了Taro和Rax初始化项目都有ts的选项，想问一下kbone支持ts开发吗？我初始化时没有看到ts选项，还是说需要自行将文件改成ts格式？感谢

**Comment by JuneAndGreen** [comment]
可以用 ts，kbone 的原理不依赖你的源码走的什么路线，只要最终输出给 kbone 的是 js 就行。比如这个 [vue 模板](https://github.com/wechat-miniprogram/kbone-template-vue)就给了使用 ts 的例子，react 也同理，可以参考着看看。
