### ISSUE TITLE
通过document.querySelector('#id)获取不到元素的高，但是报'$$getBoundingClientRect' of null

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#401]
dom代码
![image](https://user-images.githubusercontent.com/29198542/143163048-e582a635-7ae0-4e33-8852-366310a51901.png)

js代码
![image](https://user-images.githubusercontent.com/29198542/143163065-5ac486ac-fdcb-454f-b126-57b3425594a5.png)
我在别的页面是可以获取的，但这个不行，不知道是不是节点在下层自定义组件下或者wx-scroll-view导致的

**Comment by JuneAndGreen** [comment]
你用 document.querySelector 的时候，就不需要 .h5-body >>> 这个前缀了，这个主要是直接用原生接口的 select 相关操作才需要，如果直接调 kbone 模拟出来的 dom 接口就不需要了，你可以直接：document.querySelector(`#list${i}`) 试试。

**Comment by 1026203093** [comment]
我最开始就是用这个 document.querySelector(`#list${i}`)  但是报同样的错，我才加了个根节点。。。

**Comment by JuneAndGreen** [comment]
有报错？是什么样的错误栈和错误信息呢？

还有你换成 document.getElementById 能够获取么？这个要确保节点是在页面里才能找得到节点。如果你确定页面里有节点但是就是无法获取的话，可以给个问题 demo 我来试试？

**Comment by 1026203093** [comment]
页面中能找到节点的 
![image](https://user-images.githubusercontent.com/29198542/143192064-47796ad9-2094-4d74-a03a-d717e705fe20.png)

**Comment by 1026203093** [comment]
知道问题了 因为这个是后台数据渲染的，需要等到后台数据返回后才能获取   不好意思 添堵了

**Comment by JuneAndGreen** [comment]
好的，那我 close 了。
