### ISSUE TITLE
wx-checkbox  和 wx-radio 在safari浏览器不能使用。

### ISSUE THREAD

**Issue by zhouliangshun** [Tencent/kbone#402]
> @yoyo837 目前基础能力比较稳定，如果有需求或者 bug，可以单独提 issue 给我，我这边来处理。

wx-checkbox  和 wx-radio 在safari浏览器不能使用，因为在Base类里使用TouchEvent类，而TouchEvent Safari不支持。

![image](https://user-images.githubusercontent.com/3054251/143203744-ada2df94-74b4-40b6-a485-6312b0a3f34e.png)

_Originally posted by @zhouliangshun in https://github.com/Tencent/kbone/issues/279#issuecomment-977653466_

**Comment by JuneAndGreen** [comment]
是说 kbone-ui 里的 wx-checkbox 和 wx-radio 么？

**Comment by zhouliangshun** [comment]
> 是说 kbone-ui 里的 wx-checkbox 和 wx-radio 么？

是的。

**Comment by JuneAndGreen** [comment]
kbone-ui@1.0.10 补充了 TouchEvent/Touch 的兼容，可以试试。

**Comment by zhouliangshun** [comment]
macos 好像没有问题了，但是ios 现在不报错了，点击没反应。真机测试：iOS 12.5.5 模拟器：iOS 15.0

**Comment by zhouliangshun** [comment]
> kbone-ui@1.0.10 补充了 TouchEvent/Touch 的兼容，可以试试。

还需要在看一下。

**Comment by JuneAndGreen** [comment]
> macos 好像没有问题了，但是ios 现在不报错了，点击没反应。真机测试：iOS 12.5.5 模拟器：iOS 15.0

iOS 15.0.1 的 safari 自测正常，你可以走调试模式或者打个 vConsole 进去看看是否有什么报错？

**Comment by zhouliangshun** [comment]
> > macos 好像没有问题了，但是ios 现在不报错了，点击没反应。真机测试：iOS 12.5.5 模拟器：iOS 15.0
> 
> iOS 15.0.1 的 safari 自测正常，你可以走调试模式或者打个 vConsole 进去看看是否有什么报错？

你那边可以给我一个测试代码么，我这边真机15.03也是不行，我断点了一下onBaseTouchStart没有调用。

**Comment by JuneAndGreen** [comment]
examples/demo27 里就可以，需要将 kbone-ui 更新到最新版本。

**Comment by JuneAndGreen** [comment]
> 你那边可以给我一个测试代码么，我这边真机15.03也是不行，我断点了一下onBaseTouchStart没有调用。

examples/demo27 里就可以，需要将 kbone-ui 更新到最新版本。

**Comment by zhouliangshun** [comment]
> > 你那边可以给我一个测试代码么，我这边真机15.03也是不行，我断点了一下onBaseTouchStart没有调用。
> 
> examples/demo27 里就可以，需要将 kbone-ui 更新到最新版本。

找到问题了，必须要在放到wx-view里才可以。又有新的问题了，ios选中的状态显示异常。




<img width="324" alt="image" src="https://user-images.githubusercontent.com/3054251/143473597-3148fa27-5125-4e31-a256-e437ddf78e6d.png">

**Comment by JuneAndGreen** [comment]
> 找到问题了，必须要在放到wx-view里才可以。

并没有这个要求，我把 demo27 里的所有 wx-view 替换成 div 仍然在 iOS 中的 safari 是可用的。

> 又有新的问题了，ios选中的状态显示异常。

我这边表现是正常的，你说的异常是指没有勾么？这个勾是字体文件，你可以看看是没加载到字体文件还是什么样式影响到了？
![image](https://user-images.githubusercontent.com/7931744/143522469-4f733cde-a101-4874-9783-35227c27bf81.png)

**Comment by JuneAndGreen** [comment]
长时间未收到 demo，故先关闭。后续仍有问题可新开 issue 或 reopen 此 issue。
