### ISSUE TITLE
电商类小程序使用kbone框架，常发‘运行内存不足’的问题

### ISSUE THREAD

**Issue by M4tZheng** [Tencent/kbone#403]
由于使用了kbone框架研发了企业的电商类小程序，UAT阶段会常发如下的运行内存问题

- 小程序首页内容、图片较多
- 调取的后端api较频繁
- iphone xr等手机容易复现问题

请问如果有效解决这种小程序崩溃问题。

![DCIM](https://user-images.githubusercontent.com/29937678/143410064-1f7f1f65-b2f9-4cf3-88d6-78f06f989bb9.jpg)

**Comment by JuneAndGreen** [comment]
kbone 本身应该不会占用过多内存的，可以借助开发者工具定位一下是不是存在内存泄漏？

调用后端接口频繁按道理不会引发过多内存占用，除非请求和返回都是大体积的内容；另外图片过多过大也会引发内存占用过多，这方面只能由业务层面来优化了，比如压缩图片体积、使用懒加载等等。

另外业务方也可以监听内存告警做一些处理避免内存占用加剧：https://developers.weixin.qq.com/miniprogram/dev/api/device/memory/wx.onMemoryWarning.html
