### ISSUE TITLE
createSelectorQuery 拿到的 res 是 null

### ISSUE THREAD

**Issue by javaxiu** [Tencent/kbone#405]
按照小程序官方的写法
```
wx.createSelectorQuery().select('#abc')
     .node((res) => {
       console.log('#### get result', res);
})
```
用这个 node 是为了使用这个库 [lottie-miniprogram](https://www.npmjs.com/package/lottie-miniprogram)
这里拿到的 res 一定是 null 的.

看到网上在说需要加一个 in(this) 的写法 https://blog.csdn.net/weixin_30457465/article/details/95365048?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link   这个 this 应该是指的小程序里的 Page 实例吧，那在 Kbone 环境下需要怎么拿到这个 this 呢？

**Comment by JuneAndGreen** [comment]
wx.createSelectorQuery 是需要指定 scope （即自定义组件/页面）的，也就是要选择节点所属的 shadow-tree（通过调 in 方法传入），不指定相当于从页面根 shadow-tree 里找。

kbone 提供了便捷扩展接口，可以快速拿到 nodesRef 对象：[戳这里看文档](https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getnodesref)

如果因为一些原因必须手动调 wx.createSelectorQuery 的话，可以通过 [dom 节点].$$wxComponent （[戳这里看文档](https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-wxcomponent)）来获取该节点所属的自定义组件，再调 in 传入。又或者也可以直接调 select 时传入穿越选择器，即 `.h5-body >>> #abc`。这里[ QA ](https://wechat-miniprogram.github.io/kbone/docs/qa/#%E7%AD%94%E7%96%91)里也有提到：

![image](https://user-images.githubusercontent.com/7931744/144569625-b022d623-e965-40c4-8460-70c95cd45fbe.png)
