### ISSUE TITLE
query-selector last-child报错

### ISSUE THREAD

**Issue by Z1hgq** [Tencent/kbone#406]
![image](https://user-images.githubusercontent.com/26574371/147522725-d5c2fdeb-becd-4d5d-9099-39055bc27af3.png)
![image](https://user-images.githubusercontent.com/26574371/147522761-1a28b746-1f40-43c7-b07d-87c13345cc14.png)

**Comment by JuneAndGreen** [comment]
我跑测试用例是正常的，能否提供一下可以复现问题的 demo 给我定位一下是什么问题？

**Comment by Z1hgq** [comment]
业务代码跑出的error，所以抱歉暂时没法提供demo。从last-child的写法来看node.parentNode.children[node.
parentNode.children.length - 1]
这个数组至少会有一个元素，但是实际在使用的时候却遇到了取不到元素的情况。是否和#shadow-root有关呢，因为我在尝试使用querySelector或是小程序原生写法去取
#shadow-root节点下的元素时也存在找不到的情况

june01 ***@***.***> 于2021年12月28日周二 16:17写道：

**Comment by JuneAndGreen** [comment]
你说的 #shadow-root 是在工具 wxml 面板看到的 shadow-root 标记吧，这个是因为小程序自定义组件的设计是仿 web-components api 实现的，所以在展示时也采用了同样的展示方式。kbone 的模拟 dom 树是完全在 app service 端，所以两者是没有关联的，按道理只要节点在 dom 树存在，就应该能取到。

那么关于的 dom 树的大致结构和调 querySelector 时的选择器能提供么？

**Comment by Z1hgq** [comment]
页面结构

[image: image.png]

选择器

[image: image.png]

代码实现

[image: image.png]

june01 ***@***.***> 于2021年12月28日周二 17:22写道：

**Comment by JuneAndGreen** [comment]
问题复现了，且修复到 miniprogram-render@2.2.19 。

但是这里建议不要使用 document.$_tree， 直接用 document.querySelector 就好。$_ 前缀是内部属性/方法，按道理外部不应该去调用，是很容易出问题的。

**Comment by Z1hgq** [comment]
好的 多谢

june01 ***@***.***> 于2021年12月29日周三 16:58写道：
