### ISSUE TITLE
如何有效优化页面结构复杂导致setData数据多页面渲染慢的问题

### ISSUE THREAD

**Issue by Z1hgq** [Tencent/kbone#407]
![image](https://user-images.githubusercontent.com/26574371/148342158-dfcff862-dba4-4964-a539-b1212a1e28f6.png)

**Comment by JuneAndGreen** [comment]
对于需要频繁 setData 的部分，可以使用 wx-view 包括一层：https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E5%A4%84%E7%90%86%E9%A2%91%E7%B9%81%E6%9B%B4%E6%96%B0%E7%9A%84-dom-%E8%8A%82%E7%82%B9

这样会单独开一层自定义组件，而自定义组件的更新 diff 是按组件 shadow-tree 为维度的，不会全树 diff，更新性能应该会好上不少。不过不要因为这样可以优化更新性能而全盘使用 wx-view，因为小程序创建自定义组件也会有开销，所以只在必要的地方使用 wx-view 包裹即可，以确保初创性能不会被影响。

**Comment by Z1hgq** [comment]
我将列表项用wx-view包裹起来，但是渲染时间并没有得到优化，视频发到kbone qq群 june这个账号了

**Comment by JuneAndGreen** [comment]
ok，后续在 qq 来沟通具体场景，此 issue 暂且关闭。

**Comment by joneyphair** [comment]
后面有什么结论？解决了吗？

**Comment by JuneAndGreen** [comment]
> 后面有什么结论？解决了吗？

之前排查时怀疑和特定业务有关，appendChild 被疯狂调用，而不是 kbone setData 导致的。需要业务侧排查为何会有疯狂调用 appendChild 的情况，是业务导致还是上层框架导致。

**Comment by Z1hgq** [comment]
仔细看了一下，是因为随着节点的增加之后setData的数据太多了，setData延时很高

june01 ***@***.***> 于2022年4月13日周三 18:54写道：

**Comment by JuneAndGreen** [comment]
@Z1hgq 

如果做了用 wx-view 对频繁更新的部分进行包裹，或者用了比较新的支持了定点更新的包，那么 setData 的数据本身不会太多，除非你是每次都做了大范围更新（比如直接将树的根节点给直接 replace 成另外树的根节点了）。

另外 setData 延时是什么意思？
