### ISSUE TITLE
feature request: style.setProperty

### ISSUE THREAD

**Issue by javaxiu** [Tencent/kbone#408]
需要这个 api `style.setProperty` 用来做 css variable 设置用

**Comment by JuneAndGreen** [comment]
css variable 无法支持，因为 kbone 底层是将 style 对象的操作转成小程序组件的 style 属性，而小程序组件本身没有提供这个能力，所以无法兼容实现。

**Comment by javaxiu** [comment]
![image](https://user-images.githubusercontent.com/4281225/148523757-1cee7db2-d797-474a-b52d-de3cef2602c7.png)
小程序组件本身可以这样做不

**Comment by javaxiu** [comment]
是因为想用 antd-mobile, 里面用到了这个 https://github.com/ant-design/ant-design-mobile/blob/7d0a4675223229d13c28151e95b25110661b4837/src/utils/convert-px.ts#L11 ，通过 kbone 就会报style.setProperty is not a function

**Comment by javaxiu** [comment]
尝试了一下，在 style.js 添加如下方法看起来是可行的
```js
    setProperty = function(key, value) {
      // TODO 要去重一下，上下文可能要存一个 key-value 对象
      this.cssText = this.cssText + `${key}: ${value};`;
    }
```

**Comment by JuneAndGreen** [comment]
确认了下，此方法可行，待后续支持。

**Comment by JuneAndGreen** [comment]
于 miniprogram-render@2.2.20 支持
