### ISSUE TITLE
对齐tdesign

### ISSUE THREAD

**Issue by zairl23** [Tencent/kbone#409]
是否考虑对齐：https://github.com/Tencent/tdesign-miniprogram

**Comment by JuneAndGreen** [comment]
kbone 属于底层框架，一些组件库可能用到了 kbone 无法兼容实现的接口（比如同步 getComputedStyle），所以对于这类情况需要组件库来适配才行。当然如果该组件没有用到这类不支持的接口，那应该是可以直接用。
