### ISSUE TITLE
feature request  :root 修改为 page

### ISSUE THREAD

**Issue by javaxiu** [Tencent/kbone#410]
css variable 会在 `:root {}`  下写 variable, 而这个选择符是 wxss 不支持的，需要相应的替换成 `page{}` 
因此在此处增加一个 selector 判断应该就可以达到效果
https://github.com/wechat-miniprogram/kbone.git/blob/develop/packages/mp-webpack-plugin/src/tool/adjust-css.js#L38
新增一个判断
```typescript
if (selector === ':root') {
   selector = 'page';
}
```
我来提个 pr 也可以 :;)

**Comment by JuneAndGreen** [comment]
已补充到 mp-webpack-plugin@1.5.3
