### ISSUE TITLE
kbone目前是否支持把Vue组件编译成微信小程序自定义组件？

### ISSUE THREAD

**Issue by Awen-hub** [Tencent/kbone#413]
在example中只找到了把整个Vue App编译成小程序App的demo，而目前想实现的需求是把vue编写的组件编译成微信小程序自定义组件，然后在微信小程序原生开发项目中通过usingComponents的形式进行引入。想请教一下目前kbone是否有类似的功能或者未来是否考虑实现类似的功能。

**Comment by JuneAndGreen** [comment]
不支持，对于动态方案来说 vue 组件 -> 自定义组件的做法会有很多限制，首先是 kbone 本身是不理解上层框架的，所以不关心上层是 vue 和 react 还是其他什么，所以就不如耦合 web 框架的静态编译方案那样可以直接做转义。不过最近在研究直接将 kbone 页面作为自定义组件输出，也就是 vue/react app -> 自定义组件，有兴趣的话可以关注这三个核心包的更新日志：https://wechat-miniprogram.github.io/kbone/docs/changelog/ 。
