### ISSUE TITLE
请问，build-windows这个script是做什么用的呢？

### ISSUE THREAD

**Issue by ThenMorning** [Tencent/kbone#414]
"build": "PUBLIC_URL=. node scripts/build.js",
 "build-windows": "set PUBLIC_URL=.&& node scripts/build.js"

**Comment by ThenMorning** [comment]
> "build": "PUBLIC_URL=. node scripts/build.js", "build-windows": "set PUBLIC_URL=.&& node scripts/build.js"

相对build，什么场景才需要build-windows ?

**Comment by JuneAndGreen** [comment]
这是哪里看到的？kbone 里应该没有这东西

**Comment by JuneAndGreen** [comment]
如果是指 preact 模板里的话，那应该是当时加的，在 windows 下构建时调的 script，只是设置变量的方式不同而已。
