### ISSUE TITLE
如何增加一个非页面入口文件

### ISSUE THREAD

**Issue by Miaoxingren** [Tencent/kbone#415]
项目中需要提供一个工具库js给[插件](https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html#%E5%AF%BC%E5%87%BA%E5%88%B0%E6%8F%92%E4%BB%B6)使用，kbone的编译中如何能增加这样的文件入口？

**Comment by JuneAndGreen** [comment]
kbone 只是提供了 webpack 插件将小程序页面输出到小程序。

非页面的话，其实已经跟 kbone 没什么关系了，直接利用 webpack 的能力编到小程序某个目录就好了。

**Comment by Miaoxingren** [comment]
这个工具库js就是kbone项目中用到的一些方法合集，单独打包一份的话就重复了 主包大小不够用

**Comment by JuneAndGreen** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages/async.html  走分包异步化，现在支持跨分包引用 js 了。

**Comment by Miaoxingren** [comment]
分包异步化对基础库版本要求比较高，之前用uniapp增加自定义入口都是没问题的，但是kbone中增加的自定义entry好像被打包成了页面文件，无法正常使用了@JuneAndGreen

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/150732824-5a19b670-593d-43ad-bf9d-55c31d1142d2.png)
这个版本要求已经非常非常低的了。

如果要新增的 kbone 无关文件，最好不要在原有 kbone 构建配置中补充。建议将不关联的输出内容完全解耦开，直接新增一份 webpack 构建任务单独处理额外的任意需求，不然后续想利用 kbone 针对构建做的一些调整也容易受到各种掣肘。
