### ISSUE TITLE
react 的例子中为何需要使用 babel-plugin-class

### ISSUE THREAD

**Issue by javaxiu** [Tencent/kbone#416]
如 https://github.com/Tencent/kbone/issues/314 所示的例子中，描述的 ClassName 变成一个 undefined。排查过程如下：
将 [kbone-template-react clone](https://github.com/wechat-miniprogram/kbone-template-react/blob/master/src/components/counter/index.js) 下来，其中的 Counter.js 代码简化如下：

```jsx
import React from 'react'

const SomeComp = (props) => React.createElement('div', props);

function Counter() {
  console.log('vvvv')
  return (
    <SomeComp className="member" ccc="member">abb</SomeComp>
  )
}

export default Counter;

```

分别构建 web 和 miniprogram，看到构建产物差异如下: 
web 端:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/4281225/153546667-0e9df597-93a1-4621-b317-e2e286050e2d.png">

miniprogram端：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/4281225/153546759-d0330e8d-12ff-4de0-9a6f-53a5a5888ab7.png">

造成如上差异的原因在于[此处](https://github.com/wechat-miniprogram/kbone-template-react/blob/master/scripts/webpack.mp.config.js#L85)使用了 babel-plugin-class 插件

而此 babel-plugin-class 插件内容很简单，就是将 className 变成 class

```jsx

var declare = require("@babel/helper-plugin-utils").declare

module.exports = declare(function (api) {
  api.assertVersion(7);

  return {
    name: "class",
    visitor: {
      JSXAttribute({ node }) {
        if (node.name.name === 'className') {
          node.name.name = 'class';
        }
      }
    }
  };
});
```

所以构建效果是符合插件预期的，但是这个构建结果会导致 react 组件里无法正常传递 className，子组件通过 props.className 是拿不到父级传递过来的 className 的。
https://github.com/Tencent/kbone/issues/314 这个问题中说的，通过改个名字 clzName 就能拿到，也是符合 babel-plugin-class 这个插件的表现效果

因此我想请教一下为何模板中要使用此插件？

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by JuneAndGreen** [comment]
看了下，这个当初是另一大佬帮忙搞 react 支持和提供 react 模板的时候加的，应该是顺手支持了一下 class 的写法，因此补了下这个插件。在 kbone 内置的 [examples](https://github.com/Tencent/kbone/tree/develop/examples) 里应该都没用到 babel-plugin-class。

这个倒不是 kbone 必须的，可以去掉，我重新调整一下 react 模版好了。
