### ISSUE TITLE
在kbone中怎样添加第三方库vant-weapp，可以给一个demo么？

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#420]
H5中 kbone使用vantUI是没问题的 ，但小程序里van-datetime-piker不兼容，所以需要使用vant的微信版，按照引入vantUi一样的方式 ，构建都报错，麻烦可以提供一个vant-weapp 的demo，谢谢啦

**Comment by JuneAndGreen** [comment]
vant-weapp 应该是自定义组件库，所以可参考自定义组件的引入说明：[文档](https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)

> PS：不过不建议页面大范围使用自定义组件（自定义组件的创建有一定开销），如果页面只有数个的话问题不大。
