### ISSUE TITLE
一个页面中两个video，但是不会同时出现 ，通过KboneApi控制视频状态的时候 ，控制台报错

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#421]
报错信息：
 Cannot read property '$$getContext' of null

页面A伪代码：

 v-if=0 
   <shipingref="firstVideo"></shiping>
 v-else
 <shipingref="lasVideo"></shiping>

视频封装代码:
import kboneAPI from "kbone-api";
    videoTap() {
      if (this.play) {
        //开始播放
        kboneAPI.createVideoContext("myVideo").then((res) => {
          res.play();
        });
      } else {
        //当play==false 显示图片 暂停
        kboneAPI.createVideoContext("myVideo").then((res) => {
          res.pause();
        });
      }
      this.play = !this.play;
    },

**Comment by 1026203093** [comment]
微信开发者和安卓都会提示Cannot read property '$$getContext' of null，没问题

**Comment by JuneAndGreen** [comment]
如果是为了拿到 context，建议直接用 kbont 提供的 dom 扩展方法：https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getcontext ，不需要额外引入其他库
