### ISSUE TITLE
定位用到的permission要写在那个位置？ app.json要怎么写？

### ISSUE THREAD

**Issue by dddsssaaa** [Tencent/kbone#422]
定位用到的permission要写在那个位置 app.json要怎么写

**Comment by JuneAndGreen** [comment]
写在 appExtraConfig 中 

https://wechat-miniprogram.github.io/kbone/docs/config/#appextraconfig

**Comment by dddsssaaa** [comment]
> 写在 appExtraConfig 中
> 
> https://wechat-miniprogram.github.io/kbone/docs/config/#appextraconfig
好的 谢谢
