### ISSUE TITLE
页面渲染&button点击响应慢，如何确认是哪个环节引起的性能问题呢

### ISSUE THREAD

**Issue by Z1hgq** [Tencent/kbone#428]

**Comment by Z1hgq** [comment]
DOM数量700+
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/26574371/162949304-e602f59f-4d74-4662-a62c-ad919b883597.png">

可以微信扫描下方的二维码进行体验
<img width="173" alt="image" src="https://user-images.githubusercontent.com/26574371/162949491-ab8610e5-46a4-40c4-a0b2-fa6a5d1e42f8.png">

**Comment by Z1hgq** [comment]
setData数据过多引起的性能问题，暂时无解
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/26574371/163114328-bdb4c973-2ea2-457a-810e-068f40bece9d.png">

**Comment by JuneAndGreen** [comment]
为什么会有一次性更新 600 多个节点的情况……？如果是瀑布流列表的话，可以尝试只渲染 2 ～ 3 屏的数量？

**Comment by Z1hgq** [comment]
> 新 600 多个节点的情况……？如果是瀑布流列表的话，可以尝试只渲染 2 ～ 3 屏

这里是整个页面setData次数的统计，diff表示从开始setData到执行回调函数的时间，现在确实是一次渲染2-3屏的页面，点击加载更多再更新渲染更多数据。diff会随着页面节点的增多而变长，多点几次加载更多之后页面十分卡顿，可以尝试微信扫描上面的菊花码进行体验

**Comment by Z1hgq** [comment]
首屏渲染的界面节点数量大概在700+，点击一次加载更多会新增500左右的节点

**Comment by JuneAndGreen** [comment]
“diff表示从开始setData到执行回调函数的时间”  是指开始 setData 到 setData callback 的耗时么？

如果是这个的话，那确实不好解决了，就算使用原生开发应该也不可避免的会遇到这种问题（不过原生相对对 dom 节点的数量会有所缓解一些）。可能得看看能不能原生支持类似 recycle-view 这样的能力来处理这种长列表的通病了，届时 kbone 就能直接接入。

**Comment by Z1hgq** [comment]
我看是节点越多setData callback的时间越长，是因为会把之前已经渲染好的节点数据也通过setData再次传递吗

june01 ***@***.***> 于2022年4月14日周四 10:05写道：

**Comment by JuneAndGreen** [comment]
小程序 webview 侧会做 diff，所以按道理不会导致重复渲染。不过 diff 本身会因为树变得庞大而被影响到，因为 diff 是自上而下的，所以 wx-view 包裹的这个做法，就是为了减少 diff 的范围的。但是长列表场景通常是在最外层做追加更新，所以不可避免的会让 diff 范围越来越大，因此就得看看能不能原生来解决这个问题。

**Comment by Z1hgq** [comment]
> 小程序 webview 侧会做 diff，所以按道理不会导致重复渲染。不过 diff 本身会因为树变得庞大而被影响到，因为 diff 是自上而下的，所以 wx-view 包裹的这个做法，就是为了减少 diff 的范围的。但是长列表场景通常是在最外层做追加更新，所以不可避免的会让 diff 范围越来越大，因此就得看看能不能原生来解决这个问题。

我去尝试把组件加上recycle-view来实现，还幸苦你这边看看有没有什么可以从kbone这一层优化setData的地方

**Comment by JuneAndGreen** [comment]
kbone 之前有想过一些，但是目前看效果最多也就是复用 recycle-view 逻辑一样，所以感觉还是要根源上有特殊支持才能比较好的解决此问题。

**Comment by Z1hgq** [comment]
> 

有没有想过对setData的数据做diff，只传递更新的数据呢

**Comment by JuneAndGreen** [comment]
kbone 有 diff，100 节点的变化就会 fallback 回全子树 setData。但是这样解决不了 webview 侧的 diff 问题，那是基础库做的底层逻辑。

另外我发现你的小程序里，展示出来的每一项按道理不应该有数百个 dom 这么多，是不是有很多处于 display: none 的状态？如果本身是不会展示，或者不常展示的节点，可以直接去掉以减少节点数，然后对于一顿操作后要展示的节点，可以放到 wx-view 里，减少更新时的 diff。( https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#dom-%E6%A0%91%E7%9A%84%E7%B2%BE%E7%AE%80 )

**Comment by Z1hgq** [comment]
> 

单个卡片的节点数在70左右，点击一次加载更多会加载7-8个卡片，所以单次新增的节点数在500左右。即使不做“加载更多”的操作，页面上的其他交互，例如点击展示“规则”或者“奖品” 也能感受到延时，并且延时随整个页面节点数的增长而增长。代码中其实已经把h5才展示的代码逻辑都去除了。

**Comment by JuneAndGreen** [comment]
`点击展示“规则”或者“奖品” ` 这个如果容器是在一个 wx-view 内，那就不应该会有全树 diff 了，而是局部 diff，按道理延时就可以减轻一些。单个卡片如果无法再精简的话，那就只能待原生来提供优化方案给 kbone 接入了。

**Comment by Z1hgq** [comment]
> 这个如果容器是在一个 wx-view 内，那就不应该会有全树 diff 了，而是局部 diff，按道理延时就可以减轻一些。单个卡片如果无法再精简的话，那就只能待原生来提供优化方案给 kbone 接入了。

现在看来长列表卡片需要使用原生组件混用来进行优化了
