### ISSUE TITLE
kbone-ui 1.0.11版本在react上无法使用的问题

### ISSUE THREAD

**Issue by Larry-Da** [Tencent/kbone#430]
基础库版本：2.14.0
框架：React（使用demo16提供的React kbone模版）

将所有组件全部注册：
import KBoneUI from 'kbone-ui'
KBoneUI.register()

使用：
<mp-loading type="circle"></mp-loading>
但并没有展示出loading的组件

执行nom run mp编译时并未出现error，小程序运行期间也未出现error。

kbone-ui 1.x 看文档应该已经不限制React框架使用了，是否是因为缺少配置了其他东西？

**Comment by JuneAndGreen** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/7931744/164622235-528b53b6-cdac-4a06-bec8-ad03c2a4b2e0.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/7931744/164622357-62378827-2dd6-4911-8ca0-0bd6cdb6d183.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7931744/164622473-cae21fa4-4f8b-4f22-a9b2-2b7cd5c1c8d6.png">


写了个 demo 试了下，貌似没有问题。不过你的 npm run mp 确认是编译到 web 端？

kbone-ui 是给 web 端用的，因为 web 端没有小程序内置组件和 weui 组件，kbone-ui 就是把小程序的这些搬到 web 上跑。

而小程序端本身就内置了所以无需引入，只需要加个配置，然后 kbone 会帮忙补个 weui 的扩展库，然后就能直接用 mp-loading 了：
<img width="893" alt="image" src="https://user-images.githubusercontent.com/7931744/164622890-f3919181-1f37-4bb0-964b-19ac9b9016ef.png">

**Comment by JimmyVV** [comment]
已经收到哦~~~~
