### ISSUE TITLE
引入腾讯OCR sdk ，找不到路径

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#432]
1.文档地址 ：https://cloud.tencent.com/document/product/1007/31071
2.
![image](https://user-images.githubusercontent.com/29198542/166857706-84bc3e33-404c-4d7d-9b9a-f0d3c2be2335.png)
这个kbone中怎样引入呢？
因为这种引入方式不像原生，导致找不到OCR的页面
3.报错信息：
![image](https://user-images.githubusercontent.com/29198542/166857823-0f7a25c5-5b72-49c9-a217-1a1cf2619de0.png)

**Comment by JuneAndGreen** [comment]
需要额外追加 kbone 之外的内容的话，建议不输出 app 相关代码，配置是 [generate.app](https://wechat-miniprogram.github.io/kbone/docs/config/#generate-app)，然后自己手动补充 app.json、app.js、app.wxss 等。等价于 kbone 和原生小程序混合开发的模式。

**Comment by 1026203093** [comment]
我现在就是参考demo21，可以加下您微信详细问下么 ，看这样的话 改动好大了

**Comment by 1026203093** [comment]
现在设置手动添加app一些文件，我是把编译后的复制对应的mp文件夹中，但是并没有生成出app,json这些，现在项目都起不来了。
![image](https://user-images.githubusercontent.com/29198542/166920512-aadd83bf-df32-4742-ad18-882d4efb377f.png)

**Comment by JuneAndGreen** [comment]
报错应该属于基础库/工具的问题，微信内沟通具体细节，故此 issue 关闭。
