### ISSUE TITLE
能否按需渲染Wxml中的bind事件？

### ISSUE THREAD

**Issue by M4tZheng** [Tencent/kbone#433]
使用Kbone开发带来了便利，但是也会有一些性能问题，比如Elements多了之后会有用户出现内存不足闪退问题。
调试时发现Kbone框架会给每个view生成较多bindxxxx事件，请问这些事件是否可以按需生成，在未使用或设置对应事件时，不要渲染出这些bindxxx事件

<img width="926" alt="image" src="https://user-images.githubusercontent.com/29937678/167368315-e4c97c18-f280-4b09-8963-77257be5ccb1.png">

**Comment by JuneAndGreen** [comment]
kbone 的动态创建 dom tree 的方案目前做不到动态 bind 事件，只能模板预先写好所有需要的属性、事件。（因为官方没有提供动态设置属性、绑定事件的能力；而针对可冒泡的事件，如果不绑定到对应的 view 上，会被自定义组件的特性隐藏掉 target）

不过内存不足感觉应该和模板的事件绑定关系不大，事件绑定一直都不是组件里占大头的部分，可以借助工具的 memory 面板看看逻辑上是否有内存泄漏的情况
