### ISSUE TITLE
generate.app 设置为 noemit后，每次都生成config文件，但是tabBarMap没有生成出来，导致每次保存后，都生成一次，需要自己重新添加tabBarMap

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#434]
![1652164891(1)](https://user-images.githubusercontent.com/29198542/167564438-e15cfe4d-2e6d-411b-8e2d-05c1ec3f6c60.png)
每次代码保存都清空，怎样让他不清空或者自己添加tabBarMap呢

**Comment by JuneAndGreen** [comment]
已修复到 mp-webpack-plugin@1.6.1
