### ISSUE TITLE
使用 kbone 打包的微信小程序代码，inner-component.wxml 里面有音视频相关的组件，导致微信小程序提审时需要填相关隐私条例信息

### ISSUE THREAD

**Issue by AymaxLi** [Tencent/kbone#436]
## Background
自查了下，我们的业务代码里面没有调用到音视频相关组件，只有 kbone 的库里面有，请问如何处理比较好。

## Appearance
<img width="2560" alt="2022-05-25 152303" src="https://user-images.githubusercontent.com/19837987/170206111-ae2fc2aa-dc14-44b8-bda6-77f34ec3cd04.png">
<img width="769" alt="2022-05-25 152639" src="https://user-images.githubusercontent.com/19837987/170206120-eb6d3830-316f-4e75-9778-cf8e25dcfd18.png">

**Comment by AymaxLi** [comment]
<img width="2560" alt="2022-05-25 152303" src="https://user-images.githubusercontent.com/19837987/170205323-9a14775c-1537-43ca-9a1f-1da4c5dea3de.png">
<img width="769" alt="2022-05-25 152639" src="https://user-images.githubusercontent.com/19837987/170205355-63d9244c-e484-4885-971f-4254b8c12382.png">

**Comment by AymaxLi** [comment]
自查了下，我们的业务代码里面没有调用到音视频相关组件，只有 kbone 的库里面有，请问如何处理比较好

**Comment by JuneAndGreen** [comment]
如 Z1hgq 所说，目前最好的解法是使用扩展库。后续主仓库层面也会思索一下有什么办法可以处理这种因为动态方案而引入的副作用。

**Comment by AymaxLi** [comment]
> 两种解决办法
> 
> 1. 通过拓展库进行使用 https://wechat-miniprogram.github.io/kbone/docs/guide/optimize.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%89%A9%E5%B1%95%E5%BA%93
> 2. 自己维护miniprogram-element包，删除里面模版代码中的voip-room和live-pusher模版标签

感谢，已通过方法一解决
