### ISSUE TITLE
小程序的Sourcemap匹配调试在kbone能用吗？

### ISSUE THREAD

**Issue by TiffanyVChou** [Tencent/kbone#438]
使用kbone框架后还能使用小程序提供的插件Sourcemap定位错误位置吗
1.下载最新版的开发者工具，菜单-设置-拓展设置-调试器插件
2.sourcemap在小程序后台管理，开发管理-错误日志-错误内容旁边下载最新版本。
3.输入报错位置进行匹配

定位出来全是data问题，属于框架内容，无法定位。
onTabItemTap(data) {
                if (this.window && this.window.onTabItemTap) this.window.onTabItemTap(data)
},

赋微信小程序官方文档
https://developers.weixin.qq.com/miniprogram/dev/devtools/sourcemap.html

**Comment by JuneAndGreen** [comment]
看了下，应该是可以用的。

kbone 项目跑到手机上，一般是有两次编译，一次是本地的 webpack，将 vue/react 等 web 代码编到小程序项目；另一次是小程序的编译后台，在工具点预览/上传，会由小程序后台进行编译打包处理，然后手机上就可以拉取编译后的小程序包运行。

小程序 sourcemap 匹配调试是用来解小程序后台的编包的，可以还原到小程序项目。要还原到 web 代码，就得再走一遍 sourcemap，这个如果需要的话通过 webpack 配置可以生成，和正常 web 端代码构建操作一致。

你提到的 onTabItemTap 是 kbone 透传的，其来自于：https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onTabItemTap-Object-object
