### ISSUE TITLE
Event 构造函数参数问题

### ISSUE THREAD

**Issue by yifan0817** [Tencent/kbone#439]
https://github.com/Tencent/kbone/blob/60b5ed4df429411ad17d98fd4caf00b4370f314c/packages/miniprogram-render/src/event/event.js#L18

Event 构造函数参数这里第一个应该是 typeArg，是 DOMString 类型，表示所创建事件的名称；第二个参数是 eventInit，是 EventInit 类型的字典。 [参考文档](https://developer.mozilla.org/zh-CN/docs/Web/API/Event/Event)

**Comment by JuneAndGreen** [comment]
Event 设计成这样是有一些历史遗留原因，有什么特殊场景是必须使用 Event 构造器的么？

如果是一般的自定义事件可以走 CustomEvent，这个第一个参数就是 typeArg，第二个参数就是 eventInit

**Comment by yifan0817** [comment]
> 

哦哦，了解了，就是发现和标准参数不一致还以为是自己写错了。我这边业务中有一些直接用的 Event，没用 CustomEvent，参数会报错。现在是通过劫持了一下 Event 来兼容这种参数，放在 globalVars 里解决掉了

**Comment by JuneAndGreen** [comment]
好的，我在代码上也补充了一下注释说明
