### ISSUE TITLE
Component is not fount

### ISSUE THREAD

**Issue by skylarblue** [Tencent/kbone#445]
![image](https://user-images.githubusercontent.com/25023100/187444058-8e622058-3a98-41ad-ae26-f7612fd10417.png)
开启编译插件功能后，miniprogram-element虚拟节点指定的默认组件报错
![image](https://user-images.githubusercontent.com/25023100/187444322-27630290-05ef-42cf-be39-7ef5747f039d.png)
开发者工具版本：
![image](https://user-images.githubusercontent.com/25023100/187444405-ac49abb8-5695-41bf-b857-d9a12a826188.png)

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by skylarblue** [comment]
测试了一下，只有开发者工具里会出错，工具的二维码编译预览正常、ci工具编译也是正常的

**Comment by JuneAndGreen** [comment]
> 测试了一下，只有开发者工具里会出错，工具的二维码编译预览正常、ci工具编译也是正常的

好的，我转给负责工具的同学看看

**Comment by skylarblue** [comment]
> 

请问有结论了么

**Comment by JuneAndGreen** [comment]
应该已经修复了，可以使用最新稳定版试试：https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html

**Comment by skylarblue** [comment]
![image](https://user-images.githubusercontent.com/25023100/190301638-c281e609-fd08-4bc3-afd5-c5751259764c.png)
使用了下最新版，还是有报错

**Comment by JuneAndGreen** [comment]
抱歉😂，刚确认了下问题修复了但是还没有正式带上线，预计今天的 nightly 版本会带上，然后按计划下周应该会有个 stable 版本发出，届时也会带上。

**Comment by skylarblue** [comment]
亲测，已ok了
