### ISSUE TITLE
项目采用了混合开发，generate.app设置成noemit模式，现在进入页面一直空白也不报错，不知道什么原因

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#446]
1.mp-webpack-plugin 已升级1.6.1
2.自定义过app.json app.js app.wxss 和 project.config.json

**Comment by 1026203093** [comment]
有一个报错，但不知道有没有影响
[渲染层错误] [jsbridge] invoke remoteDebugInfo fail: too eayly.(env: Windows,mp,1.05.2107090; lib: 2.26.0)

**Comment by 1026203093** [comment]
控制台有一个报错，但不知道有没有影响
[渲染层错误] [jsbridge] invoke remoteDebugInfo fail: too eayly.(env: Windows,mp,1.05.2107090; lib: 2.26.0)

**Comment by JuneAndGreen** [comment]
`[渲染层错误] [jsbridge] invoke remoteDebugInfo fail: too eayly.(env: Windows,mp,1.05.2107090; lib: 2.26.0)`  这个日志无关

如果不设置 noemit 的话，window.open('/starHealth') 就可以跳过去么？

window.open 跳转取决于生成的 config.js 里的 router 字段：
<img width="777" alt="image" src="https://user-images.githubusercontent.com/7931744/190624364-90d88753-6524-4a19-ab4b-cab09342a694.png">

而这个字段是根据插件配置的 router 字段生成的：
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7931744/190624470-fc3db26d-9e54-4201-a715-92fb4e0634f3.png">

可以先检查下这个字段。如果这个字段配置正常还无法跳转的话，看能不能抽个 demo 给我看看？
