### ISSUE TITLE
组件样式不能用scoped，打包出来的样式都是全局的，会造成相互污染，请问有办法避免吗？

### ISSUE THREAD

**Issue by jasonxxp** [Tencent/kbone#449]

**Comment by JuneAndGreen** [comment]
受限于小程序自身不支持属性选择器，所以无法支持 scoped，对于动态技术（kbone 即属于此类）的话只能手动规避污染问题。比如按 BEM 命名规范来规避一部分冲突问题。

如果是静态技术或者直接原生开发的话，可以使用原生组件的 styleIsolation 属性。
