### ISSUE TITLE
小程序头像昵称填写问题

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#450]
![image](https://user-images.githubusercontent.com/29198542/194743571-942396b6-a690-4f13-93c3-1fa579c0b747.png)

基础库使用的是 2.26..1   不管上传多大的图片 都不会触发chooseavatar的回调 ，请问是kbone还没有兼容么，还是什么问题

**Comment by JuneAndGreen** [comment]
小程序基础库是在 2.21.2 支持的，kbone 相当于 web 代码和小程序原生之间的胶水层，所以还是需要小程序原生有支持才能使用。
 
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/7931744/194796217-06d11b4c-4c81-4087-b597-d365038f60dc.png">

**Comment by 1026203093** [comment]
但是我2.26.1版本在2.21.2之上了哈   但是并没有触发bindchooseavatar的回调方法，您的意思是说只能使用原生的方法么 不能使用kbone的

**Comment by JuneAndGreen** [comment]
抱歉，眼拙看成 2.16.1 了。。。

你用的 miniprogram-element / miniprogram-render 版本是？

**Comment by 1026203093** [comment]
![image](https://user-images.githubusercontent.com/29198542/194985638-27143d12-9d1d-4336-ae79-9507a0ce2ae0.png)
![image](https://user-images.githubusercontent.com/29198542/194985698-4fe062f1-00ec-4606-9122-737b6359da34.png)
最新的是多少呢

**Comment by JuneAndGreen** [comment]
按道理 miniprogram-element@2.2.11 以上就支持了，我用 demo3 试了下 2.26.1 是可以的，你直接跑 examples/demo3 ，然后切到基础库 2.26.1 试试呢？

<img width="467" alt="image" src="https://user-images.githubusercontent.com/7931744/195326941-ab6b061d-8f70-41ce-a1a4-a012340572b3.png">

**Comment by 1026203093** [comment]
![image](https://user-images.githubusercontent.com/29198542/195517701-4e093496-2969-4c3c-8622-5e1acaa1ee81.png)
![image](https://user-images.githubusercontent.com/29198542/195517817-5772fa46-de17-4e7c-8925-a59d7ac3479f.png)

直接把代码下载下来运行demo3  运行不了呀 大佬

**Comment by JuneAndGreen** [comment]
构建一下 npm

**Comment by 1026203093** [comment]
![image](https://user-images.githubusercontent.com/29198542/196073461-af730b99-2c73-499a-905f-693ccd76ca16.png)
不行呀 我在开发者工具中  构建npm 还是报错 是不是我文件夹中错了呀 
我在kbone\kbone-develop\examples\demo3中npm install 然后 npm run mp 最后在微信开发中打开dist 的mp文件

**Comment by JuneAndGreen** [comment]
为了方便调试，demo 列表中有些有配置 autoBuildNpm，有些没有，对于没有的构建流程是：

1、进入 demo 目录执行 npm install 安装项目依赖和 npm run mp 构建出小程序目录 dist
2、进入 dist 执行 npm install 安装小程序自身的依赖
3、工具执行构建 npm 将 node_modules 处理到 miniprogram_npm 目录，这个目录是小程序最终会读取的目录。而 node_modules 里因为可能携带大量小程序用不到的代码会占用空间，因此会被小程序忽略。

如果配置了 autoBuildNpm 或者使用了扩展库，2 和 3 这两步就不需要了。

<img width="864" alt="image" src="https://user-images.githubusercontent.com/7931744/196082073-d73698e9-e492-4f9c-88c7-f1515aa126e3.png">
文档这里有比较完整的构建流程：https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html

**Comment by 1026203093** [comment]
可以了   之前没有在构建好的mp中执行npm install  
我这边执行这个例子是onchooseAvatar是可以回调的，但是我本地项目步行 
![image](https://user-images.githubusercontent.com/29198542/196085891-437ca7eb-8d0e-4009-b8e5-3d567ce1c0c7.png)

**Comment by JuneAndGreen** [comment]
那么问题应该就出在 web 框架或者业务代码了，你可以打印一下你本地项目那个 wx-button 节点的属性看看？看看有没有将 open-type 成功设置上去？

如果有的话，麻烦给下可以复现代码的片段，我看看为什么事件抛不出来。

**Comment by 1026203093** [comment]
已经设置了 open-type 
![image](https://user-images.githubusercontent.com/29198542/196312207-7439475e-5b55-4897-b68e-410211dcc0d2.png)

但是项目中启动就报这个自定义组件的错 其他分支是没有报的 只有这个分支有 不知道是不是这个原因导致的
![image](https://user-images.githubusercontent.com/29198542/196312352-c82a860f-e79a-4791-ade2-d70832d8323b.png)

**Comment by JuneAndGreen** [comment]
这个报错看来是使用外部自定义组件那里配置有问题，方便给一下完整 demo 么？可以脱敏后发到邮箱 wx-miniprogram@qq.com，我本地定位一下
