### ISSUE TITLE
由于扩展库没有更新，导致小程序头像填写能力有问题，

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#452]
现在扩展库更新了么，如果更新了 我本地怎么更新呀  上次是您给的扩展库包放到本地的

**Comment by 1026203093** [comment]
上个月kbone维护老师说最近会给更新的，但是这么久了也没更新，请问什么时候更新呢

**Comment by 1026203093** [comment]
请问下更新了么 扩展库

**Comment by JuneAndGreen** [comment]
扩展库目前正在处理中

**Comment by 1026203093** [comment]
> 扩展库目前正在处理中

请问下 扩展库现在更新了么

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by JuneAndGreen** [comment]
> > 扩展库目前正在处理中
> 
> 请问下 扩展库现在更新了么

年前一周应该就已经全量了，可以试试？

**Comment by 1026203093** [comment]
> > > 扩展库目前正在处理中
> > 
> > 
> > 请问下 扩展库现在更新了么
> 
> 年前一周应该就已经全量了，可以试试？

**Comment by JuneAndGreen** [comment]
扩展库手机端我试了下可以了呀？你切到扩展库的时候有没有删掉 miniprogram_npm？两者不能混用。

第二个应该是工具的 bug，刚看了下工具里的扩展库没有及时更新，不过真机是 ok 的。工具问题我提到相关同学来跟进看看。

**Comment by 1026203093** [comment]
我删了 还是不行 基础库2.26.2
![image](https://user-images.githubusercontent.com/29198542/218042834-9d8b57c9-eddc-4daa-95bf-575c18c5fb1a.png)

**Comment by JuneAndGreen** [comment]
试试我刚提交的 demo35，我本地真机看是没问题的（这里不要用真机调试，而是点预览，不然还是会和工具连在一起）。

**Comment by JuneAndGreen** [comment]
> 试试我刚提交的 demo35，我本地真机看是没问题的（这里不要用真机调试，而是点预览，不然还是会和工具连在一起）。

进入 demo35 后，npm install + npm run mp 就会在 demo35/dist/mp 下生成小程序，已经配置了扩展库，所以直接工具打开即可

**Comment by 1026203093** [comment]
确实 真机预览是可以的 开发者工具中头像和昵称都不行 ，可以更新下开发者工具

**Comment by JuneAndGreen** [comment]
> 真机预览确实是可以的， 开发者工具中获取头像和昵称的小问题是不是下次更新开发者工具版本就不会出现哈

工具无效问题我已经提给相关同学了，似乎不是工具本身的问题，而是工具从后台拉取到的扩展库就是旧的，所以应该是需要后台同学来帮忙修复。

**Comment by JuneAndGreen** [comment]
已修复，清空工具缓存后，重启工具将会拉取最新扩展库

<img width="766" alt="image" src="https://user-images.githubusercontent.com/7931744/218948631-f21da5af-e8ca-4448-b610-245ce0dfd8ca.png">
