### ISSUE TITLE
touchMove的时候 e.preventDefault无效 

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#453]
因为业务中  通过touch事件实现类似swipe的功能，可滑动区域左右滑动的时候，页面整体都Y轴也会变动，看到kbone中的eventjs中有这么一段   
 preventDefault() {
        // 目前仅支持 a 标签的点击阻止
        this.$_preventDefault = true
    }
是这个导致的么，那如何才能阻止默认事件呢

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by 1026203093** [comment]
> 那扩展库版本太旧导致头像填写能力的问题麻烦更新下哈 上次一个维护的老师是直接给我element，和render那两个文件包让我直接放到我本地中 但是这个太占项目空间了

**Comment by 1026203093** [comment]
> > 那扩展库版本太旧导致头像填写能力的问题麻烦更新下哈 上次一个维护的老师是直接给我element，和render那两个文件包让我直接放到我本地中 但是这个太占项目空间了

请问下这个扩展库更新了么

**Comment by JuneAndGreen** [comment]
扩展库更新问题正在处理

**Comment by JuneAndGreen** [comment]
kbone 本身无法支持标准的 preventDefault，因为小程序的双线程架构，事件是异步来到逻辑层的，此时逻辑层想要去阻止视图层的事件势必会滞后，所以小程序本身也没支持这个能力，因此 kbone 也无法完全兼容。kbone 提供的 preventDefault 只能做到阻止点击跳转等可以监管的事件。

如果要实现阻止外层滚动之类的，可以使用 wx-catch 等，他会将事件绑定使用 catchbind 来处理：

https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BA%8B%E4%BB%B6%E7%B3%BB%E7%BB%9F%E6%89%A9%E5%B1%95

**Comment by 1026203093** [comment]
感谢大佬及时解惑，那就是说如果kbone中 利用 touchmove 和 toustart ，touchend 无法做到和小程序的轮播效果一样对么 ？
因为我swipe-item中会有点击事件，如果使用wx-catch的话   在touchmove的时候  就不能使整个bodyY轴移动了。
我现在使用的是wx-capture ，但是我移动沿着X轴触发touchmove的时候    body的Y轴也在滚动
而且现在我移动的时候 是使用translate3D改变当前swipe-item X轴位置  安卓机会很卡，ios就比较流畅

**Comment by 1026203093** [comment]
辛苦大佬细心的解答  第一种 第二种我这边可以再尝试下(按需控制外层是否可以滚动估计还是做不到)，但是第三种有一个弊端  就是自定义组件他会默认放到主包里面，可以放到我指定的分包么

**Comment by JuneAndGreen** [comment]
第三种想放分包倒不是不行，只是需要绕一下，你可以把真正复杂逻辑的组件放到分包，然后主包这里留一个 wrapper 自定义组件给 kbone 用。而主包这个 wrapper 自定义组件可以通过分包异步化这个特性来使用任意分包的自定义组件：https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages/async.html

相当于主包做个没有具体业务逻辑的管理组件，根据你需要使用不同分包的自定义组件即可。

**Comment by 1026203093** [comment]
谢谢大佬指点
