### ISSUE TITLE
Demo23 新增的defaultTargetUrl  传入不带 origin 的 url，会影响原来页面的origin？

### ISSUE THREAD

**Issue by TiffanyVChou** [Tencent/kbone#454]
targeturl 是经过编码的 location.href（也可以是 /test/abcde?id=123#hash 这样不带 origin 的 url，以缩减页面路由的长度，kbone 会自动取配置中的 origin 进行拼接），新增的defaultTargetUrl需要传入带origin的url，否则会影响原来页面的origin？

文档：https://wechat-miniprogram.github.io/kbone/docs/config/#pages-%E9%A1%B5%E9%9D%A2%E5%90%8D%E7%A7%B0-defaulttargeturl

例子：https://github.com/Tencent/kbone/tree/develop/examples/demo23

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by JuneAndGreen** [comment]
会，不过这确实是个问题，我修一下。

**Comment by JuneAndGreen** [comment]
mp-webpack-plugin@1.6.4  fixed

**Comment by JuneAndGreen** [comment]
发现了一个 bug，1.6.4 中遇到没有 targeturl 的时候也会进行 origin 拼接，这和以前的表现没对齐。故在 mp-webpack-plugin@1.6.5 中修复对齐。
