### ISSUE TITLE
自定义app.js中 onShow中拿到的参数没有实时更新？

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#455]
kbone中自定义了app.js来对小程序的生命周期进行一些业务处理，但是发现一个问题，流程如：
1.从A小程序某页面的列表中 点击某一项数据 把数据的id带过来   到我这边的小程序跳转路径是page/share/index?id=1  我这边在自定义的appjs的onShow中可以获取到id为1 ，也成功进入我这边的页面
2.但是我返回到A小程序 再点击另一个数据带id为2   路径是page/share/index?id=2  到我这边  appjs的onShow中获取到的仍然是id为1
除非刷新一次  才能正确拿到值
我估计是因为短时间内 打开的是同一个页面 导致第二次直接打开了上一次的页面，故导致此问题
请问下这个怎样才能拿到最新的值呢？

**Comment by 1026203093** [comment]
不好意思 后页发现onShow时有更新 只是我把数据存到了setStorage中 后面get的时候还是之前的，现在放到了globalData中是可以的

**Comment by JuneAndGreen** [comment]
OK，我这边看也并不会没有更新，除了走 app.js onShow 获取，也可以通过 https://developers.weixin.qq.com/miniprogram/dev/api/base/app/life-cycle/wx.getEnterOptionsSync.html 来获取进入参数的。
