### ISSUE TITLE
wx-button open-type="agreePrivacyAuthorization" 回调无法触发

### ISSUE THREAD

**Issue by 1026203093** [Tencent/kbone#465]
![image](https://github.com/Tencent/kbone/assets/29198542/8c8a98b5-6256-4429-acbd-d897b9127e71)
无法触发agreeprivacyauthorization事件，只能通过click事件触发
已经更新了这个miniprogram-element到 2.2.15了 

是不是扩展库没有更新呢

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by JuneAndGreen** [comment]
扩展库还在灰度中，预计周五可以全量

**Comment by 1026203093** [comment]
好的

**Comment by JuneAndGreen** [comment]
> 好的
前段时间应该已经全量了。
