### ISSUE TITLE
是否可以支持 Construct 3 引擎？

### ISSUE THREAD

**Issue by XHXIAIEIN** [Tencent/kbone#467]
Construct 是一款基于浏览器的游戏引擎，它依赖于原生浏览器，基于WebGL渲染(WebGL1、WebGL2、WebGPU)。
https://editor.construct.net/

这是一个使用 Construct 导出的H5项目

Demo1: 简单的 Hello World 显示
[Construct-HelloWorld.zip](https://github.com/wechat-miniprogram/minigame-adaptor/files/12734135/Construct-HelloWorld.zip)

Demo2: 显示简单的 HTML 表格，演示原生 dom 的渲染能力
[Construct-HTML-Table.zip](https://github.com/Tencent/kbone/files/12734160/Construct-HTML-Table.zip)

Demo3: 使用 JavaScript 编写的 Tween 示例
[Tween example.zip](https://github.com/Tencent/kbone/files/12734315/Tween.example.zip)

Demo4: 一个较复杂的游戏Demo，有完整的游戏交互逻辑，调用手机陀螺仪
[Rocket Barrel Template.zip](https://github.com/wechat-miniprogram/minigame-adaptor/files/12734139/Rocket.Barrel.Template.zip)

**Comment by JuneAndGreen** [comment]
这个项目是通过模拟 dom 树的方式来实现让 Web 代码跑到小程序上，似乎和 Construct 引擎没有任何交集？

**Comment by XHXIAIEIN** [comment]
除了游戏内容是渲染在 <canvas> 元素，它也支持 HTML Element，可以在 dom 树里面创建 HTML 元素，应该是可以跟 kbone 一起工作的

**Comment by XHXIAIEIN** [comment]
除了游戏内容是渲染在 <canvas> 元素，它也支持 HTML Element，可以在 dom 树里面创建 HTML 元素，应该是可以跟 kbone 一起工作的

**Comment by JuneAndGreen** [comment]
这种看起来应该往小游戏方面发展，小程序这边本身受限于体积与环境等各种原因，暂时不会考虑主动兼容太多框架/工具，除非本身的兼容成本/维护成本比较低。
