### ISSUE TITLE
kbone递归方案

### ISSUE THREAD

**Issue by 1679236695** [Tencent/kbone#471]
kbone为什么不使用模版自已递归自已，要使用自定义组件递归的方式，是自定义组件递归的性能更好吗

**Comment by JuneAndGreen** [comment]
小程序模板递归有限制层数，无法像自定义组件一样可以做到无限递归。另外模板递归在更新时是整树 diff，自定义组件可以按组件维度 diff，diff 范围会更小。

关于性能，自定义组件在创建时会比纯模板慢一些，但是更新时会更快。
