### ISSUE TITLE
组件属性对齐：input 组件 auto-focus 即将弃用，需要使用 focus 替代

### ISSUE THREAD

**Issue by YangYongAn** [Tencent/kbone#474]
参考文档地址：https://developers.weixin.qq.com/miniprogram/dev/component/input.html

<img width="1049" alt="image" src="https://github.com/Tencent/kbone/assets/4987317/16cdd556-6ffb-49e4-afc3-47b63c362e8f">

**Comment by JuneAndGreen** [comment]
kbone 的实现是去掉了 auto-focus，直接使用 focus 的
