### ISSUE TITLE
请求 Blazor WebAssmebly 支持

### ISSUE THREAD

**Issue by ElderJames** [Tencent/kbone#479]
你好，请问能否支持 Blazor WebAssembly? 
入口文件是html，里面加载一个通过webpack构建好的blazor.webassembly.js文件。这个文件会加载依赖的多个 wasm 文件和json文件。不知到这样的加载过程如何用kbone实现。

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by JuneAndGreen** [comment]
兼容起来坑很多，不建议在小程序环境上使用对浏览器环境依赖较重的框架，像 vue、react 能够较好兼容是因为其有完整的 webpack 编译链路和对浏览器接口较轻量的依赖，可以比较简单模拟出其需要的环境（但是一些特性仍然因为无法模拟而无法支持，比如同步 getBoundingClientReact 和 getComputedStyle 等）。

如果有小程序 wasm 的需求可参考：https://developers.weixin.qq.com/miniprogram/dev/framework/performance/wasm.html ，但是其也不完全等价于 WebAssembly
