### ISSUE TITLE
我想问下后期是否继续更新维护？

### ISSUE THREAD

**Issue by xiaodeji** [Tencent/kbone#480]
目前公司项目正在选型想用这个框架，但看到项目已经5个多月没维护了，我有点担心一旦用上就不维护的情况

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by xiaodeji** [comment]
还有为什么还要用vue2而不是更新到最新的vue3

**Comment by JuneAndGreen** [comment]
vue3 应该很早就提供过一个 demo 了，建议使用此工具前了解一下其原理，这样才有办法兼容一些 vue、react 中一些奇怪的设计，以及对于产生的性能损耗有一些认知。

目前此工具的状态是：如果没有特殊情况，不会做大变更。如果是有组件需求或恶性 bug 的话可以提 issue，我这边会跟进处理。

此工具是提供给一些有特殊需求的用户使用的，如果只是想用 vue、react 就不建议直接使用此工具，这样会错失一些原生小程序的优化和特性，所以如果没有特殊需求的话更推荐直接用原生来写，遇到问题也可以直接提给小程序方。
