### ISSUE TITLE
vue3 demo 26 看不懂

### ISSUE THREAD

**Issue by tesla-cat** [Tencent/kbone#482]
- 能不能给个详细点的教程啊   demo 26 vue3 看不懂啊  
- 能用vue router 吗

- 为什么每个页面都要 `main.mp.js`

![image](https://github.com/user-attachments/assets/6aa3e540-8221-4e69-ac5a-ee72ebaa1890)

- 为什么结构和 cli 给出的 很不一样  没有 `.babelrc` 这些

![image](https://github.com/user-attachments/assets/798306c7-d41c-485e-b7ba-f6db67ead83c)

**Comment by JuneAndGreen** [comment]
参考[文档](https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html#%E7%BC%96%E5%86%99-webpack-%E9%85%8D%E7%BD%AE)

demo 是仅供参考的最简写法，有其他需求自己补充即可。

**Comment by JuneAndGreen** [comment]
补充两个问题的回复：

> 能用vue router 吗

A：只要没有用到原生不支持的特性 / kbone 没实现的特性，就可以。vue 2.x 时期的 vue router 应该就有相关 demo，因为其底层使用的 history api 在 kbone 是有支持的。

> 为什么每个页面都要 main.mp.js

上述文档里有说明，这是为了兼顾同时构建到 web 的情况而设置的，在 web 和在小程序的启动流程会略有不同，所以需要两个不同的启动逻辑。如果只考虑小程序端就可以只跑小程序的启动逻辑。
