### ISSUE TITLE
vue3 demo 26 bug, 希望给出最新的 kbone + vue3 + vue-router 示例

### ISSUE THREAD

**Issue by tesla-cat** [Tencent/kbone#483]
```js
[ pages/page1/index.json 文件内容错误] pages/page1/index.json: ["usingComponents"]["element"]: "miniprogram-element"，在 C:/Users/ricky/Desktop/demo26/dist/mp/pages/page1/miniprogram-element
C:/Users/ricky/Desktop/demo26/dist/mp/pages/page1/miniprogram-element/index
C:/Users/ricky/Desktop/demo26/dist/mp/pages/page1/miniprogram_npm/miniprogram-element
C:/Users/ricky/Desktop/demo26/dist/mp/pages/page1/miniprogram_npm/miniprogram-element/index
C:/Users/ricky/Desktop/demo26/dist/mp/pages/miniprogram_npm/miniprogram-element
C:/Users/ricky/Desktop/demo26/dist/mp/pages/miniprogram_npm/miniprogram-element/index
C:/Users/ricky/Desktop/demo26/dist/mp/miniprogram_npm/miniprogram-element
C:/Users/ricky/Desktop/demo26/dist/mp/miniprogram_npm/miniprogram-element/index 路径下未找到组件(env: Windows,mp,1.06.2409140; lib: 2.25.3)
```

![image](https://github.com/user-attachments/assets/3cd4890e-30a7-41d9-985f-78462589a096)

**Comment by JuneAndGreen** [comment]
这个报错不是 bug，是因为你没有构建 npm，小程序因为有个打包上传的操作，所以不能直接将 node_modules 上传，因为里面有太多非业务需要的代码。使用前建议先看下 [kbone 搭建文档](https://wechat-miniprogram.github.io/kbone/docs/guide/tutorial.html#%E6%89%A7%E8%A1%8C%E6%9E%84%E5%BB%BA) 和小程序官方的 [npm 使用文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)。

kbone 本身只是一个运行在 web 代码和原生小程序中间的适配层工具，webpack 的操作就是基于此对目标代码做了点包装。有其他自定义需求基本上围绕着 webpack 来做就行。

**Comment by JuneAndGreen** [comment]
* 在小程序里是建议使用网络字体，一个是印象中 wxss 不支持本地链接，一个是本地放字体文件会占用包体积，而小程序本身是有包体积限制的。
* 第三方 ui 库有些用到了小程序中无法兼容实现的接口，比如同步的 getBoundingClientRect、getComputedStyle 这些，因为小程序本身的限制无法实现成同步接口，所以视其具体实现会有些限制。

至于其他跨端框架，我个人不是特别了解。其实如果没有其他特殊需求的话，我是更推崇使用原生来开发小程序的，原生开发性能可以做定制化优化，很多功能也可以直接接入而不需要经过一个中间层的封装。
