### ISSUE TITLE
mp-webpack-plugin 是否有vite版本

### ISSUE THREAD

**Issue by niubaobaozsy** [Tencent/kbone#484]

**Comment by JimmyVV** [comment]
已经收到哦~~~~

**Comment by JuneAndGreen** [comment]
没有，考虑到维护成本，未来应该也不会考虑支持 vite。

**Comment by wanxxz** [comment]
vibe 了一个 mp-webpack-plugin 的 vite 版
能 "跑起来" 最简的 react 项目 但没有深入测试
https://github.com/wanxxz/vite-plugin-kbone
