### ISSUE TITLE
kbone编译web正常，但是编译小程序一直报这个没见过的错误，怎么解决

### ISSUE THREAD

**Issue by anjularzwl** [Tencent/kbone#52]
![image](https://user-images.githubusercontent.com/27289513/70887921-07c7e200-201a-11ea-98d1-28b723b7e651.png)

**Comment by anjularzwl** [comment]
有大佬回复下没？

**Comment by TomVista** [comment]
去掉  miniprogram.config.js
    generate: {
        autoBuildNpm: 'npm',
    },
或者改成 false

**Comment by TomVista** [comment]
关闭后需要自行处理 dist/mp   => npm i

**Comment by JuneAndGreen** [comment]
使用最新的 mp-webpack-plugin 试试？现已改成使用 execa 来执行 npm 构建命令
