### ISSUE TITLE
canvasCtx.drawImage(tempFilePath) 报错

### ISSUE THREAD

**Issue by saoraozhe3hao** [Tencent/kbone#67]
这是微信小程序文档里的样例代码
```
wx.chooseImage({
  success: function(res){
    ctx.drawImage(res.tempFilePaths[0], 0, 0, 150, 100)
    ctx.draw()
  }
})
```
在kbone中这样写，报错
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)';at api chooseImage success callback function

**Comment by JuneAndGreen** [comment]
你使用的 ctx 是通过 node 方法拿到的么？还是通过 context 方法呢？如果是 node 的话，这里很可能是在新的 canvas 上混用了旧的使用方法了

**Comment by JuneAndGreen** [comment]
新的 canvas 要这样绘制图片：

```js
const ctx = canvas.getContext('2d');
const img = canvas.createImage()
img.onload = function() {
        ctx.drawImage(img, 0, 0)
}
img.src = 'a.jpg'
```

**Comment by yanyang1116** [comment]
> 这是微信小程序文档里的样例代码
> 
> ```
> wx.chooseImage({
>   success: function(res){
>     ctx.drawImage(res.tempFilePaths[0], 0, 0, 150, 100)
>     ctx.draw()
>   }
> })
> ```
> 
> 在kbone中这样写，报错
> Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)';at api chooseImage success callback function

新的2d，临时路径，不要画在画板上。
显示不出来的，直接用网络地址@saoraozhe3hao
