### ISSUE TITLE
pages/page1/miniprogram-render" is not defined

### ISSUE THREAD

**Issue by heyishi** [Tencent/kbone#78]
demo11编译时无法编译examples\demo11\dist\mp\node_modules\miniprogram-element和examples\demo11\dist\mp\node_modules\miniprogram-render，小程序IDE运行错误
VM42 WAService.js:1 Uncaught Error: module "pages/page1/miniprogram-render" is not defined
    at require (VM42 WAService.js:1)
    at VM42 WAService.js:1
    at index.js:1
    at require (VM42 WAService.js:1)
    at <anonymous>:23:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1580787656635:1230)
    at HTMLScriptElement.script.onload (appservice?t=1580787656635:1273)
![图片](https://user-images.githubusercontent.com/5929961/73711964-90721d00-4743-11ea-872b-5d6a6e26f3ce.png)

**Comment by JuneAndGreen** [comment]
使用相关依赖需要以下两步：

1、进入小程序项目目录执行 npm install
2、执行小程序开发者工具的” npm 构建“

是否缺少了以上其中一步？相关文档：https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html

**Comment by yexk** [comment]
我也和你遇到了同样的问题。，不过我的是官方默认demo。 
![微信截图_20200220014512](https://user-images.githubusercontent.com/19749521/74860571-db1aa880-5383-11ea-87ab-8a953d114a95.png)

**Comment by yexk** [comment]
> 使用相关依赖需要以下两步：
> 
> 1、进入小程序项目目录执行 npm install
> 2、执行小程序开发者工具的” npm 构建“
> 
> 是否缺少了以上其中一步？相关文档：https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html

我进行了这两部操作。结果又出现另外一个错误。是我姿势不对吗？
![image](https://user-images.githubusercontent.com/19749521/74861588-92fc8580-5385-11ea-96f8-7afd043e9f3f.png)

**Comment by JuneAndGreen** [comment]
@yexk 看来已经有了对应依赖了，尝试下关闭项目重新打开，有可能是工具没有识别到 npm 构建带来的文件变化。

**Comment by msdog** [comment]
执行npm i => 构建npm 依旧报错
VM404:1 thirdScriptError
nativeParseInt is not a function;at "pages/app/index" page lifeCycleMethod onLoad function
TypeError: nativeParseInt is not a function

**Comment by JuneAndGreen** [comment]
nativeParseInt 这个应该是你的代码依赖中出现的变量，可以定位进去看看是不是这里使用了 window.parseInt ？如果是的话，可以更新到 miniprogram-render 到 0.8.1 版本，此版本将 parseInt 和 parseFloat 挂到了 window 上。

**Comment by zedwang** [comment]
在mac上也是包这个错

**Comment by JuneAndGreen** [comment]
@zedwang 报的是 pages/page1/miniprogram-render" is not defined 还是 nativeParseInt is not a function？参考上述几个手段都无法解决是么？

**Comment by zedwang** [comment]
报的是 pages/page1/miniprogram-render" is not defined
后面我用了react项目模板里面的mp config，就没问题了

**Comment by heyishi** [comment]
看到这个已经close了，是不是已经修复了？关闭的时候不需要说明吗

**Comment by JuneAndGreen** [comment]
@heyishi 前面已说明，如还有问题，可以 reopen。
![image](https://user-images.githubusercontent.com/7931744/77906100-f4374300-72b9-11ea-9da8-d10c37402304.png)
