### ISSUE TITLE
如何优雅实现多页/跨页面状态管理？

### ISSUE THREAD

**Issue by xmsz** [Tencent/kbone#87]
由于遵循 web 端多页机制，以往的的全局状态管理方法都不太合适

所以，有什么优雅的办法来解决多页/跨页面的状态管理？

现在
1. Web 上的各种页面通信用不了
2. 最基础的`window.addEventListener('storage',()=>{})`的也用不行
3. 各种以往挂载到 app 的方法不符合规范
4. 使用 js 文件单例机制也不符合规范

**Comment by xxxBW** [comment]
多页在web上通信可以用cookie之类的来存储

**Comment by xmsz** [comment]
> 多页在web上通信可以用cookie之类的来存储

不是本地储存是通信。。。 cookie 怎么通信？通信指的是
1. 状态变化广播

全局状态管理还包括
1. 状态变化同步

在单页里，实现状态同步很简单。kbone 单个页面也没问题。但现在多个页面没办法实例都不是一个
然后只能选择通信方案，但是以往我们通信有浏览器提供的 api。或者最粗暴就是监听本地储存变化。现在也不行

**Comment by TomVista** [comment]
小程序页面生命周期事件,打开页面 返回页面后,更新页面数据,缺点是,不实时

**Comment by xmsz** [comment]
> 小程序页面生命周期事件,打开页面 返回页面后,更新页面数据,缺点是,不实时

这个方案之一，不过不推荐，因为小程序的生命周期web没有。

而两者都有的是对storage（kbone自己封装了所以支持）的监听，所以推荐使用这个方案。

**Comment by JuneAndGreen** [comment]
已提供跨页面的通信和数据存储方法，文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%B7%A8%E9%A1%B5%E9%9D%A2%E9%80%9A%E4%BF%A1%E5%92%8C%E8%B7%A8%E9%A1%B5%E9%9D%A2%E6%95%B0%E6%8D%AE%E5%85%B1%E4%BA%AB

参考例子（此例子中所有页面共享一个 vuex 的 state）：https://github.com/Tencent/kbone/tree/develop/examples/demo22

**Comment by xmsz** [comment]
> 已提供跨页面的通信和数据存储方法，文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E8%B7%A8%E9%A1%B5%E9%9D%A2%E9%80%9A%E4%BF%A1%E5%92%8C%E8%B7%A8%E9%A1%B5%E9%9D%A2%E6%95%B0%E6%8D%AE%E5%85%B1%E4%BA%AB
> 
> 参考例子（此例子中所有页面共享一个 vuex 的 state）：https://github.com/Tencent/kbone/tree/develop/examples/demo22

非常给力

**Comment by JuneAndGreen** [comment]
备注：在原先的 demo22 里全局使用 vuex 的例子中，存在某些缺陷：页面销毁后 getter/setter 未被取消和 __ob__ 属性覆盖问题，其中 __ob__ 覆盖问题已提供工具包解决。相关 issue #71 ，后续相关问题在 #71 中跟进处理。
