### ISSUE TITLE
小程序内置 picker-view 组件无法滚动

### ISSUE THREAD

**Issue by ChrisCindy** [Tencent/kbone#88]
示例代码如下：picker-view 组件可正常显示，但是滚动后会复位，也即无法选择具体值
```js
import React, { useState } from 'react'

function Counter() {
  const [value, setValue] = useState([0, 1]);
  function onChange(e) {
    console.log(e.detail.value);
    setValue(e.detail.value);
  };

  return (
    <div>
      <picker-view onChange={onChange} value={value}>
        <picker-view-column>
          <view>春</view>
          <view>夏</view>
          <view>秋</view>
          <view>冬</view>
        </picker-view-column>
        <picker-view-column>
          <view>2011</view>
          <view>2012</view>
          <view>2013</view>
          <view>2014</view>
          <view>2015</view>
          <view>2016</view>
          <view>2017</view>
          <view>2018</view>
        </picker-view-column>
      </picker-view>
    </div>
  )
}

export default Counter

```
下面是具体表现的 gif 截图：
![2020-02-25 17_00_21](https://user-images.githubusercontent.com/10289782/75231550-9910bd00-57f0-11ea-92f8-76dccd66b25d.gif)

**Comment by lehui521** [comment]
emm，其实这种东西最好和官方的实例对比一下，如果他的可以滚动，你的不可以，看看是不是什地方写错了，慢慢删减代码，又或是什么地方的代码影响到了

**Comment by ChrisCindy** [comment]
> emm，其实这种东西最好和官方的实例对比一下，如果他的可以滚动，你的不可以，看看是不是什地方写错了，慢慢删减代码，又或是什么地方的代码影响到了

第一，kbone 好像没有提供 picker-view 使用的官方实例；
第二，我贴的代码就是按照小程序的官方实例来写的，没有一处多余的功能，已经达到最简状态，如果有用的不对的地方欢迎指正。

**Comment by JuneAndGreen** [comment]
@ChrisCindy 我在 demo16 里补充了 react 中使用 picker-view 的例子，发现并没有自动复位的情况：https://github.com/Tencent/kbone/blob/develop/examples/demo16/src/picker-view.jsx

你可以试试这个例子看看可不可以？

**Comment by JuneAndGreen** [comment]
@ChrisCindy 
picker-view 重置问题已发现，只要重新设置 value 就会触发，原因是 react 自动将传进去的数组转成字符串了，导致透传给小程序后识别不了。这里已针对 picker-view 做了兼容（miniprogram-element@1.0.4），开发者也可以通过 setAttribute 的方式来设置值。

onChange 不触发是因为 react 限制了自定义事件的绑定方式，小程序内置组件的事件可以理解为是 Web 端的自定义事件，所以得使用 addEventListener 的方式来监听，demo16 已更新。

**Comment by xmsz** [comment]
> @ChrisCindy
> picker-view 重置问题已发现，只要重新设置 value 就会触发，原因是 react 自动将传进去的数组转成字符串了，导致透传给小程序后识别不了。这里已针对 picker-view 做了兼容（miniprogram-element@1.0.4），开发者也可以通过 setAttribute 的方式来设置值。
> 
> onChange 不触发是因为 react 限制了自定义事件的绑定方式，小程序内置组件的事件可以理解为是 Web 端的自定义事件，所以得使用 addEventListener 的方式来监听，demo16 已更新。

```
 <wx-picker
              mode="selector"
              value={props.selectorInfo.value}
              range={props.selectorInfo.range}
            >
              <div class="article-text article-select-content">
                123
              </div>
            </wx-picker>
```

普通的wx-picker也出现？

当改变value以后.article-text article-select-content就消失了
![image](https://user-images.githubusercontent.com/5879146/78628173-01f65500-78c6-11ea-86e3-092db474ef87.png)

![image](https://user-images.githubusercontent.com/5879146/78628185-091d6300-78c6-11ea-977f-ddb6bf1b6de1.png)

**Comment by JuneAndGreen** [comment]
@xmsz  是的，react 这点比较坑。不过 kbone 对于普通类型数组做了兼容处理，对于 range 这种可能传入复杂对象数组的情况，支持传入 json 串来处理。
