### ISSUE TITLE
提供一个在线的demo呗，展示一下kbone的特性

### ISSUE THREAD

**Issue by netroby** [Tencent/kbone#89]
提供一个在线的demo呗，展示一下kbone的特性
我不是很有勇气来下载一个，然后一步步构建一个demo，能否提供一个在线demo，让我看看kbone有哪些本领。如何吸引我

**Comment by JuneAndGreen** [comment]
在线案例：
![image](https://user-images.githubusercontent.com/7931744/75505863-5da40780-5a17-11ea-9ff2-c82e8fc56488.png)
