### ISSUE TITLE
地图组件支持吗？

### ISSUE THREAD

**Issue by bulolo** [Tencent/kbone#91]
地图组件支持web和小程序？？同时？？

**Comment by JuneAndGreen** [comment]
小程序端可以使用 wx-map 来渲染地图组件，web 端的话按照原本 web 端的方式接入地图 sdk 即可。

如果是 vue 组件（兼容小程序和 web 端）的话，可以在 kbone-ui 这边提 issue 需求：https://github.com/wechat-miniprogram/kbone-ui/issues。
