### ISSUE TITLE
vue-kbone 编译好慢啊

### ISSUE THREAD

**Issue by wzs28150** [Tencent/kbone#94]
尝试用了一下vue-kbone写小程序 改一点 得等半天  。。。

**Comment by xmsz** [comment]
webpack 里开启 cache:true，babel-loader 开始 cache 会很很多（遇到问题重启就行）
不过 webpack 本身如果不支持热加载处理这种就很蛋疼确实很慢。

**Comment by JuneAndGreen** [comment]
应该是项目比较大且复杂？我这边试了下一个比较复杂的项目构建，一次大概30s左右，mp-webpack-plugin 处理大概数百ms，对比构建成 web 端的耗时并没差多少。其实 mp-webpack-plugin 是在构建完成后做的后置处理，在进到这个插件之前的构建流程就是正常 webpack 构建流程和 web 端构建是一样的，所以像 cache、happypack、thread-loader 等 webpack 常用的构建加速手段都是可用，可以尝试一下？

至于 xmsz 提到的热更新，因为小程序无法动态执行 js，也没想到比较好的替代方案，就暂时无法支持了。

**Comment by xmsz** [comment]
确实目前的话，使用webpack的cache是最效的办法，目前我其中一个中型项目，第一次启动比较久。第二次同个文件基本就是几百毫秒。快的话20ms 就可以。

如果是100ms 以内的话，其实就不影响了。毕竟小程序重新加载也要很久。

当然要达到极致的快还是 gulp 比较粗暴，但是只适合原生小程序那种，写一个文件，编译一次。
