### ISSUE TITLE
kbone-template-react 引入第三方库eacharts太大，怎么办？

### ISSUE THREAD

**Issue by lhC0** [Tencent/kbone#96]

**Comment by JuneAndGreen** [comment]
可以尝试按需引入。

这里不要直接使用 ecomfe/echarts-for-weixin 这个例子，因为这里是引入了完整的 echarts 文件，可以参考 [demo20](https://github.com/Tencent/kbone/tree/develop/examples/demo20)。这个 demo 虽然是使用的 vue ，而且 demo 里也是引入了完整的 echarts，但是原理是想通的，走 webpack 构建即可，具体可以查看 echarts 的官方文档：https://www.echartsjs.com/zh/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts
